import type { TranslationKey } from '../i18n/translations'

interface Model {
  readonly slug: string
  readonly canonicalSlug?: string
  readonly name: string
  readonly displayName: TranslationKey
  readonly description: TranslationKey
  readonly directory: 'diffusion_models' | 'checkpoints' | 'loras' | 'controlnet' | 'clip_vision' | 'model_patches' | 'vae' | 'text_encoders' | 'audio_encoders' | 'latent_upscale_models' | 'upscale_models' | 'style_models' | 'partner_nodes'
  readonly huggingFaceUrl: string
  readonly docsUrl?: string
  readonly blogUrl?: string
  readonly ogImage: string
  readonly thumbnail: string
  readonly featured: boolean
  readonly workflowCount: number
  readonly tags: readonly string[]
  readonly publishedDate: string
  readonly modifiedDate: string
}

export const models: readonly Model[] = [
  {
    slug: 'nano-banana',
    name: 'Nano Banana',
    displayName: 'models.nano-banana.displayName' as TranslationKey,
    description: 'models.nano-banana.description' as TranslationKey,
    directory: 'partner_nodes',
    huggingFaceUrl: '',
    docsUrl: 'https://docs.comfy.org/tutorials/partner-nodes/google/nano-banana-pro',
    ogImage: '/images/models/nano-banana-og.png',
    thumbnail: '/images/models/nano-banana-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['partner_nodes', 'google', 'image-generation'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'kling-ai',
    name: 'Kling AI',
    displayName: 'models.kling-ai.displayName' as TranslationKey,
    description: 'models.kling-ai.description' as TranslationKey,
    directory: 'partner_nodes',
    huggingFaceUrl: '',
    docsUrl: 'https://docs.comfy.org/tutorials/partner-nodes/kling/kling-motion-control',
    ogImage: '/images/models/kling-ai-og.png',
    thumbnail: '/images/models/kling-ai-thumb.webp',
    featured: true,
    workflowCount: 11,
    tags: ['partner_nodes', 'kling', 'video-generation'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'meshy-ai',
    name: 'Meshy AI',
    displayName: 'models.meshy-ai.displayName' as TranslationKey,
    description: 'models.meshy-ai.description' as TranslationKey,
    directory: 'partner_nodes',
    huggingFaceUrl: '',
    docsUrl: 'https://docs.comfy.org/tutorials/partner-nodes/meshy/meshy-6',
    ogImage: '/images/models/meshy-ai-og.png',
    thumbnail: '/images/models/meshy-ai-thumb.webp',
    featured: true,
    workflowCount: 3,
    tags: ['partner_nodes', 'meshy', '3d-generation'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'umt5-xxl-fp8-e4m3fn-scaled',
    name: 'umt5_xxl_fp8_e4m3fn_scaled.safetensors',
    displayName: 'models.umt5-xxl-fp8-e4m3fn-scaled.displayName' as TranslationKey,
    description: 'models.umt5-xxl-fp8-e4m3fn-scaled.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors',
    ogImage: '/images/models/umt5-xxl-fp8-e4m3fn-scaled-og.png',
    thumbnail: '/images/models/umt5-xxl-fp8-e4m3fn-scaled-thumb.webp',
    featured: true,
    workflowCount: 34,
    tags: ['text_encoders', 'umt5', 'xxl', 'fp8', 'e4m3fn', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan-2-1-vae',
    name: 'wan_2.1_vae.safetensors',
    displayName: 'models.wan-2-1-vae.displayName' as TranslationKey,
    description: 'models.wan-2-1-vae.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors',
    ogImage: '/images/models/wan-2-1-vae-og.png',
    thumbnail: '/images/models/wan-2-1-vae-thumb.webp',
    featured: true,
    workflowCount: 29,
    tags: ['vae', 'wan'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ae',
    name: 'ae.safetensors',
    displayName: 'models.ae.displayName' as TranslationKey,
    description: 'models.ae.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Lumina_Image_2.0_Repackaged/resolve/main/split_files/vae/ae.safetensors',
    ogImage: '/images/models/ae-og.png',
    thumbnail: '/images/models/ae-thumb.webp',
    featured: true,
    workflowCount: 26,
    tags: ['vae', 'ae'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-2-5-vl-7b-fp8-scaled',
    name: 'qwen_2.5_vl_7b_fp8_scaled.safetensors',
    displayName: 'models.qwen-2-5-vl-7b-fp8-scaled.displayName' as TranslationKey,
    description: 'models.qwen-2-5-vl-7b-fp8-scaled.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors',
    ogImage: '/images/models/qwen-2-5-vl-7b-fp8-scaled-og.png',
    thumbnail: '/images/models/qwen-2-5-vl-7b-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 25,
    tags: ['text_encoders', 'qwen', 'vl', '7b', 'fp8', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-vae',
    name: 'qwen_image_vae.safetensors',
    displayName: 'models.qwen-image-vae.displayName' as TranslationKey,
    description: 'models.qwen-image-vae.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors',
    ogImage: '/images/models/qwen-image-vae-og.png',
    thumbnail: '/images/models/qwen-image-vae-thumb.webp',
    featured: true,
    workflowCount: 19,
    tags: ['vae', 'qwen', 'image'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'clip-l',
    name: 'clip_l.safetensors',
    displayName: 'models.clip-l.displayName' as TranslationKey,
    description: 'models.clip-l.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/clip_l.safetensors?download=true',
    ogImage: '/images/models/clip-l-og.png',
    thumbnail: '/images/models/clip-l-thumb.webp',
    featured: true,
    workflowCount: 14,
    tags: ['text_encoders', 'clip'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 't5xxl-fp16',
    name: 't5xxl_fp16.safetensors',
    displayName: 'models.t5xxl-fp16.displayName' as TranslationKey,
    description: 'models.t5xxl-fp16.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp16.safetensors?download=true',
    ogImage: '/images/models/t5xxl-fp16-og.png',
    thumbnail: '/images/models/t5xxl-fp16-thumb.webp',
    featured: true,
    workflowCount: 12,
    tags: ['text_encoders', 't5xxl', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'clip-vision-h',
    name: 'clip_vision_h.safetensors',
    displayName: 'models.clip-vision-h.displayName' as TranslationKey,
    description: 'models.clip-vision-h.description' as TranslationKey,
    directory: 'clip_vision',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors',
    ogImage: '/images/models/clip-vision-h-og.png',
    thumbnail: '/images/models/clip-vision-h-thumb.webp',
    featured: true,
    workflowCount: 12,
    tags: ['clip_vision', 'clip', 'vision'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux2-vae',
    name: 'flux2-vae.safetensors',
    displayName: 'models.flux2-vae.displayName' as TranslationKey,
    description: 'models.flux2-vae.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux2-dev/resolve/main/split_files/vae/flux2-vae.safetensors',
    ogImage: '/images/models/flux2-vae-og.png',
    thumbnail: '/images/models/flux2-vae-thumb.webp',
    featured: true,
    workflowCount: 9,
    tags: ['vae', 'flux2'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 't5xxl-fp8-e4m3fn-scaled',
    canonicalSlug: 't5xxl-fp16',
    name: 't5xxl_fp8_e4m3fn_scaled.safetensors',
    displayName: 'models.t5xxl-fp8-e4m3fn-scaled.displayName' as TranslationKey,
    description: 'models.t5xxl-fp8-e4m3fn-scaled.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp8_e4m3fn_scaled.safetensors',
    ogImage: '/images/models/t5xxl-fp8-e4m3fn-scaled-og.png',
    thumbnail: '/images/models/t5xxl-fp8-e4m3fn-scaled-thumb.webp',
    featured: true,
    workflowCount: 8,
    tags: ['text_encoders', 't5xxl', 'fp8', 'e4m3fn', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-3-4b',
    name: 'qwen_3_4b.safetensors',
    displayName: 'models.qwen-3-4b.displayName' as TranslationKey,
    description: 'models.qwen-3-4b.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/text_encoders/qwen_3_4b.safetensors',
    ogImage: '/images/models/qwen-3-4b-og.png',
    thumbnail: '/images/models/qwen-3-4b-thumb.webp',
    featured: true,
    workflowCount: 8,
    tags: ['text_encoders', 'qwen', '4b'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-edit-2509-fp8-e4m3fn',
    name: 'qwen_image_edit_2509_fp8_e4m3fn.safetensors',
    displayName: 'models.qwen-image-edit-2509-fp8-e4m3fn.displayName' as TranslationKey,
    description: 'models.qwen-image-edit-2509-fp8-e4m3fn.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_2509_fp8_e4m3fn.safetensors',
    ogImage: '/images/models/qwen-image-edit-2509-fp8-e4m3fn-og.png',
    thumbnail: '/images/models/qwen-image-edit-2509-fp8-e4m3fn-thumb.webp',
    featured: true,
    workflowCount: 8,
    tags: ['diffusion_models', 'qwen', 'image', 'edit', 'fp8', 'e4m3fn'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'gemma-3-12b-it-fp4-mixed',
    name: 'gemma_3_12B_it_fp4_mixed.safetensors',
    displayName: 'models.gemma-3-12b-it-fp4-mixed.displayName' as TranslationKey,
    description: 'models.gemma-3-12b-it-fp4-mixed.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/ltx-2/resolve/main/split_files/text_encoders/gemma_3_12B_it_fp4_mixed.safetensors',
    ogImage: '/images/models/gemma-3-12b-it-fp4-mixed-og.png',
    thumbnail: '/images/models/gemma-3-12b-it-fp4-mixed-thumb.webp',
    featured: true,
    workflowCount: 7,
    tags: ['text_encoders', 'gemma', '12b', 'it', 'fp4', 'mixed'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ltx-2-spatial-upscaler-x2-1-0',
    name: 'ltx-2-spatial-upscaler-x2-1.0.safetensors',
    displayName: 'models.ltx-2-spatial-upscaler-x2-1-0.displayName' as TranslationKey,
    description: 'models.ltx-2-spatial-upscaler-x2-1-0.description' as TranslationKey,
    directory: 'latent_upscale_models',
    huggingFaceUrl: 'https://huggingface.co/Lightricks/LTX-2/resolve/main/ltx-2-spatial-upscaler-x2-1.0.safetensors',
    ogImage: '/images/models/ltx-2-spatial-upscaler-x2-1-0-og.png',
    thumbnail: '/images/models/ltx-2-spatial-upscaler-x2-1-0-thumb.webp',
    featured: true,
    workflowCount: 7,
    tags: ['latent_upscale_models', 'ltx', 'spatial', 'upscaler', 'x2'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-i2v-lightx2v-4steps-lora-v1-high-noise',
    name: 'wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors',
    displayName: 'models.wan2-2-i2v-lightx2v-4steps-lora-v1-high-noise.displayName' as TranslationKey,
    description: 'models.wan2-2-i2v-lightx2v-4steps-lora-v1-high-noise.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors',
    ogImage: '/images/models/wan2-2-i2v-lightx2v-4steps-lora-v1-high-noise-og.png',
    thumbnail: '/images/models/wan2-2-i2v-lightx2v-4steps-lora-v1-high-noise-thumb.webp',
    featured: true,
    workflowCount: 7,
    tags: ['loras', 'wan2', 'i2v', 'lightx2v', '4steps', 'lora', 'v1', 'high'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-i2v-lightx2v-4steps-lora-v1-low-noise',
    name: 'wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors',
    displayName: 'models.wan2-2-i2v-lightx2v-4steps-lora-v1-low-noise.displayName' as TranslationKey,
    description: 'models.wan2-2-i2v-lightx2v-4steps-lora-v1-low-noise.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors',
    ogImage: '/images/models/wan2-2-i2v-lightx2v-4steps-lora-v1-low-noise-og.png',
    thumbnail: '/images/models/wan2-2-i2v-lightx2v-4steps-lora-v1-low-noise-thumb.webp',
    featured: true,
    workflowCount: 7,
    tags: ['loras', 'wan2', 'i2v', 'lightx2v', '4steps', 'lora', 'v1', 'low'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-1-vace-1-3b-fp16',
    name: 'wan2.1_vace_1.3B_fp16.safetensors',
    displayName: 'models.wan2-1-vace-1-3b-fp16.displayName' as TranslationKey,
    description: 'models.wan2-1-vace-1-3b-fp16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_vace_1.3B_fp16.safetensors',
    ogImage: '/images/models/wan2-1-vace-1-3b-fp16-og.png',
    thumbnail: '/images/models/wan2-1-vace-1-3b-fp16-thumb.webp',
    featured: true,
    workflowCount: 6,
    tags: ['diffusion_models', 'wan2', 'vace', '3b', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan21-causvid-bidirect2-t2v-1-3b-lora-rank32',
    name: 'Wan21_CausVid_bidirect2_T2V_1_3B_lora_rank32.safetensors',
    displayName: 'models.wan21-causvid-bidirect2-t2v-1-3b-lora-rank32.displayName' as TranslationKey,
    description: 'models.wan21-causvid-bidirect2-t2v-1-3b-lora-rank32.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan21_CausVid_bidirect2_T2V_1_3B_lora_rank32.safetensors',
    ogImage: '/images/models/wan21-causvid-bidirect2-t2v-1-3b-lora-rank32-og.png',
    thumbnail: '/images/models/wan21-causvid-bidirect2-t2v-1-3b-lora-rank32-thumb.webp',
    featured: true,
    workflowCount: 6,
    tags: ['loras', 'wan21', 'causvid', 'bidirect2', 't2v', '3b', 'lora', 'rank32'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'umt5-xxl-fp16',
    canonicalSlug: 'umt5-xxl-fp8-e4m3fn-scaled',
    name: 'umt5_xxl_fp16.safetensors',
    displayName: 'models.umt5-xxl-fp16.displayName' as TranslationKey,
    description: 'models.umt5-xxl-fp16.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp16.safetensors',
    ogImage: '/images/models/umt5-xxl-fp16-og.png',
    thumbnail: '/images/models/umt5-xxl-fp16-thumb.webp',
    featured: true,
    workflowCount: 6,
    tags: ['text_encoders', 'umt5', 'xxl', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-1-vace-14b-fp16',
    name: 'wan2.1_vace_14B_fp16.safetensors',
    displayName: 'models.wan2-1-vace-14b-fp16.displayName' as TranslationKey,
    description: 'models.wan2-1-vace-14b-fp16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_vace_14B_fp16.safetensors',
    ogImage: '/images/models/wan2-1-vace-14b-fp16-og.png',
    thumbnail: '/images/models/wan2-1-vace-14b-fp16-thumb.webp',
    featured: true,
    workflowCount: 6,
    tags: ['diffusion_models', 'wan2', 'vace', '14b', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan21-causvid-14b-t2v-lora-rank32',
    name: 'Wan21_CausVid_14B_T2V_lora_rank32.safetensors',
    displayName: 'models.wan21-causvid-14b-t2v-lora-rank32.displayName' as TranslationKey,
    description: 'models.wan21-causvid-14b-t2v-lora-rank32.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan21_CausVid_14B_T2V_lora_rank32.safetensors',
    ogImage: '/images/models/wan21-causvid-14b-t2v-lora-rank32-og.png',
    thumbnail: '/images/models/wan21-causvid-14b-t2v-lora-rank32-thumb.webp',
    featured: true,
    workflowCount: 6,
    tags: ['loras', 'wan21', 'causvid', '14b', 't2v', 'lora', 'rank32'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-edit-2509-lightning-4steps-v1-0-bf16',
    name: 'Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors',
    displayName: 'models.qwen-image-edit-2509-lightning-4steps-v1-0-bf16.displayName' as TranslationKey,
    description: 'models.qwen-image-edit-2509-lightning-4steps-v1-0-bf16.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors',
    ogImage: '/images/models/qwen-image-edit-2509-lightning-4steps-v1-0-bf16-og.png',
    thumbnail: '/images/models/qwen-image-edit-2509-lightning-4steps-v1-0-bf16-thumb.webp',
    featured: true,
    workflowCount: 6,
    tags: ['loras', 'qwen', 'image', 'edit', 'lightning', '4steps', 'v1', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'vae-ft-mse-840000-ema-pruned',
    name: 'vae-ft-mse-840000-ema-pruned.safetensors',
    displayName: 'models.vae-ft-mse-840000-ema-pruned.displayName' as TranslationKey,
    description: 'models.vae-ft-mse-840000-ema-pruned.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors',
    ogImage: '/images/models/vae-ft-mse-840000-ema-pruned-og.png',
    thumbnail: '/images/models/vae-ft-mse-840000-ema-pruned-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['vae', 'ft', 'mse', 'ema', 'pruned'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'lotus-depth-d-v1-1',
    name: 'lotus-depth-d-v1-1.safetensors',
    displayName: 'models.lotus-depth-d-v1-1.displayName' as TranslationKey,
    description: 'models.lotus-depth-d-v1-1.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/lotus/resolve/main/lotus-depth-d-v1-1.safetensors',
    ogImage: '/images/models/lotus-depth-d-v1-1-og.png',
    thumbnail: '/images/models/lotus-depth-d-v1-1-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['diffusion_models', 'lotus', 'depth', 'v1'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ltx-2-19b-dev-fp8',
    name: 'ltx-2-19b-dev-fp8.safetensors',
    displayName: 'models.ltx-2-19b-dev-fp8.displayName' as TranslationKey,
    description: 'models.ltx-2-19b-dev-fp8.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/Lightricks/LTX-2/resolve/main/ltx-2-19b-dev-fp8.safetensors',
    ogImage: '/images/models/ltx-2-19b-dev-fp8-og.png',
    thumbnail: '/images/models/ltx-2-19b-dev-fp8-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['checkpoints', 'ltx', '19b', 'dev', 'fp8'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ltx-2-19b-distilled-lora-384',
    name: 'ltx-2-19b-distilled-lora-384.safetensors',
    displayName: 'models.ltx-2-19b-distilled-lora-384.displayName' as TranslationKey,
    description: 'models.ltx-2-19b-distilled-lora-384.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Lightricks/LTX-2/resolve/main/ltx-2-19b-distilled-lora-384.safetensors',
    ogImage: '/images/models/ltx-2-19b-distilled-lora-384-og.png',
    thumbnail: '/images/models/ltx-2-19b-distilled-lora-384-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['loras', 'ltx', '19b', 'distilled', 'lora'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-fp8-e4m3fn',
    name: 'qwen_image_fp8_e4m3fn.safetensors',
    displayName: 'models.qwen-image-fp8-e4m3fn.displayName' as TranslationKey,
    description: 'models.qwen-image-fp8-e4m3fn.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_fp8_e4m3fn.safetensors',
    ogImage: '/images/models/qwen-image-fp8-e4m3fn-og.png',
    thumbnail: '/images/models/qwen-image-fp8-e4m3fn-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['diffusion_models', 'qwen', 'image', 'fp8', 'e4m3fn'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-lightning-4steps-v1-0',
    name: 'Qwen-Image-Lightning-4steps-V1.0.safetensors',
    displayName: 'models.qwen-image-lightning-4steps-v1-0.displayName' as TranslationKey,
    description: 'models.qwen-image-lightning-4steps-v1-0.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Lightning-4steps-V1.0.safetensors',
    ogImage: '/images/models/qwen-image-lightning-4steps-v1-0-og.png',
    thumbnail: '/images/models/qwen-image-lightning-4steps-v1-0-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['loras', 'qwen', 'image', 'lightning', '4steps', 'v1'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ltx-2-19b-distilled',
    name: 'ltx-2-19b-distilled.safetensors',
    displayName: 'models.ltx-2-19b-distilled.displayName' as TranslationKey,
    description: 'models.ltx-2-19b-distilled.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/Lightricks/LTX-2/resolve/main/ltx-2-19b-distilled.safetensors',
    ogImage: '/images/models/ltx-2-19b-distilled-og.png',
    thumbnail: '/images/models/ltx-2-19b-distilled-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['checkpoints', 'ltx', '19b', 'distilled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'clip-l-hidream',
    name: 'clip_l_hidream.safetensors',
    displayName: 'models.clip-l-hidream.displayName' as TranslationKey,
    description: 'models.clip-l-hidream.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/text_encoders/clip_l_hidream.safetensors',
    ogImage: '/images/models/clip-l-hidream-og.png',
    thumbnail: '/images/models/clip-l-hidream-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['text_encoders', 'clip', 'hidream'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'clip-g-hidream',
    name: 'clip_g_hidream.safetensors',
    displayName: 'models.clip-g-hidream.displayName' as TranslationKey,
    description: 'models.clip-g-hidream.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/text_encoders/clip_g_hidream.safetensors',
    ogImage: '/images/models/clip-g-hidream-og.png',
    thumbnail: '/images/models/clip-g-hidream-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['text_encoders', 'clip', 'hidream'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'llama-3-1-8b-instruct-fp8-scaled',
    name: 'llama_3.1_8b_instruct_fp8_scaled.safetensors',
    displayName: 'models.llama-3-1-8b-instruct-fp8-scaled.displayName' as TranslationKey,
    description: 'models.llama-3-1-8b-instruct-fp8-scaled.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/text_encoders/llama_3.1_8b_instruct_fp8_scaled.safetensors',
    ogImage: '/images/models/llama-3-1-8b-instruct-fp8-scaled-og.png',
    thumbnail: '/images/models/llama-3-1-8b-instruct-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['text_encoders', 'llama', '8b', 'instruct', 'fp8', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'lightx2v-i2v-14b-480p-cfg-step-distill-rank64-bf16',
    name: 'lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
    displayName: 'models.lightx2v-i2v-14b-480p-cfg-step-distill-rank64-bf16.displayName' as TranslationKey,
    description: 'models.lightx2v-i2v-14b-480p-cfg-step-distill-rank64-bf16.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
    ogImage: '/images/models/lightx2v-i2v-14b-480p-cfg-step-distill-rank64-bf16-og.png',
    thumbnail: '/images/models/lightx2v-i2v-14b-480p-cfg-step-distill-rank64-bf16-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['loras', 'lightx2v', 'i2v', '14b', '480p', 'cfg', 'step', 'distill'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-i2v-high-noise-14b-fp8-scaled',
    name: 'wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors',
    displayName: 'models.wan2-2-i2v-high-noise-14b-fp8-scaled.displayName' as TranslationKey,
    description: 'models.wan2-2-i2v-high-noise-14b-fp8-scaled.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors',
    ogImage: '/images/models/wan2-2-i2v-high-noise-14b-fp8-scaled-og.png',
    thumbnail: '/images/models/wan2-2-i2v-high-noise-14b-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['diffusion_models', 'wan2', 'i2v', 'high', 'noise', '14b', 'fp8', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-i2v-low-noise-14b-fp8-scaled',
    name: 'wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors',
    displayName: 'models.wan2-2-i2v-low-noise-14b-fp8-scaled.displayName' as TranslationKey,
    description: 'models.wan2-2-i2v-low-noise-14b-fp8-scaled.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors',
    ogImage: '/images/models/wan2-2-i2v-low-noise-14b-fp8-scaled-og.png',
    thumbnail: '/images/models/wan2-2-i2v-low-noise-14b-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 5,
    tags: ['diffusion_models', 'wan2', 'i2v', 'low', 'noise', '14b', 'fp8', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ltx-2-19b-lora-camera-control-dolly-left',
    name: 'ltx-2-19b-lora-camera-control-dolly-left.safetensors',
    displayName: 'models.ltx-2-19b-lora-camera-control-dolly-left.displayName' as TranslationKey,
    description: 'models.ltx-2-19b-lora-camera-control-dolly-left.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Lightricks/LTX-2-19b-LoRA-Camera-Control-Dolly-Left/resolve/main/ltx-2-19b-lora-camera-control-dolly-left.safetensors',
    ogImage: '/images/models/ltx-2-19b-lora-camera-control-dolly-left-og.png',
    thumbnail: '/images/models/ltx-2-19b-lora-camera-control-dolly-left-thumb.webp',
    featured: true,
    workflowCount: 4,
    tags: ['loras', 'ltx', '19b', 'lora', 'camera', 'control', 'dolly', 'left'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ace-step-v1-3-5b',
    name: 'ace_step_v1_3.5b.safetensors',
    displayName: 'models.ace-step-v1-3-5b.displayName' as TranslationKey,
    description: 'models.ace-step-v1-3-5b.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/ACE-Step_ComfyUI_repackaged/resolve/main/all_in_one/ace_step_v1_3.5b.safetensors?download=true',
    ogImage: '/images/models/ace-step-v1-3-5b-og.png',
    thumbnail: '/images/models/ace-step-v1-3-5b-thumb.webp',
    featured: true,
    workflowCount: 4,
    tags: ['checkpoints', 'ace', 'step', 'v1', '5b'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'z-image-turbo-bf16',
    name: 'z_image_turbo_bf16.safetensors',
    displayName: 'models.z-image-turbo-bf16.displayName' as TranslationKey,
    description: 'models.z-image-turbo-bf16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/z_image_turbo/resolve/main/split_files/diffusion_models/z_image_turbo_bf16.safetensors',
    ogImage: '/images/models/z-image-turbo-bf16-og.png',
    thumbnail: '/images/models/z-image-turbo-bf16-thumb.webp',
    featured: true,
    workflowCount: 4,
    tags: ['diffusion_models', 'image', 'turbo', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'sd-xl-base-1-0',
    name: 'sd_xl_base_1.0.safetensors',
    displayName: 'models.sd-xl-base-1-0.displayName' as TranslationKey,
    description: 'models.sd-xl-base-1-0.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors?download=true',
    ogImage: '/images/models/sd-xl-base-1-0-og.png',
    thumbnail: '/images/models/sd-xl-base-1-0-thumb.webp',
    featured: true,
    workflowCount: 4,
    tags: ['checkpoints', 'sd', 'xl', 'base'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'sd3-5-large-fp8-scaled',
    name: 'sd3.5_large_fp8_scaled.safetensors',
    displayName: 'models.sd3-5-large-fp8-scaled.displayName' as TranslationKey,
    description: 'models.sd3-5-large-fp8-scaled.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/stable-diffusion-3.5-fp8/resolve/main/sd3.5_large_fp8_scaled.safetensors?download=true',
    ogImage: '/images/models/sd3-5-large-fp8-scaled-og.png',
    thumbnail: '/images/models/sd3-5-large-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 4,
    tags: ['checkpoints', 'sd3', 'large', 'fp8', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-vae',
    name: 'wan2.2_vae.safetensors',
    displayName: 'models.wan2-2-vae.displayName' as TranslationKey,
    description: 'models.wan2-2-vae.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan2.2_vae.safetensors',
    ogImage: '/images/models/wan2-2-vae-og.png',
    thumbnail: '/images/models/wan2-2-vae-thumb.webp',
    featured: true,
    workflowCount: 3,
    tags: ['vae', 'wan2'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux1-dev',
    name: 'flux1-dev.safetensors',
    displayName: 'models.flux1-dev.displayName' as TranslationKey,
    description: 'models.flux1-dev.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux1-dev/resolve/main/flux1-dev.safetensors',
    ogImage: '/images/models/flux1-dev-og.png',
    thumbnail: '/images/models/flux1-dev-thumb.webp',
    featured: true,
    workflowCount: 3,
    tags: ['diffusion_models', 'flux1', 'dev'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'hunyuan-video-vae-bf16',
    name: 'hunyuan_video_vae_bf16.safetensors',
    displayName: 'models.hunyuan-video-vae-bf16.displayName' as TranslationKey,
    description: 'models.hunyuan-video-vae-bf16.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Kijai/HunyuanVideo_comfy/resolve/main/hunyuan_video_vae_bf16.safetensors',
    ogImage: '/images/models/hunyuan-video-vae-bf16-og.png',
    thumbnail: '/images/models/hunyuan-video-vae-bf16-thumb.webp',
    featured: true,
    workflowCount: 3,
    tags: ['vae', 'hunyuan', 'video', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'sigclip-vision-patch14-384',
    name: 'sigclip_vision_patch14_384.safetensors',
    displayName: 'models.sigclip-vision-patch14-384.displayName' as TranslationKey,
    description: 'models.sigclip-vision-patch14-384.description' as TranslationKey,
    directory: 'clip_vision',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/sigclip_vision_384/resolve/main/sigclip_vision_patch14_384.safetensors',
    ogImage: '/images/models/sigclip-vision-patch14-384-og.png',
    thumbnail: '/images/models/sigclip-vision-patch14-384-thumb.webp',
    featured: true,
    workflowCount: 3,
    tags: ['clip_vision', 'sigclip', 'vision', 'patch14'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-edit-2511-bf16',
    name: 'qwen_image_edit_2511_bf16.safetensors',
    displayName: 'models.qwen-image-edit-2511-bf16.displayName' as TranslationKey,
    description: 'models.qwen-image-edit-2511-bf16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_2511_bf16.safetensors',
    ogImage: '/images/models/qwen-image-edit-2511-bf16-og.png',
    thumbnail: '/images/models/qwen-image-edit-2511-bf16-thumb.webp',
    featured: true,
    workflowCount: 3,
    tags: ['diffusion_models', 'qwen', 'image', 'edit', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux2-dev-fp8mixed',
    name: 'flux2_dev_fp8mixed.safetensors',
    displayName: 'models.flux2-dev-fp8mixed.displayName' as TranslationKey,
    description: 'models.flux2-dev-fp8mixed.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux2-dev/resolve/main/split_files/diffusion_models/flux2_dev_fp8mixed.safetensors',
    ogImage: '/images/models/flux2-dev-fp8mixed-og.png',
    thumbnail: '/images/models/flux2-dev-fp8mixed-thumb.webp',
    featured: true,
    workflowCount: 3,
    tags: ['diffusion_models', 'flux2', 'dev', 'fp8mixed'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-3-8b-fp8mixed',
    name: 'qwen_3_8b_fp8mixed.safetensors',
    displayName: 'models.qwen-3-8b-fp8mixed.displayName' as TranslationKey,
    description: 'models.qwen-3-8b-fp8mixed.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux2-klein-9B/resolve/main/split_files/text_encoders/qwen_3_8b_fp8mixed.safetensors',
    ogImage: '/images/models/qwen-3-8b-fp8mixed-og.png',
    thumbnail: '/images/models/qwen-3-8b-fp8mixed-thumb.webp',
    featured: true,
    workflowCount: 3,
    tags: ['text_encoders', 'qwen', '8b', 'fp8mixed'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux1-dev-fp8',
    name: 'flux1-dev-fp8.safetensors',
    displayName: 'models.flux1-dev-fp8.displayName' as TranslationKey,
    description: 'models.flux1-dev-fp8.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux1-dev/resolve/main/flux1-dev-fp8.safetensors',
    ogImage: '/images/models/flux1-dev-fp8-og.png',
    thumbnail: '/images/models/flux1-dev-fp8-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'flux1', 'dev', 'fp8'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'hunyuan-3d-v2-1',
    name: 'hunyuan_3d_v2.1.safetensors',
    displayName: 'models.hunyuan-3d-v2-1.displayName' as TranslationKey,
    description: 'models.hunyuan-3d-v2-1.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/hunyuan3D_2.1_repackaged/resolve/main/hunyuan_3d_v2.1.safetensors',
    ogImage: '/images/models/hunyuan-3d-v2-1-og.png',
    thumbnail: '/images/models/hunyuan-3d-v2-1-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['checkpoints', 'hunyuan', '3d', 'v2'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan21-wanmove-fp8-scaled-e4m3fn-kj',
    name: 'Wan21-WanMove_fp8_scaled_e4m3fn_KJ.safetensors',
    displayName: 'models.wan21-wanmove-fp8-scaled-e4m3fn-kj.displayName' as TranslationKey,
    description: 'models.wan21-wanmove-fp8-scaled-e4m3fn-kj.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/WanMove/Wan21-WanMove_fp8_scaled_e4m3fn_KJ.safetensors',
    ogImage: '/images/models/wan21-wanmove-fp8-scaled-e4m3fn-kj-og.png',
    thumbnail: '/images/models/wan21-wanmove-fp8-scaled-e4m3fn-kj-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'wan21', 'wanmove', 'fp8', 'scaled', 'e4m3fn', 'kj'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'sd-xl-refiner-1-0',
    name: 'sd_xl_refiner_1.0.safetensors',
    displayName: 'models.sd-xl-refiner-1-0.displayName' as TranslationKey,
    description: 'models.sd-xl-refiner-1-0.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors?download=true',
    ogImage: '/images/models/sd-xl-refiner-1-0-og.png',
    thumbnail: '/images/models/sd-xl-refiner-1-0-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['checkpoints', 'sd', 'xl', 'refiner'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-2512-fp8-e4m3fn',
    name: 'qwen_image_2512_fp8_e4m3fn.safetensors',
    displayName: 'models.qwen-image-2512-fp8-e4m3fn.displayName' as TranslationKey,
    description: 'models.qwen-image-2512-fp8-e4m3fn.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_2512_fp8_e4m3fn.safetensors',
    ogImage: '/images/models/qwen-image-2512-fp8-e4m3fn-og.png',
    thumbnail: '/images/models/qwen-image-2512-fp8-e4m3fn-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'qwen', 'image', 'fp8', 'e4m3fn'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-edit-2509-multiple-angles',
    name: 'Qwen-Edit-2509-Multiple-angles.safetensors',
    displayName: 'models.qwen-edit-2509-multiple-angles.displayName' as TranslationKey,
    description: 'models.qwen-edit-2509-multiple-angles.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/loras/Qwen-Edit-2509-Multiple-angles.safetensors',
    ogImage: '/images/models/qwen-edit-2509-multiple-angles-og.png',
    thumbnail: '/images/models/qwen-edit-2509-multiple-angles-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['loras', 'qwen', 'edit', 'multiple', 'angles'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'mistral-3-small-flux2-bf16',
    name: 'mistral_3_small_flux2_bf16.safetensors',
    displayName: 'models.mistral-3-small-flux2-bf16.displayName' as TranslationKey,
    description: 'models.mistral-3-small-flux2-bf16.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux2-dev/resolve/main/split_files/text_encoders/mistral_3_small_flux2_bf16.safetensors',
    ogImage: '/images/models/mistral-3-small-flux2-bf16-og.png',
    thumbnail: '/images/models/mistral-3-small-flux2-bf16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['text_encoders', 'mistral', 'small', 'flux2', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux-2-klein-9b-fp8',
    name: 'flux-2-klein-9b-fp8.safetensors',
    displayName: 'models.flux-2-klein-9b-fp8.displayName' as TranslationKey,
    description: 'models.flux-2-klein-9b-fp8.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/black-forest-labs/FLUX.2-klein-9b-fp8/resolve/main/flux-2-klein-9b-fp8.safetensors',
    ogImage: '/images/models/flux-2-klein-9b-fp8-og.png',
    thumbnail: '/images/models/flux-2-klein-9b-fp8-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'flux', 'klein', '9b', 'fp8'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-2-5-vl-fp16',
    name: 'qwen_2.5_vl_fp16.safetensors',
    displayName: 'models.qwen-2-5-vl-fp16.displayName' as TranslationKey,
    description: 'models.qwen-2-5-vl-fp16.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Omnigen2_ComfyUI_repackaged/resolve/main/split_files/text_encoders/qwen_2.5_vl_fp16.safetensors',
    ogImage: '/images/models/qwen-2-5-vl-fp16-og.png',
    thumbnail: '/images/models/qwen-2-5-vl-fp16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['text_encoders', 'qwen', 'vl', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'omnigen2-fp16',
    name: 'omnigen2_fp16.safetensors',
    displayName: 'models.omnigen2-fp16.displayName' as TranslationKey,
    description: 'models.omnigen2-fp16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Omnigen2_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/omnigen2_fp16.safetensors',
    ogImage: '/images/models/omnigen2-fp16-og.png',
    thumbnail: '/images/models/omnigen2-fp16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'omnigen2', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-layered-vae',
    name: 'qwen_image_layered_vae.safetensors',
    displayName: 'models.qwen-image-layered-vae.displayName' as TranslationKey,
    description: 'models.qwen-image-layered-vae.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image-Layered_ComfyUI/resolve/main/split_files/vae/qwen_image_layered_vae.safetensors',
    ogImage: '/images/models/qwen-image-layered-vae-og.png',
    thumbnail: '/images/models/qwen-image-layered-vae-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['vae', 'qwen', 'image', 'layered'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux-2-klein-base-9b-fp8',
    name: 'flux-2-klein-base-9b-fp8.safetensors',
    displayName: 'models.flux-2-klein-base-9b-fp8.displayName' as TranslationKey,
    description: 'models.flux-2-klein-base-9b-fp8.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/black-forest-labs/FLUX.2-klein-base-9b-fp8/resolve/main/flux-2-klein-base-9b-fp8.safetensors',
    ogImage: '/images/models/flux-2-klein-base-9b-fp8-og.png',
    thumbnail: '/images/models/flux-2-klein-base-9b-fp8-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'flux', 'klein', 'base', '9b', 'fp8'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-edit-2509-lightning-8steps-v1-0-bf16',
    name: 'Qwen-Image-Edit-2509-Lightning-8steps-V1.0-bf16.safetensors',
    displayName: 'models.qwen-image-edit-2509-lightning-8steps-v1-0-bf16.displayName' as TranslationKey,
    description: 'models.qwen-image-edit-2509-lightning-8steps-v1-0-bf16.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-8steps-V1.0-bf16.safetensors',
    ogImage: '/images/models/qwen-image-edit-2509-lightning-8steps-v1-0-bf16-og.png',
    thumbnail: '/images/models/qwen-image-edit-2509-lightning-8steps-v1-0-bf16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['loras', 'qwen', 'image', 'edit', 'lightning', '8steps', 'v1', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-edit-2511-lightning-4steps-v1-0-bf16',
    name: 'Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors',
    displayName: 'models.qwen-image-edit-2511-lightning-4steps-v1-0-bf16.displayName' as TranslationKey,
    description: 'models.qwen-image-edit-2511-lightning-4steps-v1-0-bf16.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/lightx2v/Qwen-Image-Edit-2511-Lightning/resolve/main/Qwen-Image-Edit-2511-Lightning-4steps-V1.0-bf16.safetensors',
    ogImage: '/images/models/qwen-image-edit-2511-lightning-4steps-v1-0-bf16-og.png',
    thumbnail: '/images/models/qwen-image-edit-2511-lightning-4steps-v1-0-bf16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['loras', 'qwen', 'image', 'edit', 'lightning', '4steps', 'v1', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-1-vae-bf16',
    name: 'Wan2_1_VAE_bf16.safetensors',
    displayName: 'models.wan2-1-vae-bf16.displayName' as TranslationKey,
    description: 'models.wan2-1-vae-bf16.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan2_1_VAE_bf16.safetensors',
    ogImage: '/images/models/wan2-1-vae-bf16-og.png',
    thumbnail: '/images/models/wan2-1-vae-bf16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['vae', 'wan2', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-1-i2v-ati-14b-fp8-e4m3fn',
    name: 'Wan2_1-I2V-ATI-14B_fp8_e4m3fn.safetensors',
    displayName: 'models.wan2-1-i2v-ati-14b-fp8-e4m3fn.displayName' as TranslationKey,
    description: 'models.wan2-1-i2v-ati-14b-fp8-e4m3fn.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan2_1-I2V-ATI-14B_fp8_e4m3fn.safetensors',
    ogImage: '/images/models/wan2-1-i2v-ati-14b-fp8-e4m3fn-og.png',
    thumbnail: '/images/models/wan2-1-i2v-ati-14b-fp8-e4m3fn-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'wan2', 'i2v', 'ati', '14b', 'fp8', 'e4m3fn'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'byt5-small-glyphxl-fp16',
    name: 'byt5_small_glyphxl_fp16.safetensors',
    displayName: 'models.byt5-small-glyphxl-fp16.displayName' as TranslationKey,
    description: 'models.byt5-small-glyphxl-fp16.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HunyuanVideo_1.5_repackaged/resolve/main/split_files/text_encoders/byt5_small_glyphxl_fp16.safetensors',
    ogImage: '/images/models/byt5-small-glyphxl-fp16-og.png',
    thumbnail: '/images/models/byt5-small-glyphxl-fp16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['text_encoders', 'byt5', 'small', 'glyphxl', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'hunyuanvideo1-5-1080p-sr-distilled-fp16',
    name: 'hunyuanvideo1.5_1080p_sr_distilled_fp16.safetensors',
    displayName: 'models.hunyuanvideo1-5-1080p-sr-distilled-fp16.displayName' as TranslationKey,
    description: 'models.hunyuanvideo1-5-1080p-sr-distilled-fp16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HunyuanVideo_1.5_repackaged/resolve/main/split_files/diffusion_models/hunyuanvideo1.5_1080p_sr_distilled_fp16.safetensors',
    ogImage: '/images/models/hunyuanvideo1-5-1080p-sr-distilled-fp16-og.png',
    thumbnail: '/images/models/hunyuanvideo1-5-1080p-sr-distilled-fp16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'hunyuanvideo1', '1080p', 'sr', 'distilled', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'hunyuanvideo15-vae-fp16',
    name: 'hunyuanvideo15_vae_fp16.safetensors',
    displayName: 'models.hunyuanvideo15-vae-fp16.displayName' as TranslationKey,
    description: 'models.hunyuanvideo15-vae-fp16.description' as TranslationKey,
    directory: 'vae',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HunyuanVideo_1.5_repackaged/resolve/main/split_files/vae/hunyuanvideo15_vae_fp16.safetensors',
    ogImage: '/images/models/hunyuanvideo15-vae-fp16-og.png',
    thumbnail: '/images/models/hunyuanvideo15-vae-fp16-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['vae', 'hunyuanvideo15', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'hunyuanvideo15-latent-upsampler-1080p',
    name: 'hunyuanvideo15_latent_upsampler_1080p.safetensors',
    displayName: 'models.hunyuanvideo15-latent-upsampler-1080p.displayName' as TranslationKey,
    description: 'models.hunyuanvideo15-latent-upsampler-1080p.description' as TranslationKey,
    directory: 'latent_upscale_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HunyuanVideo_1.5_repackaged/resolve/main/split_files/latent_upscale_models/hunyuanvideo15_latent_upsampler_1080p.safetensors',
    ogImage: '/images/models/hunyuanvideo15-latent-upsampler-1080p-og.png',
    thumbnail: '/images/models/hunyuanvideo15-latent-upsampler-1080p-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['latent_upscale_models', 'hunyuanvideo15', 'latent', 'upsampler', '1080p'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-t2v-lightx2v-4steps-lora-v1-1-high-noise',
    name: 'wan2.2_t2v_lightx2v_4steps_lora_v1.1_high_noise.safetensors',
    displayName: 'models.wan2-2-t2v-lightx2v-4steps-lora-v1-1-high-noise.displayName' as TranslationKey,
    description: 'models.wan2-2-t2v-lightx2v-4steps-lora-v1-1-high-noise.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/loras/wan2.2_t2v_lightx2v_4steps_lora_v1.1_high_noise.safetensors',
    ogImage: '/images/models/wan2-2-t2v-lightx2v-4steps-lora-v1-1-high-noise-og.png',
    thumbnail: '/images/models/wan2-2-t2v-lightx2v-4steps-lora-v1-1-high-noise-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['loras', 'wan2', 't2v', 'lightx2v', '4steps', 'lora', 'v1', 'high'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux1-fill-dev',
    name: 'flux1-fill-dev.safetensors',
    displayName: 'models.flux1-fill-dev.displayName' as TranslationKey,
    description: 'models.flux1-fill-dev.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux1-dev/resolve/main/split_files/diffusion_models/flux1-fill-dev.safetensors',
    ogImage: '/images/models/flux1-fill-dev-og.png',
    thumbnail: '/images/models/flux1-fill-dev-thumb.webp',
    featured: true,
    workflowCount: 2,
    tags: ['diffusion_models', 'flux1', 'fill', 'dev'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-edit-fp8-e4m3fn',
    name: 'qwen_image_edit_fp8_e4m3fn.safetensors',
    displayName: 'models.qwen-image-edit-fp8-e4m3fn.displayName' as TranslationKey,
    description: 'models.qwen-image-edit-fp8-e4m3fn.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_fp8_e4m3fn.safetensors',
    ogImage: '/images/models/qwen-image-edit-fp8-e4m3fn-og.png',
    thumbnail: '/images/models/qwen-image-edit-fp8-e4m3fn-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'qwen', 'image', 'edit', 'fp8', 'e4m3fn'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-edit-lightning-4steps-v1-0-bf16',
    name: 'Qwen-Image-Edit-Lightning-4steps-V1.0-bf16.safetensors',
    displayName: 'models.qwen-image-edit-lightning-4steps-v1-0-bf16.displayName' as TranslationKey,
    description: 'models.qwen-image-edit-lightning-4steps-v1-0-bf16.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Edit-Lightning-4steps-V1.0-bf16.safetensors',
    ogImage: '/images/models/qwen-image-edit-lightning-4steps-v1-0-bf16-og.png',
    thumbnail: '/images/models/qwen-image-edit-lightning-4steps-v1-0-bf16-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['loras', 'qwen', 'image', 'edit', 'lightning', '4steps', 'v1', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'chroma-radiance-x0',
    name: 'chroma-radiance-x0.safetensors',
    displayName: 'models.chroma-radiance-x0.displayName' as TranslationKey,
    description: 'models.chroma-radiance-x0.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Chroma1-Radiance_Repackaged/resolve/main/split_files/diffusion_models/chroma-radiance-x0.safetensors',
    ogImage: '/images/models/chroma-radiance-x0-og.png',
    thumbnail: '/images/models/chroma-radiance-x0-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'chroma', 'radiance', 'x0'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux1-depth-dev-lora',
    name: 'flux1-depth-dev-lora.safetensors',
    displayName: 'models.flux1-depth-dev-lora.displayName' as TranslationKey,
    description: 'models.flux1-depth-dev-lora.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux1-dev/resolve/main/split_files/loras/flux1-depth-dev-lora.safetensors',
    ogImage: '/images/models/flux1-depth-dev-lora-og.png',
    thumbnail: '/images/models/flux1-depth-dev-lora-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['loras', 'flux1', 'depth', 'dev', 'lora'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-fun-control-5b-bf16',
    name: 'wan2.2_fun_control_5B_bf16.safetensors',
    displayName: 'models.wan2-2-fun-control-5b-bf16.displayName' as TranslationKey,
    description: 'models.wan2-2-fun-control-5b-bf16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_fun_control_5B_bf16.safetensors',
    ogImage: '/images/models/wan2-2-fun-control-5b-bf16-og.png',
    thumbnail: '/images/models/wan2-2-fun-control-5b-bf16-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'wan2', 'fun', 'control', '5b', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-canny-diffsynth-controlnet',
    name: 'qwen_image_canny_diffsynth_controlnet.safetensors',
    displayName: 'models.qwen-image-canny-diffsynth-controlnet.displayName' as TranslationKey,
    description: 'models.qwen-image-canny-diffsynth-controlnet.description' as TranslationKey,
    directory: 'model_patches',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image-DiffSynth-ControlNets/resolve/main/split_files/model_patches/qwen_image_canny_diffsynth_controlnet.safetensors',
    ogImage: '/images/models/qwen-image-canny-diffsynth-controlnet-og.png',
    thumbnail: '/images/models/qwen-image-canny-diffsynth-controlnet-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['model_patches', 'qwen', 'image', 'canny', 'diffsynth', 'controlnet'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-fun-inpaint-high-noise-14b-fp8-scaled',
    name: 'wan2.2_fun_inpaint_high_noise_14B_fp8_scaled.safetensors',
    displayName: 'models.wan2-2-fun-inpaint-high-noise-14b-fp8-scaled.displayName' as TranslationKey,
    description: 'models.wan2-2-fun-inpaint-high-noise-14b-fp8-scaled.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_fun_inpaint_high_noise_14B_fp8_scaled.safetensors',
    ogImage: '/images/models/wan2-2-fun-inpaint-high-noise-14b-fp8-scaled-og.png',
    thumbnail: '/images/models/wan2-2-fun-inpaint-high-noise-14b-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'wan2', 'fun', 'inpaint', 'high', 'noise', '14b', 'fp8'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-fun-inpaint-low-noise-14b-fp8-scaled',
    name: 'wan2.2_fun_inpaint_low_noise_14B_fp8_scaled.safetensors',
    displayName: 'models.wan2-2-fun-inpaint-low-noise-14b-fp8-scaled.displayName' as TranslationKey,
    description: 'models.wan2-2-fun-inpaint-low-noise-14b-fp8-scaled.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_fun_inpaint_low_noise_14B_fp8_scaled.safetensors',
    ogImage: '/images/models/wan2-2-fun-inpaint-low-noise-14b-fp8-scaled-og.png',
    thumbnail: '/images/models/wan2-2-fun-inpaint-low-noise-14b-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'wan2', 'fun', 'inpaint', 'low', 'noise', '14b', 'fp8'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'netayumev35-pretrained-all-in-one',
    name: 'NetaYumev35_pretrained_all_in_one.safetensors',
    displayName: 'models.netayumev35-pretrained-all-in-one.displayName' as TranslationKey,
    description: 'models.netayumev35-pretrained-all-in-one.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/duongve/NetaYume-Lumina-Image-2.0/resolve/main/NetaYumev35_pretrained_all_in_one.safetensors',
    ogImage: '/images/models/netayumev35-pretrained-all-in-one-og.png',
    thumbnail: '/images/models/netayumev35-pretrained-all-in-one-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['checkpoints', 'netayumev35', 'pretrained', 'all', 'in', 'one'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ltx-2-19b-ic-lora-depth-control',
    name: 'ltx-2-19b-ic-lora-depth-control.safetensors',
    displayName: 'models.ltx-2-19b-ic-lora-depth-control.displayName' as TranslationKey,
    description: 'models.ltx-2-19b-ic-lora-depth-control.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Lightricks/LTX-2-19b-IC-LoRA-Depth-Control/resolve/main/ltx-2-19b-ic-lora-depth-control.safetensors',
    ogImage: '/images/models/ltx-2-19b-ic-lora-depth-control-og.png',
    thumbnail: '/images/models/ltx-2-19b-ic-lora-depth-control-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['loras', 'ltx', '19b', 'ic', 'lora', 'depth', 'control'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'hidream-i1-dev-fp8',
    name: 'hidream_i1_dev_fp8.safetensors',
    displayName: 'models.hidream-i1-dev-fp8.displayName' as TranslationKey,
    description: 'models.hidream-i1-dev-fp8.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI/resolve/main/split_files/diffusion_models/hidream_i1_dev_fp8.safetensors',
    ogImage: '/images/models/hidream-i1-dev-fp8-og.png',
    thumbnail: '/images/models/hidream-i1-dev-fp8-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'hidream', 'i1', 'dev', 'fp8'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'humo-17b-fp8-e4m3fn',
    name: 'humo_17B_fp8_e4m3fn.safetensors',
    displayName: 'models.humo-17b-fp8-e4m3fn.displayName' as TranslationKey,
    description: 'models.humo-17b-fp8-e4m3fn.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HuMo_ComfyUI/resolve/main/split_files/diffusion_models/humo_17B_fp8_e4m3fn.safetensors',
    ogImage: '/images/models/humo-17b-fp8-e4m3fn-og.png',
    thumbnail: '/images/models/humo-17b-fp8-e4m3fn-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'humo', '17b', 'fp8', 'e4m3fn'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'whisper-large-v3-fp16',
    name: 'whisper_large_v3_fp16.safetensors',
    displayName: 'models.whisper-large-v3-fp16.displayName' as TranslationKey,
    description: 'models.whisper-large-v3-fp16.description' as TranslationKey,
    directory: 'audio_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/HuMo_ComfyUI/resolve/main/split_files/audio_encoders/whisper_large_v3_fp16.safetensors',
    ogImage: '/images/models/whisper-large-v3-fp16-og.png',
    thumbnail: '/images/models/whisper-large-v3-fp16-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['audio_encoders', 'whisper', 'large', 'v3', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ltx-video-2b-v0-9-5',
    name: 'ltx-video-2b-v0.9.5.safetensors',
    displayName: 'models.ltx-video-2b-v0-9-5.displayName' as TranslationKey,
    description: 'models.ltx-video-2b-v0-9-5.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/Lightricks/LTX-Video/resolve/main/ltx-video-2b-v0.9.5.safetensors',
    ogImage: '/images/models/ltx-video-2b-v0-9-5-og.png',
    thumbnail: '/images/models/ltx-video-2b-v0-9-5-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['checkpoints', 'ltx', 'video', '2b', 'v0'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'z-image-turbo-fun-controlnet-union',
    name: 'Z-Image-Turbo-Fun-Controlnet-Union.safetensors',
    displayName: 'models.z-image-turbo-fun-controlnet-union.displayName' as TranslationKey,
    description: 'models.z-image-turbo-fun-controlnet-union.description' as TranslationKey,
    directory: 'model_patches',
    huggingFaceUrl: 'https://huggingface.co/alibaba-pai/Z-Image-Turbo-Fun-Controlnet-Union/resolve/main/Z-Image-Turbo-Fun-Controlnet-Union.safetensors',
    ogImage: '/images/models/z-image-turbo-fun-controlnet-union-og.png',
    thumbnail: '/images/models/z-image-turbo-fun-controlnet-union-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['model_patches', 'image', 'turbo', 'fun', 'controlnet', 'union'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'clip-vision-g',
    name: 'clip_vision_g.safetensors',
    displayName: 'models.clip-vision-g.displayName' as TranslationKey,
    description: 'models.clip-vision-g.description' as TranslationKey,
    directory: 'clip_vision',
    huggingFaceUrl: 'https://huggingface.co/comfyanonymous/clip_vision_g/resolve/main/clip_vision_g.safetensors?download=true',
    ogImage: '/images/models/clip-vision-g-og.png',
    thumbnail: '/images/models/clip-vision-g-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['clip_vision', 'clip', 'vision'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wananimate-relight-lora-fp16',
    name: 'WanAnimate_relight_lora_fp16.safetensors',
    displayName: 'models.wananimate-relight-lora-fp16.displayName' as TranslationKey,
    description: 'models.wananimate-relight-lora-fp16.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/LoRAs/Wan22_relight/WanAnimate_relight_lora_fp16.safetensors',
    ogImage: '/images/models/wananimate-relight-lora-fp16-og.png',
    thumbnail: '/images/models/wananimate-relight-lora-fp16-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['loras', 'wananimate', 'relight', 'lora', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-2-animate-14b-fp8-e4m3fn-scaled-kj',
    name: 'Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors',
    displayName: 'models.wan2-2-animate-14b-fp8-e4m3fn-scaled-kj.displayName' as TranslationKey,
    description: 'models.wan2-2-animate-14b-fp8-e4m3fn-scaled-kj.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/Wan22Animate/Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors',
    ogImage: '/images/models/wan2-2-animate-14b-fp8-e4m3fn-scaled-kj-og.png',
    thumbnail: '/images/models/wan2-2-animate-14b-fp8-e4m3fn-scaled-kj-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'wan2', 'animate', '14b', 'fp8', 'e4m3fn', 'scaled', 'kj'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-instantx-controlnet-union',
    name: 'Qwen-Image-InstantX-ControlNet-Union.safetensors',
    displayName: 'models.qwen-image-instantx-controlnet-union.displayName' as TranslationKey,
    description: 'models.qwen-image-instantx-controlnet-union.description' as TranslationKey,
    directory: 'controlnet',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Qwen-Image-InstantX-ControlNets/resolve/main/split_files/controlnet/Qwen-Image-InstantX-ControlNet-Union.safetensors',
    ogImage: '/images/models/qwen-image-instantx-controlnet-union-og.png',
    thumbnail: '/images/models/qwen-image-instantx-controlnet-union-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['controlnet', 'qwen', 'image', 'instantx', 'union'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'kandinsky5lite-t2v-sft-5s',
    name: 'kandinsky5lite_t2v_sft_5s.safetensors',
    displayName: 'models.kandinsky5lite-t2v-sft-5s.displayName' as TranslationKey,
    description: 'models.kandinsky5lite-t2v-sft-5s.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/kandinskylab/Kandinsky-5.0-T2V-Lite-sft-5s/resolve/main/model/kandinsky5lite_t2v_sft_5s.safetensors',
    ogImage: '/images/models/kandinsky5lite-t2v-sft-5s-og.png',
    thumbnail: '/images/models/kandinsky5lite-t2v-sft-5s-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'kandinsky5lite', 't2v', 'sft', '5s'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux1-krea-dev-fp8-scaled',
    name: 'flux1-krea-dev_fp8_scaled.safetensors',
    displayName: 'models.flux1-krea-dev-fp8-scaled.displayName' as TranslationKey,
    description: 'models.flux1-krea-dev-fp8-scaled.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/FLUX.1-Krea-dev_ComfyUI/resolve/main/split_files/diffusion_models/flux1-krea-dev_fp8_scaled.safetensors',
    ogImage: '/images/models/flux1-krea-dev-fp8-scaled-og.png',
    thumbnail: '/images/models/flux1-krea-dev-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'flux1', 'krea', 'dev', 'fp8', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wuli-qwen-image-2512-turbo-lora-2steps-v1-0-bf16',
    name: 'Wuli-Qwen-Image-2512-Turbo-LoRA-2steps-V1.0-bf16.safetensors',
    displayName: 'models.wuli-qwen-image-2512-turbo-lora-2steps-v1-0-bf16.displayName' as TranslationKey,
    description: 'models.wuli-qwen-image-2512-turbo-lora-2steps-v1-0-bf16.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Wuli-art/Qwen-Image-2512-Turbo-LoRA-2-Steps/resolve/main/Wuli-Qwen-Image-2512-Turbo-LoRA-2steps-V1.0-bf16.safetensors',
    ogImage: '/images/models/wuli-qwen-image-2512-turbo-lora-2steps-v1-0-bf16-og.png',
    thumbnail: '/images/models/wuli-qwen-image-2512-turbo-lora-2steps-v1-0-bf16-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['loras', 'wuli', 'qwen', 'image', 'turbo', 'lora', '2steps', 'v1'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'uso-flux1-projector-v1',
    name: 'uso-flux1-projector-v1.safetensors',
    displayName: 'models.uso-flux1-projector-v1.displayName' as TranslationKey,
    description: 'models.uso-flux1-projector-v1.description' as TranslationKey,
    directory: 'model_patches',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/USO_1.0_Repackaged/resolve/main/split_files/model_patches/uso-flux1-projector-v1.safetensors',
    ogImage: '/images/models/uso-flux1-projector-v1-og.png',
    thumbnail: '/images/models/uso-flux1-projector-v1-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['model_patches', 'uso', 'flux1', 'projector', 'v1'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'uso-flux1-dit-lora-v1',
    name: 'uso-flux1-dit-lora-v1.safetensors',
    displayName: 'models.uso-flux1-dit-lora-v1.displayName' as TranslationKey,
    description: 'models.uso-flux1-dit-lora-v1.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/USO_1.0_Repackaged/resolve/main/split_files/loras/uso-flux1-dit-lora-v1.safetensors',
    ogImage: '/images/models/uso-flux1-dit-lora-v1-og.png',
    thumbnail: '/images/models/uso-flux1-dit-lora-v1-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['loras', 'uso', 'flux1', 'dit', 'lora', 'v1'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ovis-image-bf16',
    name: 'ovis_image_bf16.safetensors',
    displayName: 'models.ovis-image-bf16.displayName' as TranslationKey,
    description: 'models.ovis-image-bf16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Ovis-Image/resolve/main/split_files/diffusion_models/ovis_image_bf16.safetensors',
    ogImage: '/images/models/ovis-image-bf16-og.png',
    thumbnail: '/images/models/ovis-image-bf16-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'ovis', 'image', 'bf16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'ovis-2-5',
    name: 'ovis_2.5.safetensors',
    displayName: 'models.ovis-2-5.displayName' as TranslationKey,
    description: 'models.ovis-2-5.description' as TranslationKey,
    directory: 'text_encoders',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Ovis-Image/resolve/main/split_files/text_encoders/ovis_2.5.safetensors',
    ogImage: '/images/models/ovis-2-5-og.png',
    thumbnail: '/images/models/ovis-2-5-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['text_encoders', 'ovis'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'flux1-dev-kontext-fp8-scaled',
    name: 'flux1-dev-kontext_fp8_scaled.safetensors',
    displayName: 'models.flux1-dev-kontext-fp8-scaled.displayName' as TranslationKey,
    description: 'models.flux1-dev-kontext-fp8-scaled.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/flux1-kontext-dev_ComfyUI/resolve/main/split_files/diffusion_models/flux1-dev-kontext_fp8_scaled.safetensors',
    ogImage: '/images/models/flux1-dev-kontext-fp8-scaled-og.png',
    thumbnail: '/images/models/flux1-dev-kontext-fp8-scaled-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'flux1', 'dev', 'kontext', 'fp8', 'scaled'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'wan2-1-flf2v-720p-14b-fp16',
    name: 'wan2.1_flf2v_720p_14B_fp16.safetensors',
    displayName: 'models.wan2-1-flf2v-720p-14b-fp16.displayName' as TranslationKey,
    description: 'models.wan2-1-flf2v-720p-14b-fp16.description' as TranslationKey,
    directory: 'diffusion_models',
    huggingFaceUrl: 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/diffusion_models/wan2.1_flf2v_720p_14B_fp16.safetensors?download=true',
    ogImage: '/images/models/wan2-1-flf2v-720p-14b-fp16-og.png',
    thumbnail: '/images/models/wan2-1-flf2v-720p-14b-fp16-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['diffusion_models', 'wan2', 'flf2v', '720p', '14b', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'sd-xl-turbo-1-0-fp16',
    name: 'sd_xl_turbo_1.0_fp16.safetensors',
    displayName: 'models.sd-xl-turbo-1-0-fp16.displayName' as TranslationKey,
    description: 'models.sd-xl-turbo-1-0-fp16.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/stabilityai/sdxl-turbo/resolve/main/sd_xl_turbo_1.0_fp16.safetensors',
    ogImage: '/images/models/sd-xl-turbo-1-0-fp16-og.png',
    thumbnail: '/images/models/sd-xl-turbo-1-0-fp16-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['checkpoints', 'sd', 'xl', 'turbo', 'fp16'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'qwen-image-edit-2511-systms-infl8',
    name: 'Qwen_Image_Edit_2511-SYSTMS_INFL8.safetensors',
    displayName: 'models.qwen-image-edit-2511-systms-infl8.displayName' as TranslationKey,
    description: 'models.qwen-image-edit-2511-systms-infl8.description' as TranslationKey,
    directory: 'loras',
    huggingFaceUrl: 'https://huggingface.co/systms/SYSTMS-INFL8-LoRA-Qwen-Image-Edit-2511/resolve/main/SYSTMS_INFL8_LoRA_Qwen_Image_Edit_2511.safetensors',
    ogImage: '/images/models/qwen-image-edit-2511-systms-infl8-og.png',
    thumbnail: '/images/models/qwen-image-edit-2511-systms-infl8-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['loras', 'qwen', 'image', 'edit', 'systms', 'infl8'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
  {
    slug: 'svd-xt',
    name: 'svd_xt.safetensors',
    displayName: 'models.svd-xt.displayName' as TranslationKey,
    description: 'models.svd-xt.description' as TranslationKey,
    directory: 'checkpoints',
    huggingFaceUrl: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt/resolve/main/svd_xt.safetensors?download=true',
    ogImage: '/images/models/svd-xt-og.png',
    thumbnail: '/images/models/svd-xt-thumb.webp',
    featured: true,
    workflowCount: 1,
    tags: ['checkpoints', 'svd', 'xt'] as const,
    publishedDate: '2026-05-04',
    modifiedDate: '2026-05-04',
  },
]

export function getModelBySlug(slug: string): Model | undefined {
  return models.find((m) => m.slug === slug)
}

export function getFeaturedModels(): readonly Model[] {
  return models.filter((m) => m.featured)
}

export function getModelsByDirectory(dir: Model['directory']): readonly Model[] {
  return models.filter((m) => m.directory === dir)
}
