// Generated by scripts/generate-model-url-map.ts. Do not edit by hand.
export const modelPageUrls: readonly { oldSlug: string; newSlug: string }[] = [
  {
    oldSlug: 'beeble--switchx-image-edit--edit-images',
    newSlug: 'beeble-switchx-image-edit'
  },
  {
    oldSlug: 'beeble--switchx-video-edit--edit-videos',
    newSlug: 'beeble-switchx-video-edit'
  },
  {
    oldSlug: 'bfl--flux-2-max--generate-images',
    newSlug: 'flux-2-max-text-to-image'
  },
  {
    oldSlug: 'bfl--flux-2-pro--generate-images',
    newSlug: 'flux-2-pro-text-to-image'
  },
  {
    oldSlug: 'bfl--flux-3-image-to-video--animate-images',
    newSlug: 'flux-3-video-image-to-video'
  },
  {
    oldSlug: 'bfl--flux-3-text-to-video--generate-videos',
    newSlug: 'flux-3-video-text-to-video'
  },
  {
    oldSlug: 'bfl--flux-erase--edit-images',
    newSlug: 'flux-tools-erase'
  },
  {
    oldSlug: 'bfl--flux-kontext-max--edit-images',
    newSlug: 'flux-1-kontext-max-image-edit'
  },
  {
    oldSlug: 'bfl--flux-kontext-pro--edit-images',
    newSlug: 'flux-1-kontext-pro-image-edit'
  },
  {
    oldSlug: 'bfl--flux-pro-1.1--generate-images',
    newSlug: 'flux-pro-1-1-text-to-image'
  },
  {
    oldSlug: 'bfl--flux-pro-1.1-ultra--generate-images',
    newSlug: 'flux-pro-1-1-ultra-text-to-image'
  },
  {
    oldSlug: 'bfl--flux-pro-expand--edit-images',
    newSlug: 'flux-pro-expand'
  },
  {
    oldSlug: 'bfl--flux-pro-fill--edit-images',
    newSlug: 'flux-pro-fill'
  },
  {
    oldSlug: 'bfl--flux-video-upscale--edit-videos',
    newSlug: 'flux-video-upscale'
  },
  {
    oldSlug: 'bfl--flux-virtual-try-on--edit-images',
    newSlug: 'flux-virtual-try-on'
  },
  {
    oldSlug: 'bria--eraser--edit-images',
    newSlug: 'bria-eraser'
  },
  {
    oldSlug: 'bria--expand-image--edit-images',
    newSlug: 'bria-expand-image'
  },
  {
    oldSlug: 'bria--fibo-image-edit--edit-images',
    newSlug: 'bria-fibo-image-edit'
  },
  {
    oldSlug: 'bria--generative-fill--edit-images',
    newSlug: 'bria-generative-fill'
  },
  {
    oldSlug: 'bria--green-screen-video--edit-videos',
    newSlug: 'bria-green-screen-video'
  },
  {
    oldSlug: 'bria--increase-resolution--edit-images',
    newSlug: 'bria-increase-resolution'
  },
  {
    oldSlug: 'bria--remove-image-background--edit-images',
    newSlug: 'bria-rmbg-2-0'
  },
  {
    oldSlug: 'bria--remove-video-background--edit-videos',
    newSlug: 'bria-remove-video-background'
  },
  {
    oldSlug: 'bria--replace-video-background--edit-videos',
    newSlug: 'bria-replace-video-background'
  },
  {
    oldSlug: 'byteplus--seed-audio-1.0--audio',
    newSlug: 'seed-audio-1-0-text-to-speech'
  },
  {
    oldSlug: 'byteplus--seed-audio-1.0-multilingual--audio',
    newSlug: 'seed-audio-1-0-multilingual-text-to-speech'
  },
  {
    oldSlug: 'byteplus--seedance-2-5-edit-video--edit-videos',
    newSlug: 'seedance-2-5-video-edit'
  },
  {
    oldSlug: 'byteplus--seedance-2-5-first-last-frame--animate-images',
    newSlug: 'seedance-2-5-first-last-frame'
  },
  {
    oldSlug: 'byteplus--seedance-2-5-reference--generate-videos',
    newSlug: 'seedance-2-5-reference-to-video'
  },
  {
    oldSlug: 'byteplus--seedance-2-5-text-to-video--generate-videos',
    newSlug: 'seedance-2-5-text-to-video'
  },
  {
    oldSlug: 'byteplus--seedance-2-fast-first-last-frame--animate-images',
    newSlug: 'seedance-2-0-fast-first-last-frame'
  },
  {
    oldSlug: 'byteplus--seedance-2-fast-reference--generate-videos',
    newSlug: 'seedance-2-0-fast-reference-to-video'
  },
  {
    oldSlug: 'byteplus--seedance-2-fast-text-to-video--generate-videos',
    newSlug: 'seedance-2-0-fast-text-to-video'
  },
  {
    oldSlug: 'byteplus--seedance-2-image-to-video--animate-images',
    newSlug: 'seedance-2-0-image-to-video'
  },
  {
    oldSlug: 'byteplus--seedance-2-mini-text-to-video--generate-videos',
    newSlug: 'seedance-2-0-mini-text-to-video'
  },
  {
    oldSlug: 'byteplus--seedance-2-reference--generate-videos',
    newSlug: 'seedance-2-0-reference-to-video'
  },
  {
    oldSlug: 'byteplus--seedance-2-text-to-video--generate-videos',
    newSlug: 'seedance-2-0-text-to-video'
  },
  {
    oldSlug: 'byteplus--seedream-4--edit-images',
    newSlug: 'seedream-4-0-image-edit'
  },
  {
    oldSlug: 'byteplus--seedream-4--generate-images',
    newSlug: 'seedream-4-0-text-to-image'
  },
  {
    oldSlug: 'byteplus--seedream-4-5--edit-images',
    newSlug: 'seedream-4-5-image-edit'
  },
  {
    oldSlug: 'byteplus--seedream-4-5--generate-images',
    newSlug: 'seedream-4-5-text-to-image'
  },
  {
    oldSlug: 'byteplus--seedream-5-lite--edit-images',
    newSlug: 'seedream-5-0-lite-image-edit'
  },
  {
    oldSlug: 'byteplus--seedream-5-lite--generate-images',
    newSlug: 'seedream-5-0-lite-text-to-image'
  },
  {
    oldSlug: 'byteplus--seedream-5-pro--edit-images',
    newSlug: 'seedream-5-0-pro-image-edit'
  },
  {
    oldSlug: 'byteplus--seedream-5-pro--generate-images',
    newSlug: 'seedream-5-0-pro-text-to-image'
  },
  {
    oldSlug: 'byteplus--seedream-5-pro-layer-separation--edit-images',
    newSlug: 'seedream-5-0-pro-layer-separation'
  },
  {
    oldSlug: 'elevenlabs--text-to-dialogue--audio',
    newSlug: 'elevenlabs-text-to-dialogue'
  },
  {
    oldSlug: 'freepik--magnific-skin-enhancer--edit-images',
    newSlug: 'magnific-skin-enhancer'
  },
  {
    oldSlug: 'gemini--omni-1.1-flash--animate-images',
    newSlug: 'gemini-omni-1-1-flash-image-to-video'
  },
  {
    oldSlug: 'gemini--omni-1.1-flash--edit-videos',
    newSlug: 'gemini-omni-1-1-flash-video-edit'
  },
  {
    oldSlug: 'gemini--omni-1.1-flash--generate-videos',
    newSlug: 'gemini-omni-1-1-flash-text-to-video'
  },
  {
    oldSlug: 'gemini--omni-flash-preview--animate-images',
    newSlug: 'gemini-omni-flash-preview-image-to-video'
  },
  {
    oldSlug: 'gemini--omni-flash-preview--edit-videos',
    newSlug: 'gemini-omni-flash-preview-video-edit'
  },
  {
    oldSlug: 'gemini--omni-flash-preview--generate-videos',
    newSlug: 'gemini-omni-flash-preview-text-to-video'
  },
  {
    oldSlug: 'heygen--starfish-tts--audio',
    newSlug: 'heygen-starfish-text-to-speech'
  },
  {
    oldSlug: 'ideogram--v3--generate-images',
    newSlug: 'ideogram-v3-text-to-image'
  },
  {
    oldSlug: 'ideogram--v4--generate-images',
    newSlug: 'ideogram-v4-text-to-image'
  },
  {
    oldSlug: 'kling--avatar--animate-images',
    newSlug: 'kling-avatar'
  },
  {
    oldSlug: 'kling--kling-3.0-turbo-text-to-video--generate-videos',
    newSlug: 'kling-3-0-turbo-text-to-video'
  },
  {
    oldSlug: 'kling--lip-sync-audio-to-video--edit-videos',
    newSlug: 'kling-lip-sync-audio-to-video'
  },
  {
    oldSlug: 'kling--lip-sync-text-to-video--edit-videos',
    newSlug: 'kling-lip-sync-text-to-video'
  },
  {
    oldSlug: 'kling--omni-pro-edit-video--edit-videos',
    newSlug: 'kling-o3-video-edit'
  },
  {
    oldSlug: 'kling--omni-pro-image-to-video--animate-images',
    newSlug: 'kling-o3-image-to-video'
  },
  {
    oldSlug: 'kling--omni-pro-text-to-video--generate-videos',
    newSlug: 'kling-o3-text-to-video'
  },
  {
    oldSlug: 'kling--omni-pro-video-to-video--edit-videos',
    newSlug: 'kling-o3-video-to-video'
  },
  {
    oldSlug: 'kling--text-to-video--generate-videos',
    newSlug: 'kling-2-5-turbo-text-to-video'
  },
  {
    oldSlug: 'kling--text-to-video-with-audio--generate-videos',
    newSlug: 'kling-2-6-pro-text-to-video-with-audio'
  },
  {
    oldSlug: 'kling--v3--generate-videos',
    newSlug: 'kling-3-0-text-to-video'
  },
  {
    oldSlug: 'krea--krea-2-large--generate-images',
    newSlug: 'krea-2-large-text-to-image'
  },
  {
    oldSlug: 'krea--krea-2-medium--generate-images',
    newSlug: 'krea-2-medium-text-to-image'
  },
  {
    oldSlug: 'krea--krea-2-medium-turbo--generate-images',
    newSlug: 'krea-2-medium-turbo-text-to-image'
  },
  {
    oldSlug: 'luma--photon-1-image-generation--generate-images',
    newSlug: 'luma-photon-1-text-to-image'
  },
  {
    oldSlug: 'luma--photon-1-image-modify--edit-images',
    newSlug: 'luma-photon-1-image-edit'
  },
  {
    oldSlug: 'luma--photon-flash-1-image-generation--generate-images',
    newSlug: 'luma-photon-flash-1-text-to-image'
  },
  {
    oldSlug: 'luma--photon-flash-1-image-modify--edit-images',
    newSlug: 'luma-photon-flash-1-image-edit'
  },
  {
    oldSlug: 'luma--ray-2-image-to-video--animate-images',
    newSlug: 'luma-ray-2-image-to-video'
  },
  {
    oldSlug: 'luma--ray-2-text-to-video--generate-videos',
    newSlug: 'luma-ray-2-text-to-video'
  },
  {
    oldSlug: 'luma--ray-flash-2-image-to-video--animate-images',
    newSlug: 'luma-ray-flash-2-image-to-video'
  },
  {
    oldSlug: 'luma--ray-flash-2-text-to-video--generate-videos',
    newSlug: 'luma-ray-flash-2-text-to-video'
  },
  {
    oldSlug: 'luma_2--uni-1-image-edit--edit-images',
    newSlug: 'luma-uni-1-image-edit'
  },
  {
    oldSlug: 'luma_2--uni-1-image-generation--generate-images',
    newSlug: 'luma-uni-1-text-to-image'
  },
  {
    oldSlug: 'luma_2--uni-1-max-image-edit--edit-images',
    newSlug: 'luma-uni-1-max-image-edit'
  },
  {
    oldSlug: 'luma_2--uni-1-max-image-generation--generate-images',
    newSlug: 'luma-uni-1-max-text-to-image'
  },
  {
    oldSlug: 'openai--gpt-image-1--edit-images',
    newSlug: 'gpt-image-1-image-edit'
  },
  {
    oldSlug: 'openai--gpt-image-1.5--edit-images',
    newSlug: 'gpt-image-1-5-image-edit'
  },
  {
    oldSlug: 'openai--gpt-image-2--generate-images',
    newSlug: 'gpt-image-2-text-to-image'
  },
  {
    oldSlug: 'openai--gpt-image-2.5-flare--generate-images',
    newSlug: 'gpt-image-2-5-flare-text-to-image'
  },
  {
    oldSlug: 'openai--gpt-image-2.5-sunburst--generate-images',
    newSlug: 'gpt-image-2-5-sunburst-text-to-image'
  },
  {
    oldSlug: 'qwen--qwen-image-3.0-image-edit--edit-images',
    newSlug: 'qwen-image-3-0-image-edit'
  },
  {
    oldSlug: 'qwen--qwen-image-3.0-pro-image-edit--edit-images',
    newSlug: 'qwen-image-3-0-pro-image-edit'
  },
  {
    oldSlug: 'qwen--qwen-image-3.0-pro-text-to-image--generate-images',
    newSlug: 'qwen-image-3-0-pro-text-to-image'
  },
  {
    oldSlug: 'qwen--qwen-image-3.0-text-to-image--generate-images',
    newSlug: 'qwen-image-3-0-text-to-image'
  },
  {
    oldSlug: 'recraft--v3-text-to-image--generate-images',
    newSlug: 'recraft-v3-text-to-image'
  },
  {
    oldSlug: 'recraft--v3-text-to-vector--generate-images',
    newSlug: 'recraft-v3-text-to-vector'
  },
  {
    oldSlug: 'recraft--v4-pro-text-to-image--generate-images',
    newSlug: 'recraft-v4-pro-text-to-image'
  },
  {
    oldSlug: 'recraft--v4-pro-text-to-vector--generate-images',
    newSlug: 'recraft-v4-pro-text-to-vector'
  },
  {
    oldSlug: 'recraft--v4-text-to-image--generate-images',
    newSlug: 'recraft-v4-text-to-image'
  },
  {
    oldSlug: 'recraft--v4-text-to-vector--generate-images',
    newSlug: 'recraft-v4-text-to-vector'
  },
  {
    oldSlug: 'recraft--v4.1-pro-text-to-image--generate-images',
    newSlug: 'recraft-v4-1-pro-text-to-image'
  },
  {
    oldSlug: 'recraft--v4.1-pro-text-to-vector--generate-images',
    newSlug: 'recraft-v4-1-pro-text-to-vector'
  },
  {
    oldSlug: 'recraft--v4.1-text-to-image--generate-images',
    newSlug: 'recraft-v4-1-text-to-image'
  },
  {
    oldSlug: 'recraft--v4.1-text-to-vector--generate-images',
    newSlug: 'recraft-v4-1-text-to-vector'
  },
  {
    oldSlug: 'recraft--v4.1-utility-pro-text-to-image--generate-images',
    newSlug: 'recraft-v4-1-utility-pro-text-to-image'
  },
  {
    oldSlug: 'recraft--v4.1-utility-pro-text-to-vector--generate-images',
    newSlug: 'recraft-v4-1-utility-pro-text-to-vector'
  },
  {
    oldSlug: 'recraft--v4.1-utility-text-to-image--generate-images',
    newSlug: 'recraft-v4-1-utility-text-to-image'
  },
  {
    oldSlug: 'recraft--v4.1-utility-text-to-vector--generate-images',
    newSlug: 'recraft-v4-1-utility-text-to-vector'
  },
  {
    oldSlug: 'runway--aleph2-video-to-video--edit-videos',
    newSlug: 'runway-aleph-2-video-to-video'
  },
  {
    oldSlug: 'runway--gen4-image--generate-images',
    newSlug: 'runway-gen-4-image-text-to-image'
  },
  {
    oldSlug: 'runway--gen4-turbo-image-to-video--animate-images',
    newSlug: 'runway-gen-4-turbo-image-to-video'
  },
  {
    oldSlug: 'vertexai--gemini-2.5-flash-image--edit-images',
    newSlug: 'nano-banana-image-edit'
  },
  {
    oldSlug: 'vertexai--gemini-2.5-flash-image--generate-images',
    newSlug: 'nano-banana-text-to-image'
  },
  {
    oldSlug: 'vertexai--gemini-3-pro-image--edit-images',
    newSlug: 'nano-banana-pro-image-edit'
  },
  {
    oldSlug: 'vertexai--gemini-3-pro-image--generate-images',
    newSlug: 'nano-banana-pro-text-to-image'
  },
  {
    oldSlug: 'vertexai--gemini-nano-banana-2--edit-images',
    newSlug: 'nano-banana-2-image-edit'
  },
  {
    oldSlug: 'vertexai--gemini-nano-banana-2--generate-images',
    newSlug: 'nano-banana-2-text-to-image'
  },
  {
    oldSlug: 'vertexai--veo-3--animate-images',
    newSlug: 'veo-3-image-to-video'
  },
  {
    oldSlug: 'vertexai--veo-3--generate-videos',
    newSlug: 'veo-3-text-to-video'
  },
  {
    oldSlug: 'vertexai--veo-3-first-last-frame--animate-images',
    newSlug: 'veo-3-first-last-frame'
  },
  {
    oldSlug: 'wan--happyhorse-reference-video--animate-images',
    newSlug: 'happyhorse-reference-to-video'
  },
  {
    oldSlug: 'wan--happyhorse-text-to-video--generate-videos',
    newSlug: 'happyhorse-text-to-video'
  },
  {
    oldSlug: 'wan--happyhorse-video-edit--edit-videos',
    newSlug: 'happyhorse-video-edit'
  },
  {
    oldSlug: 'wan--image-to-image--edit-images',
    newSlug: 'wan-2-5-image-edit'
  },
  {
    oldSlug: 'wan--image-to-video--animate-images',
    newSlug: 'wan-2-6-image-to-video'
  },
  {
    oldSlug: 'wan--image-to-video-2.7--animate-images',
    newSlug: 'wan-2-7-image-to-video'
  },
  {
    oldSlug: 'wan--image-to-video-3.0--animate-images',
    newSlug: 'wan-3-0-image-to-video'
  },
  {
    oldSlug: 'wan--image-to-video-3.0-prime--animate-images',
    newSlug: 'wan-3-0-prime-image-to-video'
  },
  {
    oldSlug: 'wan--reference-to-video-3.0--animate-images',
    newSlug: 'wan-3-0-reference-to-video'
  },
  {
    oldSlug: 'wan--reference-to-video-3.0-prime--animate-images',
    newSlug: 'wan-3-0-prime-reference-to-video'
  },
  {
    oldSlug: 'wan--reference-video--edit-videos',
    newSlug: 'wan-2-6-reference-to-video'
  },
  {
    oldSlug: 'wan--reference-video-2.7--animate-images',
    newSlug: 'wan-2-7-reference-to-video'
  },
  {
    oldSlug: 'wan--text-to-image--generate-images',
    newSlug: 'wan-2-5-text-to-image'
  },
  {
    oldSlug: 'wan--text-to-video--generate-videos',
    newSlug: 'wan-2-6-text-to-video'
  },
  {
    oldSlug: 'wan--text-to-video-2.7--generate-videos',
    newSlug: 'wan-2-7-text-to-video'
  },
  {
    oldSlug: 'wan--text-to-video-3.0--generate-videos',
    newSlug: 'wan-3-0-text-to-video'
  },
  {
    oldSlug: 'wan--text-to-video-3.0-prime--generate-videos',
    newSlug: 'wan-3-0-prime-text-to-video'
  },
  {
    oldSlug: 'wan--video-continuation-2.7--animate-images',
    newSlug: 'wan-2-7-video-continuation'
  },
  {
    oldSlug: 'wan--video-edit-2.7--edit-videos',
    newSlug: 'wan-2-7-video-edit'
  },
  {
    oldSlug: 'wavespeed--flashvsr--edit-videos',
    newSlug: 'flashvsr'
  },
  {
    oldSlug: 'wavespeed--seedvr2-image--edit-images',
    newSlug: 'seedvr2-image-upscaler'
  },
  {
    oldSlug: 'wavespeed--ultimate-image-upscaler--edit-images',
    newSlug: 'ultimate-image-upscaler'
  },
  {
    oldSlug: 'xai--grok-imagine-image--generate-images',
    newSlug: 'grok-imagine-image-text-to-image'
  },
  {
    oldSlug: 'xai--grok-imagine-image-2.0--generate-images',
    newSlug: 'grok-imagine-image-2-0-text-to-image'
  },
  {
    oldSlug: 'xai--grok-imagine-video--animate-images',
    newSlug: 'grok-imagine-video-image-to-video'
  },
  {
    oldSlug: 'xai--grok-imagine-video--generate-videos',
    newSlug: 'grok-imagine-video-text-to-video'
  },
  {
    oldSlug: 'xai--grok-imagine-video-1.5--animate-images',
    newSlug: 'grok-imagine-video-1-5-image-to-video'
  },
  {
    oldSlug: 'xai--grok-imagine-video-1.5--generate-videos',
    newSlug: 'grok-imagine-video-1-5-text-to-video'
  },
  {
    oldSlug: 'xai--grok-imagine-video-1.5-reference--animate-images',
    newSlug: 'grok-imagine-video-1-5-reference-to-video'
  },
  {
    oldSlug: 'xai--grok-imagine-video-reference--animate-images',
    newSlug: 'grok-imagine-video-reference-to-video'
  }
]

export const modelAliasUrls: readonly { alias: string; newSlug: string }[] = [
  {
    alias: 'beeble--switchx',
    newSlug: 'beeble-switchx-image-edit'
  },
  {
    alias: 'beeble--switchx-image-edit',
    newSlug: 'beeble-switchx-image-edit'
  },
  {
    alias: 'beeble--switchx-video-edit',
    newSlug: 'beeble-switchx-video-edit'
  },
  {
    alias: 'bfl--erase-v1',
    newSlug: 'flux-tools-erase'
  },
  {
    alias: 'bfl--flux-2-max',
    newSlug: 'flux-2-max-text-to-image'
  },
  {
    alias: 'bfl--flux-2-pro',
    newSlug: 'flux-2-pro-text-to-image'
  },
  {
    alias: 'bfl--flux-3-image-to-video',
    newSlug: 'flux-3-video-image-to-video'
  },
  {
    alias: 'bfl--flux-3-text-to-video',
    newSlug: 'flux-3-video-text-to-video'
  },
  {
    alias: 'bfl--flux-3-video',
    newSlug: 'flux-3-video-text-to-video'
  },
  {
    alias: 'bfl--flux-erase',
    newSlug: 'flux-tools-erase'
  },
  {
    alias: 'bfl--flux-kontext-max',
    newSlug: 'flux-1-kontext-max-image-edit'
  },
  {
    alias: 'bfl--flux-kontext-pro',
    newSlug: 'flux-1-kontext-pro-image-edit'
  },
  {
    alias: 'bfl--flux-pro-1.0-expand',
    newSlug: 'flux-pro-expand'
  },
  {
    alias: 'bfl--flux-pro-1.0-fill',
    newSlug: 'flux-pro-fill'
  },
  {
    alias: 'bfl--flux-pro-1.1',
    newSlug: 'flux-pro-1-1-text-to-image'
  },
  {
    alias: 'bfl--flux-pro-1.1-ultra',
    newSlug: 'flux-pro-1-1-ultra-text-to-image'
  },
  {
    alias: 'bfl--flux-pro-expand',
    newSlug: 'flux-pro-expand'
  },
  {
    alias: 'bfl--flux-pro-fill',
    newSlug: 'flux-pro-fill'
  },
  {
    alias: 'bfl--flux-video-upscale',
    newSlug: 'flux-video-upscale'
  },
  {
    alias: 'bfl--flux-virtual-try-on',
    newSlug: 'flux-virtual-try-on'
  },
  {
    alias: 'bfl--video-upscale-v1',
    newSlug: 'flux-video-upscale'
  },
  {
    alias: 'bfl--vto-v1',
    newSlug: 'flux-virtual-try-on'
  },
  {
    alias: 'bria--eraser',
    newSlug: 'bria-eraser'
  },
  {
    alias: 'bria--expand-image',
    newSlug: 'bria-expand-image'
  },
  {
    alias: 'bria--fibo',
    newSlug: 'bria-fibo-image-edit'
  },
  {
    alias: 'bria--fibo-image-edit',
    newSlug: 'bria-fibo-image-edit'
  },
  {
    alias: 'bria--generative-fill',
    newSlug: 'bria-generative-fill'
  },
  {
    alias: 'bria--green-screen-video',
    newSlug: 'bria-green-screen-video'
  },
  {
    alias: 'bria--image-edit-erase',
    newSlug: 'bria-eraser'
  },
  {
    alias: 'bria--image-edit-expand',
    newSlug: 'bria-expand-image'
  },
  {
    alias: 'bria--image-edit-gen-fill',
    newSlug: 'bria-generative-fill'
  },
  {
    alias: 'bria--image-edit-increase-resolution',
    newSlug: 'bria-increase-resolution'
  },
  {
    alias: 'bria--image-edit-remove-background',
    newSlug: 'bria-rmbg-2-0'
  },
  {
    alias: 'bria--increase-resolution',
    newSlug: 'bria-increase-resolution'
  },
  {
    alias: 'bria--remove-image-background',
    newSlug: 'bria-rmbg-2-0'
  },
  {
    alias: 'bria--remove-video-background',
    newSlug: 'bria-remove-video-background'
  },
  {
    alias: 'bria--replace-video-background',
    newSlug: 'bria-replace-video-background'
  },
  {
    alias: 'bria--video-edit-green-screen',
    newSlug: 'bria-green-screen-video'
  },
  {
    alias: 'bria--video-edit-remove-background',
    newSlug: 'bria-remove-video-background'
  },
  {
    alias: 'bria--video-edit-replace-background',
    newSlug: 'bria-replace-video-background'
  },
  {
    alias: 'byteplus--dreamina-seedance-2-0-260128',
    newSlug: 'seedance-2-0-text-to-video'
  },
  {
    alias: 'byteplus--dreamina-seedance-2-0-fast-260128',
    newSlug: 'seedance-2-0-fast-text-to-video'
  },
  {
    alias: 'byteplus--dreamina-seedance-2-0-mini',
    newSlug: 'seedance-2-0-mini-text-to-video'
  },
  {
    alias: 'byteplus--dreamina-seedance-2-5-260628',
    newSlug: 'seedance-2-5-text-to-video'
  },
  {
    alias: 'byteplus--seed-audio-1.0',
    newSlug: 'seed-audio-1-0-text-to-speech'
  },
  {
    alias: 'byteplus--seed-audio-1.0-multilingual',
    newSlug: 'seed-audio-1-0-multilingual-text-to-speech'
  },
  {
    alias: 'byteplus--seedance-2-5-edit-video',
    newSlug: 'seedance-2-5-video-edit'
  },
  {
    alias: 'byteplus--seedance-2-5-first-last-frame',
    newSlug: 'seedance-2-5-first-last-frame'
  },
  {
    alias: 'byteplus--seedance-2-5-reference',
    newSlug: 'seedance-2-5-reference-to-video'
  },
  {
    alias: 'byteplus--seedance-2-5-text-to-video',
    newSlug: 'seedance-2-5-text-to-video'
  },
  {
    alias: 'byteplus--seedance-2-fast-first-last-frame',
    newSlug: 'seedance-2-0-fast-first-last-frame'
  },
  {
    alias: 'byteplus--seedance-2-fast-reference',
    newSlug: 'seedance-2-0-fast-reference-to-video'
  },
  {
    alias: 'byteplus--seedance-2-fast-text-to-video',
    newSlug: 'seedance-2-0-fast-text-to-video'
  },
  {
    alias: 'byteplus--seedance-2-image-to-video',
    newSlug: 'seedance-2-0-image-to-video'
  },
  {
    alias: 'byteplus--seedance-2-mini-text-to-video',
    newSlug: 'seedance-2-0-mini-text-to-video'
  },
  {
    alias: 'byteplus--seedance-2-reference',
    newSlug: 'seedance-2-0-reference-to-video'
  },
  {
    alias: 'byteplus--seedance-2-text-to-video',
    newSlug: 'seedance-2-0-text-to-video'
  },
  {
    alias: 'byteplus--seedream-4',
    newSlug: 'seedream-4-0-text-to-image'
  },
  {
    alias: 'byteplus--seedream-4-0-250828',
    newSlug: 'seedream-4-0-text-to-image'
  },
  {
    alias: 'byteplus--seedream-4-5',
    newSlug: 'seedream-4-5-text-to-image'
  },
  {
    alias: 'byteplus--seedream-4-5-251128',
    newSlug: 'seedream-4-5-text-to-image'
  },
  {
    alias: 'byteplus--seedream-5-0-260128',
    newSlug: 'seedream-5-0-lite-text-to-image'
  },
  {
    alias: 'byteplus--seedream-5-0-pro-260628',
    newSlug: 'seedream-5-0-pro-text-to-image'
  },
  {
    alias: 'byteplus--seedream-5-lite',
    newSlug: 'seedream-5-0-lite-text-to-image'
  },
  {
    alias: 'byteplus--seedream-5-pro',
    newSlug: 'seedream-5-0-pro-text-to-image'
  },
  {
    alias: 'byteplus--seedream-5-pro-layer-separation',
    newSlug: 'seedream-5-0-pro-layer-separation'
  },
  {
    alias: 'elevenlabs--eleven_v3',
    newSlug: 'elevenlabs-text-to-dialogue'
  },
  {
    alias: 'elevenlabs--text-to-dialogue',
    newSlug: 'elevenlabs-text-to-dialogue'
  },
  {
    alias: 'freepik--ai-skin-enhancer-creative',
    newSlug: 'magnific-skin-enhancer'
  },
  {
    alias: 'freepik--magnific-skin-enhancer',
    newSlug: 'magnific-skin-enhancer'
  },
  {
    alias: 'gemini--omni-1.1-flash',
    newSlug: 'gemini-omni-1-1-flash-text-to-video'
  },
  {
    alias: 'gemini--omni-flash-preview',
    newSlug: 'gemini-omni-flash-preview-text-to-video'
  },
  {
    alias: 'gemini-interactions--gemini-omni-1.1-flash',
    newSlug: 'gemini-omni-1-1-flash-text-to-video'
  },
  {
    alias: 'gemini-interactions--gemini-omni-flash-preview',
    newSlug: 'gemini-omni-flash-preview-text-to-video'
  },
  {
    alias: 'heygen--starfish',
    newSlug: 'heygen-starfish-text-to-speech'
  },
  {
    alias: 'heygen--starfish-tts',
    newSlug: 'heygen-starfish-text-to-speech'
  },
  {
    alias: 'ideogram--ideogram-v3',
    newSlug: 'ideogram-v3-text-to-image'
  },
  {
    alias: 'ideogram--ideogram-v4',
    newSlug: 'ideogram-v4-text-to-image'
  },
  {
    alias: 'ideogram--v3',
    newSlug: 'ideogram-v3-text-to-image'
  },
  {
    alias: 'ideogram--v4',
    newSlug: 'ideogram-v4-text-to-image'
  },
  {
    alias: 'kling--avatar',
    newSlug: 'kling-avatar'
  },
  {
    alias: 'kling--kling-3.0-turbo',
    newSlug: 'kling-3-0-turbo-text-to-video'
  },
  {
    alias: 'kling--kling-3.0-turbo-text-to-video',
    newSlug: 'kling-3-0-turbo-text-to-video'
  },
  {
    alias: 'kling--kling-v2-5-turbo',
    newSlug: 'kling-2-5-turbo-text-to-video'
  },
  {
    alias: 'kling--kling-v2-6',
    newSlug: 'kling-2-6-pro-text-to-video-with-audio'
  },
  {
    alias: 'kling--kling-v3',
    newSlug: 'kling-3-0-text-to-video'
  },
  {
    alias: 'kling--kling-v3-omni',
    newSlug: 'kling-o3-image-to-video'
  },
  {
    alias: 'kling--kling-video-o1',
    newSlug: 'kling-o3-text-to-video'
  },
  {
    alias: 'kling--lip-sync-audio-to-video',
    newSlug: 'kling-lip-sync-audio-to-video'
  },
  {
    alias: 'kling--lip-sync-text-to-video',
    newSlug: 'kling-lip-sync-text-to-video'
  },
  {
    alias: 'kling--omni-pro-edit-video',
    newSlug: 'kling-o3-video-edit'
  },
  {
    alias: 'kling--omni-pro-image-to-video',
    newSlug: 'kling-o3-image-to-video'
  },
  {
    alias: 'kling--omni-pro-text-to-video',
    newSlug: 'kling-o3-text-to-video'
  },
  {
    alias: 'kling--omni-pro-video-to-video',
    newSlug: 'kling-o3-video-to-video'
  },
  {
    alias: 'kling--text-to-video',
    newSlug: 'kling-2-5-turbo-text-to-video'
  },
  {
    alias: 'kling--text-to-video-with-audio',
    newSlug: 'kling-2-6-pro-text-to-video-with-audio'
  },
  {
    alias: 'kling--v3',
    newSlug: 'kling-3-0-text-to-video'
  },
  {
    alias: 'kling--videos-avatar-image2video',
    newSlug: 'kling-avatar'
  },
  {
    alias: 'kling--videos-lip-sync',
    newSlug: 'kling-lip-sync-text-to-video'
  },
  {
    alias: 'krea--krea-2-large',
    newSlug: 'krea-2-large-text-to-image'
  },
  {
    alias: 'krea--krea-2-medium',
    newSlug: 'krea-2-medium-text-to-image'
  },
  {
    alias: 'krea--krea-2-medium-turbo',
    newSlug: 'krea-2-medium-turbo-text-to-image'
  },
  {
    alias: 'luma--photon-1',
    newSlug: 'luma-photon-1-text-to-image'
  },
  {
    alias: 'luma--photon-1-image-generation',
    newSlug: 'luma-photon-1-text-to-image'
  },
  {
    alias: 'luma--photon-1-image-modify',
    newSlug: 'luma-photon-1-image-edit'
  },
  {
    alias: 'luma--photon-flash-1',
    newSlug: 'luma-photon-flash-1-text-to-image'
  },
  {
    alias: 'luma--photon-flash-1-image-generation',
    newSlug: 'luma-photon-flash-1-text-to-image'
  },
  {
    alias: 'luma--photon-flash-1-image-modify',
    newSlug: 'luma-photon-flash-1-image-edit'
  },
  {
    alias: 'luma--ray-2',
    newSlug: 'luma-ray-2-text-to-video'
  },
  {
    alias: 'luma--ray-2-image-to-video',
    newSlug: 'luma-ray-2-image-to-video'
  },
  {
    alias: 'luma--ray-2-text-to-video',
    newSlug: 'luma-ray-2-text-to-video'
  },
  {
    alias: 'luma--ray-flash-2',
    newSlug: 'luma-ray-flash-2-text-to-video'
  },
  {
    alias: 'luma--ray-flash-2-image-to-video',
    newSlug: 'luma-ray-flash-2-image-to-video'
  },
  {
    alias: 'luma--ray-flash-2-text-to-video',
    newSlug: 'luma-ray-flash-2-text-to-video'
  },
  {
    alias: 'luma_2--uni-1',
    newSlug: 'luma-uni-1-text-to-image'
  },
  {
    alias: 'luma_2--uni-1-image-edit',
    newSlug: 'luma-uni-1-image-edit'
  },
  {
    alias: 'luma_2--uni-1-image-generation',
    newSlug: 'luma-uni-1-text-to-image'
  },
  {
    alias: 'luma_2--uni-1-max',
    newSlug: 'luma-uni-1-max-text-to-image'
  },
  {
    alias: 'luma_2--uni-1-max-image-edit',
    newSlug: 'luma-uni-1-max-image-edit'
  },
  {
    alias: 'luma_2--uni-1-max-image-generation',
    newSlug: 'luma-uni-1-max-text-to-image'
  },
  {
    alias: 'openai--gpt-image-1',
    newSlug: 'gpt-image-1-image-edit'
  },
  {
    alias: 'openai--gpt-image-1.5',
    newSlug: 'gpt-image-1-5-image-edit'
  },
  {
    alias: 'openai--gpt-image-2',
    newSlug: 'gpt-image-2-text-to-image'
  },
  {
    alias: 'openai--gpt-image-2.5-flare',
    newSlug: 'gpt-image-2-5-flare-text-to-image'
  },
  {
    alias: 'openai--gpt-image-2.5-sunburst',
    newSlug: 'gpt-image-2-5-sunburst-text-to-image'
  },
  {
    alias: 'qwen--qwen-image-3.0',
    newSlug: 'qwen-image-3-0-text-to-image'
  },
  {
    alias: 'qwen--qwen-image-3.0-image-edit',
    newSlug: 'qwen-image-3-0-image-edit'
  },
  {
    alias: 'qwen--qwen-image-3.0-pro',
    newSlug: 'qwen-image-3-0-pro-text-to-image'
  },
  {
    alias: 'qwen--qwen-image-3.0-pro-image-edit',
    newSlug: 'qwen-image-3-0-pro-image-edit'
  },
  {
    alias: 'qwen--qwen-image-3.0-pro-text-to-image',
    newSlug: 'qwen-image-3-0-pro-text-to-image'
  },
  {
    alias: 'qwen--qwen-image-3.0-text-to-image',
    newSlug: 'qwen-image-3-0-text-to-image'
  },
  {
    alias: 'recraft--recraftv3',
    newSlug: 'recraft-v3-text-to-image'
  },
  {
    alias: 'recraft--recraftv4',
    newSlug: 'recraft-v4-text-to-image'
  },
  {
    alias: 'recraft--recraftv4_1',
    newSlug: 'recraft-v4-1-text-to-image'
  },
  {
    alias: 'recraft--recraftv4_1_pro',
    newSlug: 'recraft-v4-1-pro-text-to-image'
  },
  {
    alias: 'recraft--recraftv4_1_pro_vector',
    newSlug: 'recraft-v4-1-pro-text-to-vector'
  },
  {
    alias: 'recraft--recraftv4_1_utility',
    newSlug: 'recraft-v4-1-utility-text-to-image'
  },
  {
    alias: 'recraft--recraftv4_1_utility_pro',
    newSlug: 'recraft-v4-1-utility-pro-text-to-image'
  },
  {
    alias: 'recraft--recraftv4_1_utility_pro_vector',
    newSlug: 'recraft-v4-1-utility-pro-text-to-vector'
  },
  {
    alias: 'recraft--recraftv4_1_utility_vector',
    newSlug: 'recraft-v4-1-utility-text-to-vector'
  },
  {
    alias: 'recraft--recraftv4_1_vector',
    newSlug: 'recraft-v4-1-text-to-vector'
  },
  {
    alias: 'recraft--recraftv4_pro',
    newSlug: 'recraft-v4-pro-text-to-image'
  },
  {
    alias: 'recraft--v3-text-to-image',
    newSlug: 'recraft-v3-text-to-image'
  },
  {
    alias: 'recraft--v3-text-to-vector',
    newSlug: 'recraft-v3-text-to-vector'
  },
  {
    alias: 'recraft--v4-pro-text-to-image',
    newSlug: 'recraft-v4-pro-text-to-image'
  },
  {
    alias: 'recraft--v4-pro-text-to-vector',
    newSlug: 'recraft-v4-pro-text-to-vector'
  },
  {
    alias: 'recraft--v4-text-to-image',
    newSlug: 'recraft-v4-text-to-image'
  },
  {
    alias: 'recraft--v4-text-to-vector',
    newSlug: 'recraft-v4-text-to-vector'
  },
  {
    alias: 'recraft--v4.1-pro-text-to-image',
    newSlug: 'recraft-v4-1-pro-text-to-image'
  },
  {
    alias: 'recraft--v4.1-pro-text-to-vector',
    newSlug: 'recraft-v4-1-pro-text-to-vector'
  },
  {
    alias: 'recraft--v4.1-text-to-image',
    newSlug: 'recraft-v4-1-text-to-image'
  },
  {
    alias: 'recraft--v4.1-text-to-vector',
    newSlug: 'recraft-v4-1-text-to-vector'
  },
  {
    alias: 'recraft--v4.1-utility-pro-text-to-image',
    newSlug: 'recraft-v4-1-utility-pro-text-to-image'
  },
  {
    alias: 'recraft--v4.1-utility-pro-text-to-vector',
    newSlug: 'recraft-v4-1-utility-pro-text-to-vector'
  },
  {
    alias: 'recraft--v4.1-utility-text-to-image',
    newSlug: 'recraft-v4-1-utility-text-to-image'
  },
  {
    alias: 'recraft--v4.1-utility-text-to-vector',
    newSlug: 'recraft-v4-1-utility-text-to-vector'
  },
  {
    alias: 'runway--aleph2',
    newSlug: 'runway-aleph-2-video-to-video'
  },
  {
    alias: 'runway--aleph2-video-to-video',
    newSlug: 'runway-aleph-2-video-to-video'
  },
  {
    alias: 'runway--gen4-image',
    newSlug: 'runway-gen-4-image-text-to-image'
  },
  {
    alias: 'runway--gen4-turbo-image-to-video',
    newSlug: 'runway-gen-4-turbo-image-to-video'
  },
  {
    alias: 'runway--gen4_image',
    newSlug: 'runway-gen-4-image-text-to-image'
  },
  {
    alias: 'runway--gen4_turbo',
    newSlug: 'runway-gen-4-turbo-image-to-video'
  },
  {
    alias: 'veo--veo-3.1-generate-001',
    newSlug: 'veo-3-text-to-video'
  },
  {
    alias: 'vertexai--gemini-2.5-flash-image',
    newSlug: 'nano-banana-text-to-image'
  },
  {
    alias: 'vertexai--gemini-3-pro-image',
    newSlug: 'nano-banana-pro-text-to-image'
  },
  {
    alias: 'vertexai--gemini-3.1-flash-image',
    newSlug: 'nano-banana-2-text-to-image'
  },
  {
    alias: 'vertexai--gemini-nano-banana-2',
    newSlug: 'nano-banana-2-text-to-image'
  },
  {
    alias: 'vertexai--veo-3',
    newSlug: 'veo-3-text-to-video'
  },
  {
    alias: 'vertexai--veo-3-first-last-frame',
    newSlug: 'veo-3-first-last-frame'
  },
  {
    alias: 'wan--happyhorse-1.0-video-edit',
    newSlug: 'happyhorse-video-edit'
  },
  {
    alias: 'wan--happyhorse-1.1-r2v',
    newSlug: 'happyhorse-reference-to-video'
  },
  {
    alias: 'wan--happyhorse-1.1-t2v',
    newSlug: 'happyhorse-text-to-video'
  },
  {
    alias: 'wan--happyhorse-reference-video',
    newSlug: 'happyhorse-reference-to-video'
  },
  {
    alias: 'wan--happyhorse-text-to-video',
    newSlug: 'happyhorse-text-to-video'
  },
  {
    alias: 'wan--happyhorse-video-edit',
    newSlug: 'happyhorse-video-edit'
  },
  {
    alias: 'wan--image-to-image',
    newSlug: 'wan-2-5-image-edit'
  },
  {
    alias: 'wan--image-to-video',
    newSlug: 'wan-2-6-image-to-video'
  },
  {
    alias: 'wan--image-to-video-2.7',
    newSlug: 'wan-2-7-image-to-video'
  },
  {
    alias: 'wan--image-to-video-3.0',
    newSlug: 'wan-3-0-image-to-video'
  },
  {
    alias: 'wan--image-to-video-3.0-prime',
    newSlug: 'wan-3-0-prime-image-to-video'
  },
  {
    alias: 'wan--reference-to-video-3.0',
    newSlug: 'wan-3-0-reference-to-video'
  },
  {
    alias: 'wan--reference-to-video-3.0-prime',
    newSlug: 'wan-3-0-prime-reference-to-video'
  },
  {
    alias: 'wan--reference-video',
    newSlug: 'wan-2-6-reference-to-video'
  },
  {
    alias: 'wan--reference-video-2.7',
    newSlug: 'wan-2-7-reference-to-video'
  },
  {
    alias: 'wan--text-to-image',
    newSlug: 'wan-2-5-text-to-image'
  },
  {
    alias: 'wan--text-to-video',
    newSlug: 'wan-2-6-text-to-video'
  },
  {
    alias: 'wan--text-to-video-2.7',
    newSlug: 'wan-2-7-text-to-video'
  },
  {
    alias: 'wan--text-to-video-3.0',
    newSlug: 'wan-3-0-text-to-video'
  },
  {
    alias: 'wan--text-to-video-3.0-prime',
    newSlug: 'wan-3-0-prime-text-to-video'
  },
  {
    alias: 'wan--video-continuation-2.7',
    newSlug: 'wan-2-7-video-continuation'
  },
  {
    alias: 'wan--video-edit-2.7',
    newSlug: 'wan-2-7-video-edit'
  },
  {
    alias: 'wan--wan2.5-i2i-preview',
    newSlug: 'wan-2-5-image-edit'
  },
  {
    alias: 'wan--wan2.5-t2i-preview',
    newSlug: 'wan-2-5-text-to-image'
  },
  {
    alias: 'wan--wan2.6-i2v',
    newSlug: 'wan-2-6-image-to-video'
  },
  {
    alias: 'wan--wan2.6-r2v',
    newSlug: 'wan-2-6-reference-to-video'
  },
  {
    alias: 'wan--wan2.6-t2v',
    newSlug: 'wan-2-6-text-to-video'
  },
  {
    alias: 'wan--wan2.7-i2v',
    newSlug: 'wan-2-7-image-to-video'
  },
  {
    alias: 'wan--wan2.7-r2v',
    newSlug: 'wan-2-7-reference-to-video'
  },
  {
    alias: 'wan--wan2.7-t2v',
    newSlug: 'wan-2-7-text-to-video'
  },
  {
    alias: 'wan--wan2.7-videoedit',
    newSlug: 'wan-2-7-video-edit'
  },
  {
    alias: 'wan--wan3.0-video',
    newSlug: 'wan-3-0-image-to-video'
  },
  {
    alias: 'wan--wan3.0-video-prime',
    newSlug: 'wan-3-0-prime-image-to-video'
  },
  {
    alias: 'wavespeed--flashvsr',
    newSlug: 'flashvsr'
  },
  {
    alias: 'wavespeed--seedvr2',
    newSlug: 'seedvr2-image-upscaler'
  },
  {
    alias: 'wavespeed--seedvr2-image',
    newSlug: 'seedvr2-image-upscaler'
  },
  {
    alias: 'wavespeed--ultimate-image-upscaler',
    newSlug: 'ultimate-image-upscaler'
  },
  {
    alias: 'xai--grok-imagine-image',
    newSlug: 'grok-imagine-image-text-to-image'
  },
  {
    alias: 'xai--grok-imagine-image-2.0',
    newSlug: 'grok-imagine-image-2-0-text-to-image'
  },
  {
    alias: 'xai--grok-imagine-video',
    newSlug: 'grok-imagine-video-text-to-video'
  },
  {
    alias: 'xai--grok-imagine-video-1.5',
    newSlug: 'grok-imagine-video-1-5-text-to-video'
  },
  {
    alias: 'xai--grok-imagine-video-1.5-reference',
    newSlug: 'grok-imagine-video-1-5-reference-to-video'
  },
  {
    alias: 'xai--grok-imagine-video-reference',
    newSlug: 'grok-imagine-video-reference-to-video'
  }
]
