/**
 * The partner (API) pages that lived under /p/supported-models, each sent to
 * the Hub model page for the same model or, for a provider page, its current
 * model. `null` means no Hub page matches, so the page goes to the catalogue.
 */
export const partnerModelHubSlugs: Readonly<Record<string, string | null>> = {
  'anthropic-claude': null,
  beeble: 'beeble-switchx-image-edit',
  'bria-ai': 'bria-fibo-image-edit',
  elevenlabs: 'elevenlabs-text-to-dialogue',
  flux: 'flux-2-pro-text-to-image',
  'flux-2-api': 'flux-2-pro-text-to-image',
  'flux-api': 'flux-2-pro-text-to-image',
  'gemini-image': 'nano-banana-text-to-image',
  'grok-image': 'grok-imagine-image-text-to-image',
  'grok-imagine': 'grok-imagine-image-text-to-image',
  happyhorse1: 'happyhorse-text-to-video',
  heygen: 'heygen-starfish-text-to-speech',
  'hunyuan-3d': null,
  ideogram: 'ideogram-v4-text-to-image',
  'kling-2-6': 'kling-2-6-pro-text-to-video-with-audio',
  'kling-ai': 'kling-3-0-text-to-video',
  'kling-o3': 'kling-o3-text-to-video',
  'krea-2': 'krea-2-large-text-to-image',
  'ltx-2': null,
  'luma-dream-machine': 'luma-ray-2-text-to-video',
  'magnific-ai': 'magnific-skin-enhancer',
  'meshy-7': null,
  'meshy-ai': null,
  minimax: null,
  'nano-banana': 'nano-banana-text-to-image',
  'nano-banana-2': 'nano-banana-2-text-to-image',
  'openai-dall-e': null,
  openrouter: null,
  pixverse: null,
  quiver: null,
  'qwen-3': null,
  recraft: 'recraft-v4-1-pro-text-to-image',
  'rodin-3d': null,
  runway: 'runway-gen-4-turbo-image-to-video',
  'seedance-2': 'seedance-2-0-text-to-video',
  'seedance-2-0': 'seedance-2-0-text-to-video',
  'seedance-bytedance': 'seedance-2-0-text-to-video',
  sonilo: null,
  sync: null,
  'topaz-labs': null,
  'tripo-3d': null,
  'veo-2': 'veo-3-text-to-video',
  'veo-3': 'veo-3-text-to-video',
  vidu: null,
  'wan-3-0': 'wan-3-0-text-to-video',
  'wan-api': 'wan-3-0-text-to-video',
  'wan2-6': 'wan-2-6-text-to-video',
  'wan2-7': 'wan-2-7-text-to-video',
  wavespeed: null
}
