import { describe, expect, it } from 'vitest'

import { assess, convert, generateTests, guidanceFor } from './convert'
import { RULES } from './rules'

describe('rule catalog', () => {
  it('every rule names its replacement and where it is declared', () => {
    for (const rule of RULES) {
      expect({ id: rule.id, api: rule.replacement.api }).toMatchObject({
        api: expect.any(String)
      })
      expect(rule.replacement.api.length).toBeGreaterThan(0)
      expect(rule.replacement.declaredAt.length).toBeGreaterThan(0)
    }
  })

  it('every rule ships at least one golden case', () => {
    for (const rule of RULES) {
      expect({ id: rule.id, cases: rule.cases.length }.cases).toBeGreaterThan(0)
    }
  })

  // The golden cases are the contract. A rule that cannot state its own
  // before/after is not trustworthy enough to run unattended over 5,000 packs.
  describe.for(RULES.map((r) => [r.id, r] as const))('%s', ([, rule]) => {
    it.for(rule.cases.map((c) => [c.name, c] as const))(
      '%s',
      ([, testCase]) => {
        const result = convert(testCase.before, [rule])
        if (testCase.escalates) {
          expect(result.escalated.length).toBeGreaterThan(0)
          // Escalation must never silently alter the file.
          expect(result.source).toBe(testCase.before)
          expect(result.escalated[0].escalation).toBeTruthy()
        } else {
          expect(result.source).toBe(testCase.after)
        }
      }
    )
  })
})

describe('convert', () => {
  it('reports original line numbers after deletions', () => {
    const source = [
      'a();',
      '    this.type = this.type ?? undefined;',
      'b();',
      'node.outputs[0].links.push(1);'
    ].join('\n')

    const result = convert(source)
    expect(result.applied[0].line).toBe(2)
    // Still 4, not 3 — deletion must not renumber later findings.
    expect(result.escalated[0].line).toBe(4)
  })

  it('leaves a clean file untouched and unmarked', () => {
    const source = 'const x = 1;\nexport default x;'
    const result = convert(source)
    expect(result.changed).toBe(false)
    expect(result.source).toBe(source)
    expect(result.escalated).toEqual([])
  })

  it('applies several rules to one file', () => {
    const source = [
      'this.type = this.type ?? undefined;',
      'node.outputs[0].links.push(9);',
      'node.inputs[0].link = null;'
    ].join('\n')

    const result = convert(source)
    expect(result.applied.map((m) => m.rule)).toEqual(['type-write-noop'])
    expect(new Set(result.escalated.map((m) => m.rule))).toEqual(
      new Set(['output-links-mutation', 'input-link-write'])
    )
  })

  it('warns harder when a file also manipulates serialized workflow data', () => {
    const live = convert('node.inputs[0].link = null;')
    const serialized = convert(
      'p.workflow.nodes.forEach((n) => { n.inputs[0].link = null })'
    )
    expect(serialized.escalated[0].escalation).toMatch(/serialized/i)
    expect(live.escalated[0].escalation).not.toMatch(/serialized/i)
  })
})

describe('generated tests', () => {
  const context = {
    pack: 'rgthree-comfy',
    file: 'web/comfyui/base_node.js',
    registeredTypes: ['RgthreeFastMuter', 'RgthreeFastBypasser']
  }

  const converted = () =>
    convert('    this.type = this.type ?? undefined;\n    go();')

  it('emits a test for a rule that can prove its own effect', () => {
    const tests = generateTests(converted(), context)
    expect(tests).toHaveLength(1)
    expect(tests[0].filename).toBe('rgthree-comfy.type-write-noop.test.ts')
  })

  it('asserts the thing that actually broke — construction', () => {
    const [test] = generateTests(converted(), context)
    expect(test.source).toContain('createNode')
    expect(test.source).toContain('not.toBeNull()')
    expect(test.source).toContain('RgthreeFastMuter')
    expect(test.source).toContain('RgthreeFastBypasser')
  })

  it('is traceable back to the rule and the original lines', () => {
    const [test] = generateTests(converted(), context)
    expect(test.source).toContain('Generated by Magic Patch')
    expect(test.source).toContain('rule: type-write-noop')
    expect(test.source).toContain('line 1:')
    expect(test.source).toContain('rgthree-comfy')
  })

  it('separates equivalence claims from fix claims', () => {
    const [test] = generateTests(converted(), context)
    expect(test.equivalence.length).toBeGreaterThan(0)
    expect(test.fix.join(' ')).toMatch(/constructs/)
  })

  it('emits nothing rather than a vacuous test when types are unknown', () => {
    const tests = generateTests(converted(), {
      pack: 'unknown',
      file: 'x.js'
    })
    expect(tests).toEqual([])
  })

  it('emits nothing for rules that only escalated', () => {
    const result = convert('node.outputs[0].links.push(1);')
    expect(generateTests(result, context)).toEqual([])
  })
})

describe('confidence assessment', () => {
  const context = { pack: 'p', file: 'f.js', registeredTypes: ['A'] }

  it('is proven for a rule that is safe by construction, with no test', () => {
    // Deleting a self-assignment needs no runtime demonstration.
    const result = convert('this.type = this.type ?? undefined;')
    expect(assess(result, []).confidence).toBe('proven')
  })

  it('is demonstrated when a test exercises the change', () => {
    const result = convert('this.type = this.type ?? undefined;')
    const a = assess(result, generateTests(result, context))
    expect(a.confidence).toBe('demonstrated')
    expect(a.reasons.join(' ')).toMatch(/equivalence claim/)
  })

  it('is unverified when a judgement rule ran without a demonstration', () => {
    const judgement = {
      ...RULES[0],
      id: 'needs-judgement',
      mechanicallySafe: false
    }
    const result = convert('this.type = this.type ?? undefined;', [judgement])
    const a = assess(result, [], [judgement])
    expect(a.confidence).toBe('unverified')
    expect(a.reasons.join(' ')).toMatch(/needs-judgement/)
  })

  it('treats a no-op conversion as nothing to worry about', () => {
    expect(assess(convert('const x = 1;'), []).confidence).toBe('proven')
  })
})

describe('guidanceFor', () => {
  it('returns only the guidance for rules that matched', () => {
    const result = convert('this.type = this.type ?? undefined;')
    const guidance = guidanceFor([...result.applied, ...result.escalated])
    expect(guidance).toContain('type-write-noop')
    expect(guidance).not.toContain('output-links-mutation')
  })

  it('is empty when nothing matched', () => {
    expect(guidanceFor([])).toBe('')
  })
})
