import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

import { globSync } from 'glob'

interface GeneratedDocument {
  content: string
  path: string
}

interface TokenDefinition {
  sources: Set<string>
  values: Set<string>
}

const ROOT_DIRECTORY = resolve(process.cwd())
const GENERATED_DIRECTORY = 'docs/design-system/generated'
const TOKEN_SOURCES = [
  'packages/design-system/src/css/_palette.css',
  'packages/design-system/src/css/style.css'
]
const WEBSITE_TOKEN_SOURCES = ['apps/website/src/styles/global.css']

function escapeTableCell(value: string) {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ')
}

function extractTokens(sourcePaths: string[]) {
  const tokens = new Map<string, TokenDefinition>()

  for (const sourcePath of sourcePaths) {
    const css = readFileSync(resolve(ROOT_DIRECTORY, sourcePath), 'utf8')
    for (const match of css.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/gs)) {
      const name = match[1]
      const value = match[2].replace(/\s+/g, ' ').trim()
      const definition = tokens.get(name) ?? {
        sources: new Set<string>(),
        values: new Set<string>()
      }
      definition.sources.add(sourcePath)
      definition.values.add(value)
      tokens.set(name, definition)
    }
  }

  return [...tokens.entries()].sort(([left], [right]) =>
    left.localeCompare(right)
  )
}

function buildTokenDocument() {
  const rows = extractTokens(TOKEN_SOURCES).map(([name, definition]) => {
    const values = [...definition.values].map(escapeTableCell).join('<br>')
    const sources = [...definition.sources]
      .map((source) => `\`${source}\``)
      .join('<br>')
    return `| \`${name}\` | ${values} | ${sources} |`
  })

  return `# Code Token Inventory

> Generated by \`pnpm design-system:docs\`. Do not edit this file directly.

This is the complete CSS custom-property inventory exposed by the design-system
palette and full theme. A token may have multiple values because light and dark
themes redefine the same semantic role. Product code should consume semantic
Tailwind utilities such as \`bg-base-background\`; it should not copy values from
this table.

| Token | Declared value(s) | Source |
| --- | --- | --- |
${rows.join('\n')}
`
}

function buildWebsiteTokenDocument() {
  const rows = extractTokens(WEBSITE_TOKEN_SOURCES).map(
    ([name, definition]) => {
      const values = [...definition.values].map(escapeTableCell).join('<br>')
      const sources = [...definition.sources]
        .map((source) => `\`${source}\``)
        .join('<br>')
      return `| \`${name}\` | ${values} | ${sources} |`
    }
  )

  return `# Website Token Inventory

> Generated by \`pnpm design-system:docs\`. Do not edit this file directly.

This is the complete custom-property inventory declared by the public website
theme. Use its Tailwind utilities in \`apps/website\` instead of copying values
from this table. Locally scoped properties are included because the inventory is
descriptive; presence does not promote a property to a reusable semantic token.

| Token | Declared value(s) | Source |
| --- | --- | --- |
${rows.join('\n')}
`
}

function buildComponentDocument() {
  const componentPaths = globSync('src/components/ui/**/*.vue', {
    cwd: ROOT_DIRECTORY,
    ignore: ['**/__mocks__/**']
  }).sort()
  const rows = componentPaths.map((componentPath) => {
    const componentName =
      componentPath
        .split('/')
        .at(-1)
        ?.replace(/\.vue$/, '') ?? ''
    const family = dirname(componentPath).replace('src/components/ui/', '')
    const familyDirectory = resolve(ROOT_DIRECTORY, dirname(componentPath))
    const hasStory = existsSync(
      resolve(familyDirectory, `${componentName}.stories.ts`)
    )
    const hasTest = existsSync(
      resolve(familyDirectory, `${componentName}.test.ts`)
    )
    return `| ${componentName} | \`${componentPath}\` | ${family === 'src/components/ui' ? 'root' : family} | ${hasStory ? 'yes' : 'no'} | ${hasTest ? 'yes' : 'no'} |`
  })

  return `# Code Component Inventory

> Generated by \`pnpm design-system:docs\`. Do not edit this file directly.

This is the complete reusable component inventory under \`src/components/ui\`.
Start with the family root component. Use the other entries when assembling a
documented compound primitive such as Dialog or Select. Storybook and unit-test
columns show the available implementation context; they are not quality scores.

| Component | Import source | Family | Storybook | Unit test |
| --- | --- | --- | --- | --- |
${rows.join('\n')}
`
}

function buildWebsiteComponentDocument() {
  const componentPaths = globSync(
    [
      'apps/website/src/components/ui/**/*.vue',
      'apps/website/src/components/common/**/*.vue',
      'apps/website/src/components/blocks/**/*.vue'
    ],
    {
      cwd: ROOT_DIRECTORY,
      ignore: ['**/__mocks__/**']
    }
  ).sort()
  const rows = componentPaths.map((componentPath) => {
    const componentName =
      componentPath
        .split('/')
        .at(-1)
        ?.replace(/\.vue$/, '') ?? ''
    const family = componentPath.includes('/components/ui/')
      ? componentPath
          .split('/components/ui/')[1]
          .split('/')
          .slice(0, -1)
          .join('/') || 'root'
      : componentPath.includes('/components/blocks/')
        ? 'blocks'
        : 'common'
    const familyDirectory = resolve(ROOT_DIRECTORY, dirname(componentPath))
    const hasStory = existsSync(
      resolve(familyDirectory, `${componentName}.stories.ts`)
    )
    const hasTest = existsSync(
      resolve(familyDirectory, `${componentName}.test.ts`)
    )
    return `| ${componentName} | \`${componentPath}\` | ${family} | ${hasStory ? 'yes' : 'no'} | ${hasTest ? 'yes' : 'no'} |`
  })

  return `# Website Component Inventory

> Generated by \`pnpm design-system:docs\`. Do not edit this file directly.

This is the reusable component inventory for the public Comfy website. Components
under \`common\` and \`blocks\` are established website compositions; components
under \`ui\` are the lower-level primitives they build upon. Presence in this
inventory proves that code exists, but approval rules and permitted variants live in
\`docs/design-system/website/components/\`.

| Component | Import source | Family | Storybook | Unit test |
| --- | --- | --- | --- | --- |
${rows.join('\n')}
`
}

function documents(): GeneratedDocument[] {
  return [
    {
      path: `${GENERATED_DIRECTORY}/TOKENS.md`,
      content: buildTokenDocument()
    },
    {
      path: `${GENERATED_DIRECTORY}/WEBSITE_TOKENS.md`,
      content: buildWebsiteTokenDocument()
    },
    {
      path: `${GENERATED_DIRECTORY}/COMPONENTS.md`,
      content: buildComponentDocument()
    },
    {
      path: `${GENERATED_DIRECTORY}/WEBSITE_COMPONENTS.md`,
      content: buildWebsiteComponentDocument()
    }
  ]
}

function run() {
  const check = process.argv.includes('--check')
  const staleDocuments: string[] = []

  for (const document of documents()) {
    const absolutePath = resolve(ROOT_DIRECTORY, document.path)
    if (check) {
      if (
        !existsSync(absolutePath) ||
        readFileSync(absolutePath, 'utf8') !== document.content
      ) {
        staleDocuments.push(document.path)
      }
      continue
    }

    mkdirSync(dirname(absolutePath), { recursive: true })
    writeFileSync(absolutePath, document.content)
  }

  if (staleDocuments.length > 0) {
    console.error(
      `Design-system documentation is stale: ${staleDocuments.join(', ')}. Run pnpm design-system:docs.`
    )
    process.exitCode = 1
  }
}

const entryPath = process.argv[1]
if (entryPath && pathToFileURL(resolve(entryPath)).href === import.meta.url)
  run()
