export const IMAGE_PREVIEW_CONTENT_MIN_HEIGHT = 220
export const IMAGE_PREVIEW_MARGIN_TOP = 8
export const NODE_CONTENT_GAP = 4
export const IMAGE_PREVIEW_HEIGHT_RESERVE =
  IMAGE_PREVIEW_CONTENT_MIN_HEIGHT + IMAGE_PREVIEW_MARGIN_TOP + NODE_CONTENT_GAP
