import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

function dataPath(basename: string): string {
  return resolve('browser_tests/fixtures/data', basename)
}

const VALID_TIERS = ['load', 'run', 'connectivity'] as const

export type CustomNodeTier = (typeof VALID_TIERS)[number]

// Which pack list to test. The local gate tests the CLOUD pack list against a
// LOCAL backend, so this must NOT also select backend behaviour: Cloud's
// coreDisabledNodes describe Cloud, and applying them here would expect nodes
// to be absent that this backend serves.
const VALID_MANIFESTS = ['core', 'cloud'] as const
// Separate from the manifest: the local gate runs CLOUD's pack list against a
// LOCAL backend, and the two disagree about which nodes exist because Cloud
// disables some. localExpectations records that difference; it must not apply
// when these same specs run against Cloud.
const VALID_BACKENDS = ['local', 'cloud'] as const
const CLOUD_LOCAL_CALIBRATION_SHARDS = 5

interface SharedNodeExpectations {
  pack: string
  tiers: CustomNodeTier[]
  // Frontend-format workflow (path relative to browser_tests/) loaded and queued
  // by the run tier. Run the backend with --cache-none, or repeat runs classify
  // PARTIAL when cached nodes skip executing.
  workflow: string
  // Runtime class_type / object_info keys, NOT Python class names (e.g. rgthree
  // registers "Power Primitive (rgthree)", not RgthreePowerPrimitive).
  expectedNodes: string[]
  expectedRunnableCount?: number
  expectedRunnableNodeTypesSha256?: string
  timeoutMs: number
}

export interface CoreManifestEntry extends SharedNodeExpectations {
  repo: string
  pin: string
  // Frontend extension names the pack's JS registers at boot (via
  // app.registerExtension), calibrated from the pinned source. Asserted
  // against window.app.extensions in the load tier: backend nodes can
  // register while the pack's frontend JS silently fails to load (wrong
  // web dir, a loadExtensions regression), and every JS-dependent
  // assertion in this suite would then quietly test vanilla nodes.
  // Empty array = no healthy boot registration is expected. Source-proven
  // broken registrations are tracked by the explicit broken-extension ledger.
  expectedExtensions: string[]
  // Exact number of nodes the pack registers at its pin, calibrated from the
  // gating CI's object_info. The all-nodes tiers derive their corpus from the
  // live backend, so without this a pack that silently registers fewer nodes
  // (a broken sub-import, a core change breaking registration) shrinks
  // coverage while CI stays green. Any delta - either direction - fails until
  // the count is deliberately recalibrated alongside a pin/core change.
  expectedNodeCount: number
  requiresGpu: boolean
  requiresModels: string[]
  // Nodes that cannot execute on pure defaults. Asserted both ways: an
  // unlisted failure is a regression, a listed clean run is a stale entry.
  cannotRunAlone?: string[]
}

// Rows are generated by `pnpm gen:cloud-manifest <object-info-snapshot.json>`.
export interface CloudManifestEntry extends SharedNodeExpectations {
  deployRef: string
  disabledNodes: Record<string, string[]>
  expectedExtensions: string[]
  expectedNodeCount: number
  webDirectory?: string
  cannotRunAlone?: string[]
}

export interface CloudManifestSource {
  repository: string
  ref: string
  path: string
  importedAt: string
}

export interface CloudManifest {
  source: CloudManifestSource
  coreDisabledNodes: Record<string, string[]>
  packs: CloudManifestEntry[]
  // yaml packs the snapshot has no nodes for. Recorded rather than dropped:
  // the snapshot cannot distinguish "pack registers nothing" from "the dirname
  // mapping broke", so the list is a reviewed record - a pack appearing here
  // has no cloud coverage, and the list growing is the signal to look.
  unjoinedYamlPacks: string[]
}

export const AUTOGROW_CASES = [
  {
    pack: 'ComfyUI-Impact-Pack',
    extensionName: 'Comfy.Impack',
    extensionPathPack: 'comfyui-impact-pack',
    consumerType: 'ImpactMakeImageList',
    producerType: 'EmptyImage',
    producerSlot: 'IMAGE'
  }
] as const

export const FRONTEND_ASSET_EXCLUSIONS: Record<
  string,
  {
    deployRef: string
    reason: string
    restore: string
    webDirectory: string
  }
> = {
  'ComfyUI-DepthAnythingV3': {
    deployRef: 'ComfyUI-DepthAnythingV3@0.1.2',
    webDirectory: 'web',
    reason:
      'the registry artifact declares WEB_DIRECTORY="./web" but contains no web/ directory',
    restore:
      'publish an artifact containing web/ and remove this entry when the served extension path appears'
  }
}

function extensionPathPack(value: string): string | undefined {
  try {
    const segments = new URL(value, 'http://comfy.invalid').pathname
      .split('/')
      .filter(Boolean)
      .flatMap((segment) => {
        try {
          return decodeURIComponent(segment).split('/').filter(Boolean)
        } catch {
          return [segment]
        }
      })
    const extensionsIndex = segments.findIndex(
      (segment) => segment.toLowerCase() === 'extensions'
    )
    return extensionsIndex >= 0 ? segments[extensionsIndex + 1] : undefined
  } catch {
    return undefined
  }
}

export function servesFrontendAssetsForPack(
  servedExtensionPaths: readonly string[],
  pack: string
): boolean {
  return servedExtensionPaths.some(
    (value) => extensionPathPack(value)?.toLowerCase() === pack.toLowerCase()
  )
}

export function staleAutogrowApplicabilityIssues(
  entry: { pack: string; expectedExtensions: readonly string[] },
  registeredExtensions: readonly string[],
  servedExtensionPaths: readonly string[]
): string[] {
  return AUTOGROW_CASES.flatMap((autogrowCase) => {
    if (
      autogrowCase.pack.toLowerCase() !== entry.pack.toLowerCase() ||
      entry.expectedExtensions.includes(autogrowCase.extensionName)
    )
      return []

    const served = servesFrontendAssetsForPack(
      servedExtensionPaths,
      autogrowCase.extensionPathPack
    )
    return [
      ...(served
        ? [
            `frontend assets for "${autogrowCase.extensionName}" are now served - restore expectedExtensions and autogrow coverage`
          ]
        : []),
      ...(registeredExtensions.includes(autogrowCase.extensionName)
        ? [
            `frontend extension "${autogrowCase.extensionName}" is now registered - restore expectedExtensions and autogrow coverage`
          ]
        : [])
    ]
  })
}

function workflowFileExists(workflow: string): boolean {
  return existsSync(resolve('browser_tests', workflow))
}

function sharedIssues(entry: SharedNodeExpectations): string[] {
  const missing: string[] = []
  // CI installs the pack into custom_nodes/<pack>, and node attribution keys
  // on that directory name via python_module - so pack must be a safe,
  // plain path segment, not just non-empty.
  if (
    typeof entry.pack !== 'string' ||
    !/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(entry.pack)
  )
    missing.push('pack (must be a plain path segment)')
  // workflow may be an empty string until the pack gains a run-tier fixture.
  if (typeof entry.workflow !== 'string') missing.push('workflow')
  else if (
    Array.isArray(entry.tiers) &&
    entry.tiers.includes('run') &&
    (entry.workflow === '' || !workflowFileExists(entry.workflow))
  )
    missing.push('workflow (committed file required when tiers includes "run")')
  if (!Array.isArray(entry.expectedNodes) || entry.expectedNodes.length === 0)
    missing.push('expectedNodes')
  if (!Array.isArray(entry.tiers) || entry.tiers.length === 0)
    missing.push('tiers')
  // A typo like "connectivty" would otherwise pass and silently drop that
  // tier's coverage - the exact drift this manifest exists to catch.
  else if (entry.tiers.some((tier) => !VALID_TIERS.includes(tier)))
    missing.push(`tiers (unknown value; allowed: ${VALID_TIERS.join(', ')})`)
  else if (
    entry.tiers.includes('run') &&
    (!Number.isInteger(entry.expectedRunnableCount) ||
      (entry.expectedRunnableCount ?? 0) <= 0)
  )
    missing.push('expectedRunnableCount (positive integer for run tier)')
  else if (
    entry.tiers.includes('run') &&
    !/^[0-9a-f]{64}$/.test(entry.expectedRunnableNodeTypesSha256 ?? '')
  )
    missing.push('expectedRunnableNodeTypesSha256 (sha256 for run tier)')
  else if (
    !entry.tiers.includes('run') &&
    entry.expectedRunnableCount !== undefined
  )
    missing.push('expectedRunnableCount (only valid for run tier)')
  else if (
    !entry.tiers.includes('run') &&
    entry.expectedRunnableNodeTypesSha256 !== undefined
  )
    missing.push('expectedRunnableNodeTypesSha256 (only valid for run tier)')
  if (!Number.isFinite(entry.timeoutMs) || entry.timeoutMs <= 0)
    missing.push('timeoutMs')
  return missing
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function stringList(value: unknown, allowEmpty = false): string[] | undefined {
  if (
    !Array.isArray(value) ||
    (!allowEmpty && value.length === 0) ||
    !value.every(isNonEmptyString) ||
    new Set(value).size !== value.length
  )
    return undefined
  return [...value]
}

function tierList(value: unknown): CustomNodeTier[] | undefined {
  const values = stringList(value)
  if (values === undefined || !values.every(isCustomNodeTier)) return undefined
  return values
}

function isCustomNodeTier(value: string): value is CustomNodeTier {
  return VALID_TIERS.some((tier) => tier === value)
}

function labelRecord(value: unknown): Record<string, string[]> | undefined {
  if (!isRecord(value)) return undefined
  const record: Record<string, string[]> = {}
  for (const [node, labels] of Object.entries(value)) {
    if (!isLabelList(labels)) return undefined
    record[node] = [...labels]
  }
  return record
}

function isLabelList(value: unknown): value is string[] {
  return (
    Array.isArray(value) &&
    value.length > 0 &&
    value.every(isNonEmptyString) &&
    new Set(value).size === value.length
  )
}

function isPositiveInteger(value: unknown): value is number {
  return typeof value === 'number' && Number.isInteger(value) && value > 0
}

function invalidRecordOf(
  map: unknown,
  isValidValue: (value: unknown) => boolean
): boolean {
  return (
    typeof map !== 'object' ||
    map === null ||
    Array.isArray(map) ||
    Object.values(map).some((value) => !isValidValue(value))
  )
}

function calibrationIssues(
  entry: Pick<
    CoreManifestEntry,
    'expectedExtensions' | 'expectedNodeCount' | 'cannotRunAlone'
  >
): string[] {
  const missing: string[] = []
  // Explicitly required (an empty array deliberately expects no healthy boot
  // registration; known-broken registrations use their separate ledger) so a
  // new pack row cannot silently opt out of the extension-loaded assert.
  if (
    !Array.isArray(entry.expectedExtensions) ||
    !entry.expectedExtensions.every(isNonEmptyString) ||
    new Set(entry.expectedExtensions).size !== entry.expectedExtensions.length
  )
    missing.push('expectedExtensions (unique non-empty extension names)')
  if (
    !Number.isInteger(entry.expectedNodeCount) ||
    entry.expectedNodeCount <= 0
  )
    missing.push('expectedNodeCount (positive integer, calibrated at the pin)')
  if (
    entry.cannotRunAlone !== undefined &&
    (!Array.isArray(entry.cannotRunAlone) ||
      !entry.cannotRunAlone.every(isNonEmptyString) ||
      new Set(entry.cannotRunAlone).size !== entry.cannotRunAlone.length)
  )
    missing.push('cannotRunAlone (unique non-empty node keys)')
  return missing
}

function throwIfIncomplete(
  label: string,
  pack: unknown,
  index: number,
  missing: string[]
): void {
  if (missing.length > 0)
    throw new Error(
      `${label} entry ${index} (${typeof pack === 'string' ? pack : '?'}) missing: ${missing.join(', ')}`
    )
}

// Exported for the pure spec's validation cases; production callers go
// through loadManifest.
export function assertCoreEntry(entry: CoreManifestEntry, index: number): void {
  const missing = sharedIssues(entry)
  // CI clones from repo, so an empty value must fail here, not mid-clone.
  if (!isNonEmptyString(entry.repo)) missing.push('repo')
  if (!/^[0-9a-f]{40}$/.test(entry.pin ?? ''))
    missing.push('pin (full 40-char commit SHA required)')
  missing.push(...calibrationIssues(entry))
  if (!Array.isArray(entry.requiresModels)) missing.push('requiresModels')
  if (typeof entry.requiresGpu !== 'boolean') missing.push('requiresGpu')
  if (
    entry.tiers.includes('run') &&
    (entry.requiresGpu ||
      (Array.isArray(entry.requiresModels) && entry.requiresModels.length > 0))
  )
    missing.push('run tier (must be executable on the model-free CPU gate)')
  throwIfIncomplete('custom-node manifest', entry.pack, index, missing)
}

const DEPLOY_REF_URL = /^https?:\/\/\S+@[0-9a-f]{40}$/
const DEPLOY_REF_REGISTRY = /^[A-Za-z0-9][A-Za-z0-9._-]*@\S+$/

export function assertCloudEntry(
  entry: CloudManifestEntry,
  index: number
): void {
  const missing = sharedIssues(entry)
  if (
    typeof entry.deployRef !== 'string' ||
    !(
      DEPLOY_REF_URL.test(entry.deployRef) ||
      DEPLOY_REF_REGISTRY.test(entry.deployRef)
    )
  )
    missing.push('deployRef (git URL@sha or registry id@version)')
  if (invalidRecordOf(entry.disabledNodes, isLabelList))
    missing.push('disabledNodes (node key -> non-empty unique label list)')
  if (
    entry.webDirectory !== undefined &&
    (typeof entry.webDirectory !== 'string' ||
      !/^(?!.*(?:^|\/)\.\.(?:\/|$))[^/][A-Za-z0-9._/-]*$/.test(
        entry.webDirectory
      ))
  )
    missing.push('webDirectory (safe relative path)')
  missing.push(...calibrationIssues(entry))
  throwIfIncomplete('custom-node cloud manifest', entry.pack, index, missing)
}

function readEnum<T extends readonly string[]>(
  name: string,
  allowed: T,
  fallback: T[number]
): T[number] {
  const raw = process.env[name] || fallback
  const hit = allowed.find((candidate) => candidate === raw)
  if (hit === undefined)
    throw new Error(
      `${name}='${raw}' is not valid (allowed: ${allowed.join(', ')}; unset defaults to ${fallback})`
    )
  return hit
}

export function customNodesManifest(): (typeof VALID_MANIFESTS)[number] {
  return readEnum('CUSTOM_NODES_MANIFEST', VALID_MANIFESTS, 'core')
}

function customNodesBackend(): (typeof VALID_BACKENDS)[number] {
  return readEnum('CUSTOM_NODES_BACKEND', VALID_BACKENDS, 'local')
}

interface LocalExpectation {
  expectedNodeCount: number
  expectedExtensions?: string[]
  reason: string
}

function loadLocalExpectations(): Record<string, LocalExpectation> {
  if (customNodesBackend() !== 'local' || customNodesManifest() !== 'cloud')
    return {}
  const path = dataPath('cloud/localExpectations.json')
  if (!existsSync(path)) return {}
  const parsed: unknown = JSON.parse(readFileSync(path, 'utf-8'))
  if (!isRecord(parsed))
    throw new Error(`${path} must be a JSON object keyed by pack name`)
  const entries: Record<string, LocalExpectation> = {}
  const manifestPacks = new Set(
    readCloudManifest().packs.map(({ pack }) => pack)
  )
  for (const [pack, entry] of Object.entries(parsed)) {
    if (!manifestPacks.has(pack))
      throw new Error(`${path}: ${pack} is not in the cloud manifest`)
    if (!isRecord(entry))
      throw new Error(`${path}: ${pack} has an invalid local expectation`)
    const expectedExtensions =
      entry.expectedExtensions === undefined
        ? undefined
        : stringList(entry.expectedExtensions, true)
    if (
      !isPositiveInteger(entry.expectedNodeCount) ||
      !isNonEmptyString(entry.reason) ||
      (entry.expectedExtensions !== undefined &&
        expectedExtensions === undefined)
    )
      throw new Error(`${path}: ${pack} has an invalid local expectation`)
    entries[pack] = {
      expectedNodeCount: entry.expectedNodeCount,
      reason: entry.reason,
      ...(expectedExtensions === undefined ? {} : { expectedExtensions })
    }
  }
  return entries
}

/**
 * How many nodes this pack registers on the backend under test.
 *
 * The cloud manifest is generated from Cloud's object_info, and a local
 * ComfyUI serves the nodes Cloud disables - so the manifest number is right
 * for Cloud and wrong here. Nodes are not disabled locally to imitate Cloud;
 * what a local backend actually serves is recorded instead.
 */
export function expectedNodeCountFor(
  entry: CoreManifestEntry | CloudManifestEntry
): number {
  return (
    loadLocalExpectations()[entry.pack]?.expectedNodeCount ??
    entry.expectedNodeCount
  )
}

/**
 * Frontend extensions this pack registers on the backend under test.
 *
 * Cloud serves no frontend assets for some packs and records an empty list; a
 * local install serves them, and staleAutogrowApplicabilityIssues correctly
 * reds when coverage was withheld on a premise that no longer holds here.
 */
export function expectedExtensionsFor(
  entry: CoreManifestEntry | CloudManifestEntry
): string[] {
  return (
    loadLocalExpectations()[entry.pack]?.expectedExtensions ??
    entry.expectedExtensions
  )
}

/** Entries whose local count has caught up with the manifest are stale. */
export function staleLocalExpectations(): string[] {
  const local = loadLocalExpectations()
  return loadFullManifest()
    .filter(
      (entry) =>
        local[entry.pack] !== undefined &&
        local[entry.pack].expectedNodeCount === entry.expectedNodeCount
    )
    .map((entry) => entry.pack)
}

/**
 * Which slice of the manifest this run owns, as `index/total`, 1-based.
 */
function manifestShard(): { index: number; total: number } | null {
  const raw = process.env.CUSTOM_NODES_SHARD
  if (!raw) return null
  const parsed = /^(\d+)\/(\d+)$/.exec(raw)
  if (!parsed)
    throw new Error(
      `CUSTOM_NODES_SHARD='${raw}' is not index/total (e.g. 3/10)`
    )
  const index = Number(parsed[1])
  const total = Number(parsed[2])
  if (index < 1 || total < 1 || index > total)
    throw new Error(
      `CUSTOM_NODES_SHARD='${raw}' is out of range (need 1 <= index <= total)`
    )
  return { index, total }
}

/**
 * Balanced by node count, not by pack count.
 *
 * Equal pack counts are not equal work: expectedNodeCount runs from 1 to 285
 * with a median of 6, and S1/S2/S3 walk every node, so a few packs dominate a
 * slice. Round-robin striping ignored that and produced a 4.86x spread on run
 * 31849196357 - 1,220 nodes in one shard against 251 in another - and since a
 * matrix costs its slowest shard, that one straggler was the whole run.
 *
 * Greedy longest-processing-time: heaviest pack first, always into the
 * lightest shard. Deterministic for the pinned manifest; ties preserve its
 * reviewed order.
 */
export function shardOf<T>(
  entries: readonly T[],
  weightOf: (entry: T) => number = () => 1
): T[] {
  const shard = manifestShard()
  if (!shard) return [...entries]
  const bins: T[][] = Array.from({ length: shard.total }, () => [])
  const load = new Array<number>(shard.total).fill(0)
  const ordered = [...entries]
    .map((entry, index) => ({ entry, index }))
    .sort((a, b) => weightOf(b.entry) - weightOf(a.entry) || a.index - b.index)
  for (const { entry } of ordered) {
    const lightest = load.indexOf(Math.min(...load))
    bins[lightest].push(entry)
    load[lightest] += weightOf(entry)
  }
  return bins[shard.index - 1]
}

export function assertCloudManifestShape(
  parsed: unknown,
  sourcePath: string
): CloudManifest {
  if (!isRecord(parsed))
    throw new Error(
      `${sourcePath} is malformed (expected { source, coreDisabledNodes, packs, unjoinedYamlPacks } with at least one pack): regenerate it via 'pnpm gen:cloud-manifest'`
    )
  const source = cloudManifestSource(parsed.source)
  const coreDisabledNodes = labelRecord(parsed.coreDisabledNodes)
  const unjoinedYamlPacks = stringList(parsed.unjoinedYamlPacks, true)
  if (
    source === undefined ||
    coreDisabledNodes === undefined ||
    !Array.isArray(parsed.packs) ||
    parsed.packs.length === 0 ||
    // Required, and an empty array is the deliberate "every yaml pack joined"
    // declaration - the live assert reads this list, so a missing or malformed
    // one would silently assert nothing.
    unjoinedYamlPacks === undefined
  )
    throw new Error(
      `${sourcePath} is malformed (expected { source, coreDisabledNodes, packs, unjoinedYamlPacks } with at least one pack): regenerate it via 'pnpm gen:cloud-manifest'`
    )
  const packs = parsed.packs.map(canonicalCloudEntry)
  return { source, coreDisabledNodes, packs, unjoinedYamlPacks }
}

function isIsoDate(value: unknown): value is string {
  if (typeof value !== 'string') return false
  const timestamp = Date.parse(`${value}T00:00:00Z`)
  return (
    !Number.isNaN(timestamp) &&
    new Date(timestamp).toISOString().slice(0, 10) === value
  )
}

function cloudManifestSource(value: unknown): CloudManifestSource | undefined {
  if (!isRecord(value)) return undefined
  if (
    typeof value.repository !== 'string' ||
    !/^https:\/\/github\.com\/[^/]+\/[^/]+$/.test(value.repository) ||
    typeof value.ref !== 'string' ||
    !/^[0-9a-f]{40}$/.test(value.ref) ||
    typeof value.path !== 'string' ||
    value.path.length === 0 ||
    !isIsoDate(value.importedAt)
  )
    return undefined
  return {
    repository: value.repository,
    ref: value.ref,
    path: value.path,
    importedAt: value.importedAt
  }
}

function canonicalCloudEntry(
  value: unknown,
  index: number
): CloudManifestEntry {
  if (!isRecord(value))
    throw new Error(
      `custom-node cloud manifest entry ${index} is not an object`
    )
  const tiers = tierList(value.tiers)
  const expectedNodes = stringList(value.expectedNodes)
  const expectedExtensions = stringList(value.expectedExtensions, true)
  const disabledNodes = labelRecord(value.disabledNodes)
  const cannotRunAlone =
    value.cannotRunAlone === undefined
      ? undefined
      : stringList(value.cannotRunAlone, true)
  if (
    typeof value.pack !== 'string' ||
    typeof value.deployRef !== 'string' ||
    typeof value.workflow !== 'string' ||
    tiers === undefined ||
    expectedNodes === undefined ||
    expectedExtensions === undefined ||
    disabledNodes === undefined ||
    typeof value.expectedNodeCount !== 'number' ||
    typeof value.timeoutMs !== 'number' ||
    (value.expectedRunnableCount !== undefined &&
      typeof value.expectedRunnableCount !== 'number') ||
    (value.expectedRunnableNodeTypesSha256 !== undefined &&
      typeof value.expectedRunnableNodeTypesSha256 !== 'string') ||
    (value.webDirectory !== undefined &&
      typeof value.webDirectory !== 'string') ||
    (value.cannotRunAlone !== undefined && cannotRunAlone === undefined)
  )
    throw new Error(`custom-node cloud manifest entry ${index} is malformed`)
  const entry: CloudManifestEntry = {
    pack: value.pack,
    deployRef: value.deployRef,
    tiers,
    workflow: value.workflow,
    expectedNodes,
    expectedExtensions,
    expectedNodeCount: value.expectedNodeCount,
    timeoutMs: value.timeoutMs,
    disabledNodes,
    ...(value.expectedRunnableCount === undefined
      ? {}
      : { expectedRunnableCount: value.expectedRunnableCount }),
    ...(value.expectedRunnableNodeTypesSha256 === undefined
      ? {}
      : {
          expectedRunnableNodeTypesSha256: value.expectedRunnableNodeTypesSha256
        }),
    ...(value.webDirectory === undefined
      ? {}
      : { webDirectory: value.webDirectory }),
    ...(cannotRunAlone === undefined ? {} : { cannotRunAlone })
  }
  assertCloudEntry(entry, index)
  return entry
}

function readCloudManifest(): CloudManifest {
  const cloudPath = dataPath('customNodeManifest.cloud.json')
  if (!existsSync(cloudPath))
    throw new Error(
      `CUSTOM_NODES_MANIFEST=cloud but ${cloudPath} does not exist. ` +
        `The cloud manifest is generated, never hand-authored: run ` +
        `'pnpm gen:cloud-manifest <object-info-snapshot.json>', which joins ` +
        `the vendored browser_tests/` +
        `fixtures/data/cloud/supported_nodes.yaml with a Cloud /object_info ` +
        `snapshot. That snapshot is the Phase-1 probe output; until the ` +
        `probe has run, the cloud suite cannot run.`
    )
  return assertCloudManifestShape(
    JSON.parse(readFileSync(cloudPath, 'utf-8')),
    cloudPath
  )
}

function readCoreManifest(): CoreManifestEntry[] {
  const path = dataPath('customNodeManifest.core.json')
  const parsed: unknown = JSON.parse(readFileSync(path, 'utf-8'))
  if (!Array.isArray(parsed))
    throw new Error(
      `custom-node manifest ${path} must be a JSON array of entries, got ${parsed === null ? 'null' : typeof parsed}`
    )
  return parsed.map(canonicalCoreEntry)
}

function canonicalCoreEntry(value: unknown, index: number): CoreManifestEntry {
  if (!isRecord(value))
    throw new Error(`custom-node manifest entry ${index} is not an object`)
  const tiers = tierList(value.tiers)
  const expectedNodes = stringList(value.expectedNodes)
  const expectedExtensions = stringList(value.expectedExtensions, true)
  const requiresModels = stringList(value.requiresModels, true)
  const cannotRunAlone =
    value.cannotRunAlone === undefined
      ? undefined
      : stringList(value.cannotRunAlone, true)
  if (
    typeof value.pack !== 'string' ||
    typeof value.repo !== 'string' ||
    typeof value.pin !== 'string' ||
    typeof value.workflow !== 'string' ||
    tiers === undefined ||
    expectedNodes === undefined ||
    expectedExtensions === undefined ||
    typeof value.expectedNodeCount !== 'number' ||
    typeof value.timeoutMs !== 'number' ||
    typeof value.requiresGpu !== 'boolean' ||
    requiresModels === undefined ||
    (value.expectedRunnableCount !== undefined &&
      typeof value.expectedRunnableCount !== 'number') ||
    (value.expectedRunnableNodeTypesSha256 !== undefined &&
      typeof value.expectedRunnableNodeTypesSha256 !== 'string') ||
    (value.cannotRunAlone !== undefined && cannotRunAlone === undefined)
  )
    throw new Error(`custom-node manifest entry ${index} is malformed`)
  const entry: CoreManifestEntry = {
    pack: value.pack,
    repo: value.repo,
    pin: value.pin,
    tiers,
    workflow: value.workflow,
    expectedNodes,
    expectedExtensions,
    expectedNodeCount: value.expectedNodeCount,
    timeoutMs: value.timeoutMs,
    requiresGpu: value.requiresGpu,
    requiresModels,
    ...(value.expectedRunnableCount === undefined
      ? {}
      : { expectedRunnableCount: value.expectedRunnableCount }),
    ...(value.expectedRunnableNodeTypesSha256 === undefined
      ? {}
      : {
          expectedRunnableNodeTypesSha256: value.expectedRunnableNodeTypesSha256
        }),
    ...(cannotRunAlone === undefined ? {} : { cannotRunAlone })
  }
  assertCoreEntry(entry, index)
  return entry
}

export function loadAllManifestPackNames(): string[] {
  return loadAllManifestTargets().map(({ pack }) => pack)
}

export function loadAllManifestIdentities(): string[] {
  return loadAllManifestTargets().map(({ identity }) => identity)
}

export function loadAllManifestTargets(): Array<{
  identity: string
  pack: string
}> {
  return [...readCoreManifest(), ...readCloudManifest().packs].map((entry) => ({
    identity: packIdentity(entry),
    pack: entry.pack
  }))
}

export function loadUnjoinedYamlPacks(): string[] {
  return customNodesManifest() === 'cloud'
    ? readCloudManifest().unjoinedYamlPacks
    : []
}

/**
 * What this pack is pinned to, whatever form its manifest uses.
 *
 * Core rows carry a git commit; cloud rows carry the deployRef Cloud actually
 * ships - `owner/repo@sha` for git-sourced packs, `id@version` for registry
 * packs, which the registry distributes as a CDN artifact and for which no
 * commit exists. Callers recording provenance want the identity, not the form.
 */
export function packIdentity(
  entry: CoreManifestEntry | CloudManifestEntry
): string {
  return 'deployRef' in entry ? entry.deployRef : entry.pin
}

interface QuarantineDetails {
  reason: string
  evidence: string
  upstreamFix: string
  since: string
}

export type QuarantinedPack = QuarantineDetails &
  (
    | { class: 'unfetchable-ref'; failurePattern?: never }
    | { class: 'unsatisfiable-requirement'; failurePattern: string }
    | { class: 'requires-gpu-runner'; failurePattern?: never }
  )

// Packs this local CPU gate cannot exercise. Network-verifiable source failures
// are rechecked by the workflow; hardware exclusions remain visible in every
// Actions summary until a GPU-backed shard restores their coverage.
export function loadPackQuarantine(): Record<string, QuarantinedPack> {
  const path = dataPath('cloud/packQuarantine.json')
  if (!existsSync(path)) return {}
  const parsed: unknown = JSON.parse(readFileSync(path, 'utf-8'))
  if (!isRecord(parsed))
    throw new Error(`${path} must be a JSON object keyed by pack name`)
  const entries: Record<string, QuarantinedPack> = {}
  const manifestPacks = new Set(
    readCloudManifest().packs.map(({ pack }) => pack)
  )
  for (const [pack, entry] of Object.entries(parsed)) {
    if (!manifestPacks.has(pack))
      throw new Error(`${path}: ${pack} is not in the cloud manifest`)
    if (
      !isRecord(entry) ||
      (entry.class !== 'unfetchable-ref' &&
        entry.class !== 'unsatisfiable-requirement' &&
        entry.class !== 'requires-gpu-runner') ||
      !isNonEmptyString(entry.reason) ||
      !isNonEmptyString(entry.evidence) ||
      (entry.class === 'unsatisfiable-requirement' &&
        !isNonEmptyString(entry.failurePattern)) ||
      !isNonEmptyString(entry.upstreamFix) ||
      !isIsoDate(entry.since)
    )
      throw new Error(`${path}: ${pack} has an invalid quarantine entry`)
    if (entry.class === 'unsatisfiable-requirement') {
      if (!isNonEmptyString(entry.failurePattern))
        throw new Error(`${path}: ${pack} has an invalid quarantine entry`)
      entries[pack] = {
        class: entry.class,
        reason: entry.reason,
        evidence: entry.evidence,
        failurePattern: entry.failurePattern,
        upstreamFix: entry.upstreamFix,
        since: entry.since
      }
    } else {
      entries[pack] = {
        class: entry.class,
        reason: entry.reason,
        evidence: entry.evidence,
        upstreamFix: entry.upstreamFix,
        since: entry.since
      }
    }
  }
  return entries
}

export function loadManifest(): (CoreManifestEntry | CloudManifestEntry)[] {
  const shard = manifestShard()
  if (
    customNodesManifest() === 'cloud' &&
    customNodesBackend() === 'local' &&
    shard !== null &&
    shard.total !== CLOUD_LOCAL_CALIBRATION_SHARDS
  )
    throw new Error(
      `cloud/local expectations are calibrated for ${CLOUD_LOCAL_CALIBRATION_SHARDS} shards, got ${shard.total}; recalibrate the exact node, persistence, and connectivity contracts before changing the matrix`
    )
  // Assign over the FULL manifest, then drop the excluded packs. Packing the
  // filtered list instead made shard composition depend on the exclusion
  // ledgers: moving four packs out of quarantine moved 26 of 81 packs to a
  // different shard. All packs in a shard share one Python environment, so a
  // pack's neighbours decide which of its optional imports resolve and how
  // many node classes it registers - WanVideoWrapper measured 141, 142 and 146
  // across three runs without its own pin changing. Composition now moves only
  // when the manifest does.
  const quarantined =
    customNodesManifest() === 'cloud' ? loadPackQuarantine() : {}
  return shardOf(loadFullManifest(), (entry) => entry.expectedNodeCount).filter(
    (entry) => !(entry.pack in quarantined)
  )
}

/** Every pack the manifest declares, ignoring the shard slice. */
export function loadFullManifest(): (CoreManifestEntry | CloudManifestEntry)[] {
  if (customNodesManifest() === 'cloud') return readCloudManifest().packs
  return readCoreManifest()
}

export function loadApplicableAutogrowCases() {
  const full = loadFullManifest()
  const shard = new Set(loadManifest().map((entry) => entry.pack))
  return AUTOGROW_CASES.flatMap((autogrowCase) => {
    const manifestEntry = full.find(
      (entry) => entry.pack.toLowerCase() === autogrowCase.pack.toLowerCase()
    )
    // Stale AUTOGROW_CASES is a manifest-wide fact and must fail everywhere;
    // whether this shard runs the pack is a separate question below.
    if (!manifestEntry)
      throw new Error(
        `${autogrowCase.pack} is not a manifest pack - fix AUTOGROW_CASES`
      )
    if (!shard.has(manifestEntry.pack)) return []
    return expectedExtensionsFor(manifestEntry).includes(
      autogrowCase.extensionName
    )
      ? [{ autogrowCase, manifestEntry }]
      : []
  })
}
