import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

// Lazy: import.meta.url is not a file: URL under vitest happy-dom.
function dataPath(basename: string): string {
  return fileURLToPath(new URL(`../data/${basename}`, import.meta.url))
}

const VALID_TIERS = ['load', 'run', 'connectivity', 'io'] as const

export type CustomNodeTier = (typeof VALID_TIERS)[number]

// Which pack list to test. The local gate tests the CLOUD pack list against a
// LOCAL backend, so this must NOT also select backend behaviour: cloud's
// coreDisabledNodes/unjoinedYamlPacks describe Cloud, and applying them here
// would expect nodes to be absent that this backend serves. When the cloud
// assertions land, they need their own backend flag, not this one.
const VALID_MANIFESTS = ['core', 'cloud'] as const

interface SharedNodeExpectations {
  pack: string
  tiers: CustomNodeTier[]
  // Frontend-format workflow (path relative to browser_tests/) loaded and queued
  // by the run tier; empty or absent file = tier skips. Run the backend with
  // --cache-none, or repeat runs classify PARTIAL when cached nodes skip executing.
  workflow: string
  // Runtime class_type / object_info keys, NOT Python class names (e.g. rgthree
  // registers "Power Primitive (rgthree)", not RgthreePowerPrimitive).
  expectedNodes: string[]
  timeoutMs: number
  // Optional; absent means true. Set false ONLY with evidence that the pack's
  // nodes fail to mount under Vue Nodes 2.0 (probe it - a README grumble is
  // not evidence). When false, renderer-specific Vue assertions are not
  // applied to this pack: its tests still run and pass their LiteGraph-canvas
  // assertions, so the zero-skip gate is preserved.
  vueNodesCompatible?: boolean
  // Node key -> evidenced reason it cannot mount under Vue Nodes 2.0; only
  // the Vue mount assertion is withheld. Stale keys fail the suite.
  vueIncompatibleNodes?: Record<string, string>
}

export interface CoreManifestEntry extends SharedNodeExpectations {
  repo: string
  pin: string
  // Frontend extension names the pack's JS registers at boot (via
  // app.registerExtension), calibrated from the pinned source. Asserted
  // against window.app.extensions in the load tier: backend nodes can
  // register while the pack's frontend JS silently fails to load (wrong
  // web dir, a loadExtensions regression), and every JS-dependent
  // assertion in this suite would then quietly test vanilla nodes.
  // Empty array = no healthy boot registration is expected. Source-proven
  // broken registrations are tracked by the explicit broken-extension ledger.
  expectedExtensions: string[]
  // Exact number of nodes the pack registers at its pin, calibrated from the
  // gating CI's object_info. The all-nodes tiers derive their corpus from the
  // live backend, so without this a pack that silently registers fewer nodes
  // (a broken sub-import, a core change breaking registration) shrinks
  // coverage while CI stays green. Any delta - either direction - fails until
  // the count is deliberately recalibrated alongside a pin/core change.
  expectedNodeCount: number
  requiresGpu: boolean
  requiresModels: string[]
  // Nodes that cannot execute on pure defaults. Asserted both ways: an
  // unlisted failure is a regression, a listed clean run is a stale entry.
  cannotRunAlone?: string[]
}

// Rows are generated by scripts/gen-cloud-manifest.ts, never hand-edited.
export interface CloudManifestEntry extends SharedNodeExpectations {
  deployRef: string
  disabledNodes: Record<string, string[]>
  expectedExtensions: string[]
  expectedNodeCount: number
  cannotRunAlone?: string[]
}

export interface CloudManifest {
  coreDisabledNodes: Record<string, string[]>
  packs: CloudManifestEntry[]
  // yaml packs the snapshot has no nodes for. Recorded rather than dropped:
  // the snapshot cannot distinguish "pack registers nothing" from "the dirname
  // mapping broke", so the list is a reviewed record - a pack appearing here
  // has no cloud coverage, and the list growing is the signal to look.
  unjoinedYamlPacks: string[]
}

export const AUTOGROW_CASES = [
  {
    pack: 'ComfyUI-Impact-Pack',
    extensionName: 'Comfy.Impack',
    extensionPathPack: 'comfyui-impact-pack',
    consumerType: 'ImpactMakeImageList',
    producerType: 'EmptyImage',
    producerSlot: 'IMAGE'
  }
] as const

export function staleAutogrowApplicabilityIssues(
  entry: { pack: string; expectedExtensions: readonly string[] },
  registeredExtensions: readonly string[],
  servedExtensionPaths: readonly string[]
): string[] {
  return AUTOGROW_CASES.flatMap((autogrowCase) => {
    if (
      autogrowCase.pack.toLowerCase() !== entry.pack.toLowerCase() ||
      entry.expectedExtensions.includes(autogrowCase.extensionName)
    )
      return []

    const served = servedExtensionPaths.some((value) => {
      try {
        const segments = new URL(value, 'http://comfy.invalid').pathname
          .split('/')
          .filter(Boolean)
          .flatMap((segment) => {
            try {
              return decodeURIComponent(segment).split('/').filter(Boolean)
            } catch {
              return [segment]
            }
          })
        const extensionsIndex = segments.findIndex(
          (segment) => segment.toLowerCase() === 'extensions'
        )
        return (
          extensionsIndex >= 0 &&
          segments[extensionsIndex + 1]?.toLowerCase() ===
            autogrowCase.extensionPathPack.toLowerCase()
        )
      } catch {
        return false
      }
    })
    return [
      ...(served
        ? [
            `frontend assets for "${autogrowCase.extensionName}" are now served - restore expectedExtensions and autogrow coverage`
          ]
        : []),
      ...(registeredExtensions.includes(autogrowCase.extensionName)
        ? [
            `frontend extension "${autogrowCase.extensionName}" is now registered - restore expectedExtensions and autogrow coverage`
          ]
        : [])
    ]
  })
}

function sharedIssues(entry: SharedNodeExpectations): string[] {
  const missing: string[] = []
  // CI installs the pack into custom_nodes/<pack>, and node attribution keys
  // on that directory name via python_module - so pack must be a safe,
  // plain path segment, not just non-empty.
  if (
    typeof entry.pack !== 'string' ||
    !/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(entry.pack)
  )
    missing.push('pack (must be a plain path segment)')
  // workflow may be an empty string until the pack gains a run-tier fixture.
  if (typeof entry.workflow !== 'string') missing.push('workflow')
  // A run-tier row with no workflow would otherwise skip locally, leaving
  // only CI's skip gate to notice the lost coverage. Fail at load instead.
  else if (
    entry.workflow === '' &&
    Array.isArray(entry.tiers) &&
    entry.tiers.includes('run')
  )
    missing.push('workflow (required when tiers includes "run")')
  if (!Array.isArray(entry.expectedNodes) || entry.expectedNodes.length === 0)
    missing.push('expectedNodes')
  if (!Array.isArray(entry.tiers) || entry.tiers.length === 0)
    missing.push('tiers')
  // A typo like "connectivty" would otherwise pass and silently drop that
  // tier's coverage - the exact drift this manifest exists to catch.
  else if (entry.tiers.some((tier) => !VALID_TIERS.includes(tier)))
    missing.push(`tiers (unknown value; allowed: ${VALID_TIERS.join(', ')})`)
  if (!Number.isFinite(entry.timeoutMs) || entry.timeoutMs <= 0)
    missing.push('timeoutMs')
  if (
    entry.vueNodesCompatible !== undefined &&
    typeof entry.vueNodesCompatible !== 'boolean'
  )
    missing.push('vueNodesCompatible')
  if (
    entry.vueIncompatibleNodes !== undefined &&
    invalidRecordOf(entry.vueIncompatibleNodes, isNonEmptyString)
  )
    missing.push('vueIncompatibleNodes (node key -> non-empty reason string)')
  return missing
}

function isNonEmptyString(value: unknown): boolean {
  return typeof value === 'string' && value.length > 0
}

function isLabelList(value: unknown): boolean {
  return (
    Array.isArray(value) &&
    value.length > 0 &&
    value.every(isNonEmptyString) &&
    new Set(value).size === value.length
  )
}

function invalidRecordOf(
  map: unknown,
  isValidValue: (value: unknown) => boolean
): boolean {
  return (
    typeof map !== 'object' ||
    map === null ||
    Array.isArray(map) ||
    Object.values(map).some((value) => !isValidValue(value))
  )
}

function calibrationIssues(
  entry: Pick<
    CoreManifestEntry,
    'expectedExtensions' | 'expectedNodeCount' | 'cannotRunAlone'
  >
): string[] {
  const missing: string[] = []
  // Explicitly required (an empty array deliberately expects no healthy boot
  // registration; known-broken registrations use their separate ledger) so a
  // new pack row cannot silently opt out of the extension-loaded assert.
  if (
    !Array.isArray(entry.expectedExtensions) ||
    !entry.expectedExtensions.every(isNonEmptyString) ||
    new Set(entry.expectedExtensions).size !== entry.expectedExtensions.length
  )
    missing.push('expectedExtensions (unique non-empty extension names)')
  if (
    !Number.isInteger(entry.expectedNodeCount) ||
    entry.expectedNodeCount <= 0
  )
    missing.push('expectedNodeCount (positive integer, calibrated at the pin)')
  if (
    entry.cannotRunAlone !== undefined &&
    (!Array.isArray(entry.cannotRunAlone) ||
      !entry.cannotRunAlone.every(isNonEmptyString) ||
      new Set(entry.cannotRunAlone).size !== entry.cannotRunAlone.length)
  )
    missing.push('cannotRunAlone (unique non-empty node keys)')
  return missing
}

function throwIfIncomplete(
  label: string,
  pack: unknown,
  index: number,
  missing: string[]
): void {
  if (missing.length > 0)
    throw new Error(
      `${label} entry ${index} (${typeof pack === 'string' ? pack : '?'}) missing: ${missing.join(', ')}`
    )
}

// Exported for the pure spec's validation cases; production callers go
// through loadManifest.
export function assertCoreEntry(entry: CoreManifestEntry, index: number): void {
  const missing = sharedIssues(entry)
  // CI clones from repo, so an empty value must fail here, not mid-clone.
  if (!isNonEmptyString(entry.repo)) missing.push('repo')
  // The gate tests exactly what was verified, so pin is a required full
  // commit SHA. CUSTOM_NODES_ALLOW_UNPINNED=1 is a loader escape hatch
  // currently exercised only by the pure spec - the nightly pack-drift
  // canary ignores pin fields in its own install step instead, and the
  // PR gate never unpins.
  if (
    !/^[0-9a-f]{40}$/.test(entry.pin ?? '') &&
    !(
      process.env.CUSTOM_NODES_ALLOW_UNPINNED === '1' &&
      (entry.pin ?? '') === ''
    )
  )
    missing.push('pin (full 40-char commit SHA required)')
  missing.push(...calibrationIssues(entry))
  if (!Array.isArray(entry.requiresModels)) missing.push('requiresModels')
  if (typeof entry.requiresGpu !== 'boolean') missing.push('requiresGpu')
  throwIfIncomplete('custom-node manifest', entry.pack, index, missing)
}

const DEPLOY_REF_URL = /^https?:\/\/\S+@[0-9a-f]{40}$/
const DEPLOY_REF_REGISTRY = /^[A-Za-z0-9][A-Za-z0-9._-]*@\S+$/

export function assertCloudEntry(
  entry: CloudManifestEntry,
  index: number
): void {
  const missing = sharedIssues(entry)
  if (
    typeof entry.deployRef !== 'string' ||
    !(
      DEPLOY_REF_URL.test(entry.deployRef) ||
      DEPLOY_REF_REGISTRY.test(entry.deployRef)
    )
  )
    missing.push('deployRef (git URL@sha or registry id@version)')
  if (invalidRecordOf(entry.disabledNodes, isLabelList))
    missing.push('disabledNodes (node key -> non-empty unique label list)')
  missing.push(...calibrationIssues(entry))
  throwIfIncomplete('custom-node cloud manifest', entry.pack, index, missing)
}

// Renderer passes for the load tier: LiteGraph canvas always, Vue Nodes 2.0
// unless the pack declares itself incompatible. Conditional coverage, never a
// test.skip - the caller still runs and gates on the returned passes.
export function rendererPassesFor(
  entry: Pick<SharedNodeExpectations, 'vueNodesCompatible'>
): boolean[] {
  return entry.vueNodesCompatible === false ? [false] : [false, true]
}

function readEnum<T extends readonly string[]>(
  name: string,
  allowed: T,
  fallback: T[number]
): T[number] {
  const raw = process.env[name] || fallback
  const hit = allowed.find((candidate) => candidate === raw)
  if (hit === undefined)
    throw new Error(
      `${name}='${raw}' is not valid (allowed: ${allowed.join(', ')}; unset defaults to ${fallback})`
    )
  return hit
}

function customNodesManifest(): (typeof VALID_MANIFESTS)[number] {
  return readEnum('CUSTOM_NODES_MANIFEST', VALID_MANIFESTS, 'core')
}

/**
 * Which slice of the manifest this run owns, as `index/total`, 1-based.
 */
function manifestShard(): { index: number; total: number } | null {
  const raw = process.env.CUSTOM_NODES_SHARD
  if (!raw) return null
  const parsed = /^(\d+)\/(\d+)$/.exec(raw)
  if (!parsed)
    throw new Error(
      `CUSTOM_NODES_SHARD='${raw}' is not index/total (e.g. 3/10)`
    )
  const index = Number(parsed[1])
  const total = Number(parsed[2])
  if (index < 1 || total < 1 || index > total)
    throw new Error(
      `CUSTOM_NODES_SHARD='${raw}' is out of range (need 1 <= index <= total)`
    )
  return { index, total }
}

/**
 * Balanced by node count, not by pack count.
 *
 * Equal pack counts are not equal work: expectedNodeCount runs from 1 to 285
 * with a median of 6, and S1/S2/S3 walk every node, so a few packs dominate a
 * slice. Round-robin striping ignored that and produced a 4.86x spread on run
 * 31849196357 - 1,220 nodes in one shard against 251 in another - and since a
 * matrix costs its slowest shard, that one straggler was the whole run.
 *
 * Greedy longest-processing-time: heaviest pack first, always into the
 * lightest shard. Deterministic given the manifest, and ties break on pack
 * name so a reordered manifest cannot silently reshuffle the slices.
 */
export function shardOf<T>(
  entries: readonly T[],
  weightOf: (entry: T) => number = () => 1
): T[] {
  const shard = manifestShard()
  if (!shard) return [...entries]
  const bins: T[][] = Array.from({ length: shard.total }, () => [])
  const load = new Array<number>(shard.total).fill(0)
  const ordered = [...entries]
    .map((entry, index) => ({ entry, index }))
    .sort((a, b) => weightOf(b.entry) - weightOf(a.entry) || a.index - b.index)
  for (const { entry } of ordered) {
    const lightest = load.indexOf(Math.min(...load))
    bins[lightest].push(entry)
    load[lightest] += weightOf(entry)
  }
  return bins[shard.index - 1]
}

function assertCloudManifestShape(
  parsed: unknown,
  sourcePath: string
): CloudManifest {
  const manifest = parsed as CloudManifest
  if (
    typeof manifest !== 'object' ||
    manifest === null ||
    invalidRecordOf(manifest.coreDisabledNodes, isLabelList) ||
    !Array.isArray(manifest.packs) ||
    manifest.packs.length === 0 ||
    // Required, and an empty array is the deliberate "every yaml pack joined"
    // declaration - the live assert reads this list, so a missing or malformed
    // one would silently assert nothing.
    !Array.isArray(manifest.unjoinedYamlPacks) ||
    !manifest.unjoinedYamlPacks.every(isNonEmptyString) ||
    new Set(manifest.unjoinedYamlPacks).size !==
      manifest.unjoinedYamlPacks.length
  )
    throw new Error(
      `${sourcePath} is malformed (expected { coreDisabledNodes, packs, unjoinedYamlPacks } with at least one pack): regenerate it via 'pnpm gen:cloud-manifest'`
    )
  manifest.packs.forEach(assertCloudEntry)
  return manifest
}

function readCloudManifest(): CloudManifest {
  const cloudPath = dataPath('customNodeManifest.cloud.json')
  if (!existsSync(cloudPath))
    throw new Error(
      `CUSTOM_NODES_MANIFEST=cloud but ${cloudPath} does not exist. ` +
        `The cloud manifest is generated, never hand-authored: run ` +
        `'pnpm gen:cloud-manifest <object-info-snapshot.json>' (scripts/` +
        `gen-cloud-manifest.ts), which joins the vendored browser_tests/` +
        `fixtures/data/cloud/supported_nodes.yaml with a Cloud /object_info ` +
        `snapshot. That snapshot is the Phase-1 probe output; until the ` +
        `probe has run, the cloud suite cannot run.`
    )
  return assertCloudManifestShape(
    JSON.parse(readFileSync(cloudPath, 'utf-8')),
    cloudPath
  )
}

function readCoreManifest(): CoreManifestEntry[] {
  const path = dataPath('customNodeManifest.core.json')
  const parsed: unknown = JSON.parse(readFileSync(path, 'utf-8'))
  if (!Array.isArray(parsed))
    throw new Error(
      `custom-node manifest ${path} must be a JSON array of entries, got ${parsed === null ? 'null' : typeof parsed}`
    )
  const entries: CoreManifestEntry[] = parsed
  entries.forEach(assertCoreEntry)
  return entries
}

export function loadAllManifestPackNames(): string[] {
  return [
    ...readCoreManifest().map((entry) => entry.pack),
    ...readCloudManifest().packs.map((entry) => entry.pack)
  ]
}

/**
 * What this pack is pinned to, whatever form its manifest uses.
 *
 * Core rows carry a git commit; cloud rows carry the deployRef Cloud actually
 * ships - `owner/repo@sha` for git-sourced packs, `id@version` for registry
 * packs, which the registry distributes as a CDN artifact and for which no
 * commit exists. Callers recording provenance want the identity, not the form.
 */
export function packIdentity(
  entry: CoreManifestEntry | CloudManifestEntry
): string {
  return 'deployRef' in entry ? entry.deployRef : entry.pin
}

export interface QuarantinedPack {
  class: 'unfetchable-ref' | 'unsatisfiable-requirement'
  reason: string
  evidence: string
  upstreamFix: string
  since: string
}

// Packs that cannot be installed at the ref the manifest declares, for a
// reason only their author can fix. They are excluded from the population
// rather than left to red every run - but the exclusion is asserted, not
// trusted: the workflow re-checks each entry and fails when one starts
// working, so a quarantine cannot outlive the bug it documents.
export function loadPackQuarantine(): Record<string, QuarantinedPack> {
  const path = dataPath('cloud/packQuarantine.json')
  if (!existsSync(path)) return {}
  const parsed: unknown = JSON.parse(readFileSync(path, 'utf-8'))
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed))
    throw new Error(`${path} must be a JSON object keyed by pack name`)
  return parsed as Record<string, QuarantinedPack>
}

// A quarantine is lost coverage, so its size is gated: past this many packs
// the run fails rather than quietly measuring less of the ecosystem. Raising
// it is a deliberate edit, which is the point.
export const MAX_QUARANTINED_PACKS = 5

export function loadManifest(): (CoreManifestEntry | CloudManifestEntry)[] {
  const quarantined = loadPackQuarantine()
  return shardOf(
    loadFullManifest().filter((entry) => !(entry.pack in quarantined)),
    (entry) => entry.expectedNodeCount
  )
}

/** Every pack the manifest declares, ignoring the shard slice. */
export function loadFullManifest(): (CoreManifestEntry | CloudManifestEntry)[] {
  if (customNodesManifest() === 'cloud') return readCloudManifest().packs
  return readCoreManifest()
}

export function loadApplicableAutogrowCases() {
  const full = loadFullManifest()
  const shard = new Set(loadManifest().map((entry) => entry.pack))
  return AUTOGROW_CASES.flatMap((autogrowCase) => {
    const manifestEntry = full.find(
      (entry) => entry.pack.toLowerCase() === autogrowCase.pack.toLowerCase()
    )
    // Stale AUTOGROW_CASES is a manifest-wide fact and must fail everywhere;
    // whether this shard runs the pack is a separate question below.
    if (!manifestEntry)
      throw new Error(
        `${autogrowCase.pack} is not a manifest pack - fix AUTOGROW_CASES`
      )
    if (!shard.has(manifestEntry.pack)) return []
    return manifestEntry.expectedExtensions.includes(autogrowCase.extensionName)
      ? [{ autogrowCase, manifestEntry }]
      : []
  })
}
