name: Build ComfyUI Frontend
description: 'Install dependencies and build ComfyUI_frontend'
inputs:
  build_frontend:
    description: 'Whether to build the frontend'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    # Note: this workflow assume frontend repo is checked out in the root of the workspace

    # Install pnpm, Node.js, build frontend
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'pnpm'
        cache-dependency-path: './pnpm-lock.yaml'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build ComfyUI_frontend if needed
      if: ${{ inputs.build_frontend == 'true' }}
      shell: bash
      run: pnpm build
