// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://platformapi.comfy.org' | (string & {})
}

/**
 * Hourly price and credit cost for one GPU class.
 */
export type RateCardGpu = {
  /**
   * Stable machine-readable GPU identifier.
   */
  gpuClass: string
  /**
   * Human-readable GPU display name.
   */
  label: string
  /**
   * VRAM in gigabytes.
   */
  vramGb: number
  /**
   * Price per GPU-hour in US dollars.
   */
  pricePerHourUsd: number
  /**
   * Price per GPU-hour in Comfy Credits.
   */
  creditsPerHour: number
}

/**
 * Monthly price and credit cost for one storage type.
 */
export type StorageRate = {
  /**
   * Stable machine-readable storage type identifier.
   */
  storageType: string
  /**
   * Human-readable storage type display name.
   */
  label: string
  /**
   * Price per GB per month in US dollars.
   */
  pricePerGbMonthUsd: number
  /**
   * Price per GB per month in Comfy Credits.
   */
  creditsPerGbMonth: number
}

/**
 * Current GPU and storage rate card served by the Deploy API.
 */
export type RateCard = {
  gpus: Array<RateCardGpu>
  storage: Array<StorageRate>
}

export type GetRateCardData = {
  body?: never
  path?: never
  query?: never
  url: '/deploy/v1/rate-card'
}

export type GetRateCardResponses = {
  /**
   * Current rate card
   */
  200: RateCard
}

export type GetRateCardResponse =
  GetRateCardResponses[keyof GetRateCardResponses]
