// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod'

/**
 * Hourly price and credit cost for one GPU class.
 */
export const zRateCardGpu = z.object({
  gpuClass: z.string(),
  label: z.string(),
  vramGb: z.number().int(),
  pricePerHourUsd: z.number(),
  creditsPerHour: z.number()
})

/**
 * Monthly price and credit cost for one storage type.
 */
export const zStorageRate = z.object({
  storageType: z.string(),
  label: z.string(),
  pricePerGbMonthUsd: z.number(),
  creditsPerGbMonth: z.number()
})

/**
 * Current GPU and storage rate card served by the Deploy API.
 */
export const zRateCard = z.object({
  gpus: z.array(zRateCardGpu),
  storage: z.array(zStorageRate)
})

/**
 * Current rate card
 */
export const zGetRateCardResponse = zRateCard
