import { describe, expect, it } from 'vitest'

import {
  AUTH_ERROR_COPY,
  AUTH_TOAST_SUMMARIES,
  UNAUTHORIZED_DOMAIN_MESSAGES
} from '@comfyorg/account/firebaseAuthError'
import { TURNSTILE_MESSAGES } from '@comfyorg/account/turnstile'

import en from './en/main.json'
import ja from './ja/main.json'
import zh from './zh/main.json'

/**
 * English is the hand-edited source both this app and the package tables
 * start from, so it is pinned by value. ja and zh here are regenerated by
 * the translation job from that source and are pinned by key set only; the
 * package carries its own ja/zh tables for the Workshop site.
 */
describe('auth copy shipped here and the @comfyorg/account tables', () => {
  it('en auth.errors equals the package table', () => {
    expect(
      en.auth.errors,
      'edit the package table and en/main.json together; the website reads the package'
    ).toEqual(AUTH_ERROR_COPY.en)
  })

  it('en auth.turnstile equals the package table', () => {
    expect(en.auth.turnstile).toEqual(TURNSTILE_MESSAGES.en)
  })

  it('en unauthorized-domain and toast summaries equal the package copy', () => {
    expect(en.toastMessages.unauthorizedDomain).toBe(
      UNAUTHORIZED_DOMAIN_MESSAGES.en
    )
    expect({ error: en.g.error, warn: en.g.warning }).toEqual(
      AUTH_TOAST_SUMMARIES.en
    )
  })

  it.for([
    ['ja', ja, 'ja'],
    ['zh', zh, 'zh-CN']
  ] as const)(
    '%s carries every auth.errors key the package resolves',
    ([, messages, packageLocale]) => {
      expect(Object.keys(messages.auth.errors).sort()).toEqual(
        Object.keys(AUTH_ERROR_COPY[packageLocale]).sort()
      )
    }
  )
})
