import { defineCollection } from 'astro:content'
import { file, glob } from 'astro/loaders'

import { customerStorySchema } from './content/customers.schema'
import { faqSchema } from './content/faq.schema'
import { workshopModelSchema } from './content/workshop-models.schema'

const customers = defineCollection({
  // Preserve the exact path as the id (default slugification lowercases the
  // `zh-CN` locale folder, which would break locale filtering).
  loader: glob({
    base: './src/content/customers',
    pattern: '**/*.mdx',
    generateId: ({ entry }) => entry.replace(/\.mdx$/, '')
  }),
  schema: customerStorySchema
})

const faq = defineCollection({
  loader: glob({
    base: './src/content/faq',
    pattern: '**/*.mdx',
    generateId: ({ entry }) => entry.replace(/\.mdx$/, '')
  }),
  schema: faqSchema
})

// Generated by `pnpm generate:workshop-catalog`: every Router model as one
// packed array, a line per model. `file()` rather than `glob()` because this
// is generated data nobody reads by hand -- 270 lines rather than 25,296
// across 268 files, while a model change is still exactly one changed line.
// Entry ids come from each object's own `id`; the schema stays the one place
// the shape is written down.
const workshopModels = defineCollection({
  loader: file('./src/content/workshop-models.json'),
  schema: workshopModelSchema
})

export const collections = { customers, faq, workshopModels }
