import { defineCollection } from 'astro:content'
import { glob } from 'astro/loaders'

import { customerStorySchema } from './content/customers.schema'
import { faqSchema } from './content/faq.schema'
import { workshopModelSchema } from './content/workshop-models.schema'

const customers = defineCollection({
  // Preserve the exact path as the id (default slugification lowercases the
  // `zh-CN` locale folder, which would break locale filtering).
  loader: glob({
    base: './src/content/customers',
    pattern: '**/*.mdx',
    generateId: ({ entry }) => entry.replace(/\.mdx$/, '')
  }),
  schema: customerStorySchema
})

const faq = defineCollection({
  loader: glob({
    base: './src/content/faq',
    pattern: '**/*.mdx',
    generateId: ({ entry }) => entry.replace(/\.mdx$/, '')
  }),
  schema: faqSchema
})

// Generated by `pnpm generate:workshop-catalog`, one file per Router model.
// A collection rather than one committed blob so a model change is a diff on
// that model, and so this schema is the only place the shape is written down.
const workshopModels = defineCollection({
  loader: glob({
    base: './src/content/workshop-models',
    pattern: '**/*.json',
    generateId: ({ entry }) => entry.replace(/\.json$/, '')
  }),
  schema: workshopModelSchema
})

export const collections = { customers, faq, workshopModels }
