name: Post Release Summary Comment
description: Post or update a PR comment summarizing release links with diff, derived versions, and optional extras.
author: ComfyUI Frontend Team

inputs:
  issue-number:
    description: Pull request number to comment on
    required: true
  version_file:
    description: Path to the JSON file containing the current version (relative to repo root)
    required: true
  marker:
    description: Override comment marker prefix (auto-derived when omitted)
    default: ''
  title:
    description: Override comment title
    default: ''
  message:
    description: Override message beneath the links block
    default: ''
  links:
    description: |
      Optional newline separated list of extra links in the format `Label|URL`.
      `{{version}}` and `{{prev_version}}` placeholders are substituted automatically.
      Leave blank to use the default set for the version file.
    default: ''
  changes_heading:
    description: Override the heading shown before the changes section
    default: ''
  repo:
    description: Repository slug to use for diff links
    default: ${{ github.repository }}

outputs:
  prev_version:
    description: Previous version derived from the parent commit
    value: ${{ steps.build.outputs.prev_version }}

runs:
  using: composite
  steps:
    - name: Build comment body
      id: build
      shell: bash
      run: |
        set -euo pipefail

        VERSION_FILE="${{ inputs.version_file }}"
        MARKER_INPUT="${{ inputs.marker }}"
        TITLE_INPUT="${{ inputs.title }}"
        MESSAGE_INPUT="${{ inputs.message }}"
        LINKS_INPUT="${{ inputs.links }}"
        REPO="${{ inputs.repo }}"
        CHANGES_INPUT="${{ inputs.changes_heading }}"

        if [[ -z "$VERSION_FILE" ]]; then
          echo '::error::version_file input is required' >&2
          exit 1
        fi

        PREV_JSON=$(git show HEAD^1:"$VERSION_FILE" 2>/dev/null || true)
        if [[ -z "$PREV_JSON" ]]; then
          echo "::error::Unable to read $VERSION_FILE from parent commit" >&2
          exit 1
        fi
        PREV_VERSION=$(printf '%s' "$PREV_JSON" | node -pe "const data = JSON.parse(require('fs').readFileSync(0, 'utf8')); if (!data.version) { process.exit(1); } data.version")
        if [[ -z "$PREV_VERSION" ]]; then
          echo "::error::Unable to determine previous version from $VERSION_FILE" >&2
          exit 1
        fi

        NEW_VERSION=$(node -pe "const fs=require('fs');const data=JSON.parse(fs.readFileSync(process.argv[1],'utf8'));if(!data.version){process.exit(1);}data.version" "$VERSION_FILE")
        if [[ -z "$NEW_VERSION" ]]; then
          echo "::error::Unable to determine current version from $VERSION_FILE" >&2
          exit 1
        fi

        DEFAULT_MARKER='release-summary'
        DEFAULT_TITLE='Release Summary'
        DEFAULT_MESSAGE='Publish jobs finished successfully. Feel free to extend the section below with release notes.'
        DEFAULT_LINKS=''

        case "$VERSION_FILE" in
          package.json)
            DEFAULT_TITLE='Release Artifacts Ready'
            DEFAULT_LINKS=$'PyPI|https://pypi.org/project/comfyui-frontend-package/{{version}}/\n''npm types|https://npm.im/@comfyorg/comfyui-frontend-types@{{version}}'
            ;;
          apps/desktop-ui/package.json)
            DEFAULT_TITLE='Desktop UI Publish Complete'
            DEFAULT_MARKER='desktop-release-summary'
            DEFAULT_LINKS='npm desktop UI|https://npm.im/@comfyorg/desktop-ui@{{version}}'
            ;;
        esac

        MARKER="$MARKER_INPUT"
        [[ -z "$MARKER" ]] && MARKER="$DEFAULT_MARKER"

        TITLE="$TITLE_INPUT"
        [[ -z "$TITLE" ]] && TITLE="$DEFAULT_TITLE"

        MESSAGE="$MESSAGE_INPUT"
        [[ -z "$MESSAGE" ]] && MESSAGE="$DEFAULT_MESSAGE"

        LINKS_VALUE="$LINKS_INPUT"
        [[ -z "$LINKS_VALUE" ]] && LINKS_VALUE="$DEFAULT_LINKS"

        CHANGES_HEADING="$CHANGES_INPUT"
        [[ -z "$CHANGES_HEADING" ]] && CHANGES_HEADING='## Changes'

        DIFF_PREFIX='v'
        DIFF_LABEL='Diff'
        DIFF_URL="https://github.com/${REPO}/compare/${DIFF_PREFIX}${PREV_VERSION}...${DIFF_PREFIX}${NEW_VERSION}"
        COMMENT_FILE=$(mktemp)

        {
          printf '<!--%s:%s%s-->\n' "$MARKER" "$DIFF_PREFIX" "$NEW_VERSION"
          printf '## %s\n\n' "$TITLE"
          printf '- %s: [%s%s...%s%s](%s)\n' "$DIFF_LABEL" "$DIFF_PREFIX" "$PREV_VERSION" "$DIFF_PREFIX" "$NEW_VERSION" "$DIFF_URL"

          while IFS= read -r RAW_LINE; do
            LINE=$(printf '%s' "$RAW_LINE" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            [[ -z "$LINE" ]] && continue
            if [[ "$LINE" != *"|"* ]]; then
              echo "::warning::Skipping malformed link entry: $LINE" >&2
              continue
            fi
            LABEL=${LINE%%|*}
            URL_TEMPLATE=${LINE#*|}
            URL=${URL_TEMPLATE//\{\{version\}\}/$NEW_VERSION}
            URL=${URL_TEMPLATE//\{\{prev_version\}\}/$PREV_VERSION}
            printf '- %s: %s\n' "$LABEL" "$URL"
          done <<< "$LINKS_VALUE"

          if [[ -n "$MESSAGE" ]]; then
            printf '\n%s\n' "$MESSAGE"
          fi

          if [[ -n "$CHANGES_HEADING" ]]; then
            printf '\n%s\n' "$CHANGES_HEADING"
          fi
        } > "$COMMENT_FILE"

        {
          echo "body<<'EOF'"
          cat "$COMMENT_FILE"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        echo "prev_version=$PREV_VERSION" >> "$GITHUB_OUTPUT"
        echo "marker_search=<!--$MARKER:" >> "$GITHUB_OUTPUT"
        echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

    - name: Find existing comment
      id: find
      uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
      with:
        issue-number: ${{ inputs.issue-number }}
        comment-author: github-actions[bot]
        body-includes: ${{ steps.build.outputs.marker_search }}

    - name: Post or update comment
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
      with:
        issue-number: ${{ inputs.issue-number }}
        comment-id: ${{ steps.find.outputs.comment-id }}
        body: ${{ steps.build.outputs.body }}
        edit-mode: replace
