name: Post Release Summary Comment
description: Post or update a PR comment summarizing release links with diff, derived versions, and optional extras.
author: ComfyUI Frontend Team

inputs:
  issue-number:
    description: Pull request number to comment on
    required: true
  version_file:
    description: Path to the JSON file containing the current version (relative to repo root)
    required: true
  new_version:
    description: Current version string (e.g., 1.2.3)
    required: true
  marker:
    description: Comment marker prefix used for idempotent updates
    default: release-summary
  title:
    description: Title line displayed in the comment (without markdown heading markers)
    default: "Release Summary"
  message:
    description: Optional paragraph inserted before the changes heading
    default: ''
  links:
    description: |
      Optional newline separated list of extra links in the format `Label|URL`.
      `{{version}}` and `{{prev_version}}` placeholders are substituted automatically.
    default: ''
  changes_heading:
    description: Heading shown after the summary (set empty to omit)
    default: "## Changes"
  repo:
    description: Repository slug to use for diff links
    default: ${{ github.repository }}

outputs:
  prev_version:
    description: Previous version derived from the parent commit
    value: ${{ steps.build.outputs.prev_version }}

runs:
  using: composite
  steps:
    - name: Build comment body
      id: build
      shell: bash
      run: |
        set -euo pipefail

        VERSION_FILE="${{ inputs.version_file }}"
        NEW_VERSION="${{ inputs.new_version }}"
        MARKER="${{ inputs.marker }}"
        TITLE="${{ inputs.title }}"
        MESSAGE="${{ inputs.message }}"
        LINKS_INPUT="${{ inputs.links }}"
        REPO="${{ inputs.repo }}"
        CHANGES_HEADING="${{ inputs.changes_heading }}"

        if [[ -z "$VERSION_FILE" ]]; then
          echo '::error::version_file input is required' >&2
          exit 1
        fi
        if [[ -z "$NEW_VERSION" ]]; then
          echo '::error::new_version input is required' >&2
          exit 1
        fi

        PREV_JSON=$(git show HEAD^1:"$VERSION_FILE" 2>/dev/null || true)
        if [[ -z "$PREV_JSON" ]]; then
          echo "::error::Unable to read $VERSION_FILE from parent commit" >&2
          exit 1
        fi
        PREV_VERSION=$(printf '%s' "$PREV_JSON" | node -pe "const data = JSON.parse(require('fs').readFileSync(0, 'utf8')); if (!data.version) { process.exit(1); } data.version")
        if [[ -z "$PREV_VERSION" ]]; then
          echo "::error::Unable to determine previous version from $VERSION_FILE" >&2
          exit 1
        fi

        DIFF_PREFIX='v'
        DIFF_LABEL='Diff'
        DIFF_URL="https://github.com/${REPO}/compare/${DIFF_PREFIX}${PREV_VERSION}...${DIFF_PREFIX}${NEW_VERSION}"
        COMMENT_FILE=$(mktemp)

        {
          printf '<!--%s:%s%s-->\n' "$MARKER" "$DIFF_PREFIX" "$NEW_VERSION"
          printf '## %s\n\n' "$TITLE"
          printf '- %s: [%s%s...%s%s](%s)\n' "$DIFF_LABEL" "$DIFF_PREFIX" "$PREV_VERSION" "$DIFF_PREFIX" "$NEW_VERSION" "$DIFF_URL"

          while IFS= read -r RAW_LINE; do
            LINE=$(printf '%s' "$RAW_LINE" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            [[ -z "$LINE" ]] && continue
            if [[ "$LINE" != *"|"* ]]; then
              echo "::warning::Skipping malformed link entry: $LINE" >&2
              continue
            fi
            LABEL=${LINE%%|*}
            URL_TEMPLATE=${LINE#*|}
            URL=${URL_TEMPLATE//\{\{version\}\}/$NEW_VERSION}
            URL=${URL//\{\{prev_version\}\}/$PREV_VERSION}
            printf '- %s: %s\n' "$LABEL" "$URL"
          done <<< "$LINKS_INPUT"

          if [[ -n "$MESSAGE" ]]; then
            printf '\n%s\n' "$MESSAGE"
          fi

          if [[ -n "$CHANGES_HEADING" ]]; then
            printf '\n%s\n' "$CHANGES_HEADING"
          fi
        } > "$COMMENT_FILE"

        {
          echo "body<<'EOF'"
          cat "$COMMENT_FILE"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        echo "prev_version=$PREV_VERSION" >> "$GITHUB_OUTPUT"
        echo "marker_search=<!--$MARKER:" >> "$GITHUB_OUTPUT"

    - name: Find existing comment
      id: find
      uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad
      with:
        issue-number: ${{ inputs.issue-number }}
        comment-author: github-actions[bot]
        body-includes: ${{ steps.build.outputs.marker_search }}

    - name: Post or update comment
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
      with:
        issue-number: ${{ inputs.issue-number }}
        comment-id: ${{ steps.find.outputs.comment-id }}
        body: ${{ steps.build.outputs.body }}
        edit-mode: replace
