import type { Locale } from '../../../i18n/translations'

const COPY = {
  title: ['Creative direction', '创作指导'],
  guidance: [
    'These choices guide the prompt. Colors and lighting are not exact color transfer or physical relighting.',
    '这些选项用于指导提示词，并非精确的色彩迁移或物理重新打光。'
  ],
  apply: ['Apply', '应用'],
  cancel: ['Cancel', '取消'],
  reset: ['Reset draft', '重置草稿'],
  genre: ['Genre', '类型'],
  era: ['Era', '年代'],
  tempo: ['Video tempo', '视频节奏'],
  movements: ['Movement sequence', '镜头运动顺序'],
  search: ['Search movements', '搜索镜头运动'],
  empty: ['No matching movements', '没有匹配的镜头运动'],
  earlier: ['Move earlier', '前移'],
  later: ['Move later', '后移'],
  remove: ['Remove', '移除'],
  clear: ['Clear sequence', '清空顺序'],
  palette: ['Custom palette', '自定义调色板'],
  addColor: ['Add color', '添加颜色'],
  color: ['Color', '颜色'],
  main: ['Main color', '主色'],
  noMain: ['No main color', '无主色'],
  harmony: ['Color harmony', '色彩和谐'],
  buildHarmony: ['Build from first color', '根据首个颜色生成'],
  sample: ['Sample colors from image', '从图像采样颜色'],
  lights: ['Custom lighting', '自定义灯光'],
  addLight: ['Add light', '添加灯光'],
  position: ['Position', '位置'],
  brightness: ['Brightness', '亮度'],
  diffusion: ['Diffusion', '柔光程度'],
  presets: ['Saved presets in this browser', '此浏览器中的已存预设'],
  presetName: ['Preset name', '预设名称'],
  save: ['Save draft as preset', '将草稿存为预设'],
  load: ['Load into draft', '加载到草稿'],
  saved: [
    'Preset saved. Apply to use it in the scene.',
    '预设已保存。应用后才能用于场景。'
  ],
  error: [
    'Check the colors and settings, then try again.',
    '请检查颜色和设置后重试。'
  ],
  storageError: [
    'This browser could not save the preset.',
    '此浏览器无法保存预设。'
  ],
  sampleError: [
    'Choose a PNG, JPEG or WebP image up to 10 MB.',
    '请选择不超过 10 MB 的 PNG、JPEG 或 WebP 图像。'
  ],
  preview: ['Added prompt guidance', '新增的提示词指导'],
  none: ['No additional guidance', '无新增指导'],
  auto: ['Auto', '自动'],
  drama: ['Drama', '剧情'],
  noir: ['Noir', '黑色电影'],
  comedy: ['Comedy', '喜剧'],
  horror: ['Horror', '恐怖'],
  action: ['Action', '动作'],
  adventure: ['Adventure', '冒险'],
  epic: ['Epic', '史诗'],
  documentary: ['Documentary', '纪录片'],
  '1960s': ['1960s', '1960 年代'],
  '1970s': ['1970s', '1970 年代'],
  '1980s': ['1980s', '1980 年代'],
  '1990s': ['1990s', '1990 年代'],
  '2000s': ['2000s', '2000 年代'],
  '2020s': ['2020s', '2020 年代'],
  single: ['Single shot', '连续镜头'],
  calm: ['Calm', '平静'],
  dynamic: ['Dynamic', '动感'],
  chaotic: ['Chaotic', '混乱'],
  front: ['Front', '正面'],
  left: ['Left', '左侧'],
  right: ['Right', '右侧'],
  back: ['Back', '背面'],
  top: ['Above', '上方'],
  bottom: ['Below', '下方'],
  analogous: ['Analogous', '邻近色'],
  complementary: ['Complementary', '互补色'],
  split: ['Split complementary', '分裂互补色'],
  triad: ['Triadic', '三等分色'],
  tetradic: ['Tetradic', '四配色'],
  square: ['Square', '正方形配色'],
  monochrome: ['Monochromatic', '单色'],
  static: ['Static shot', '固定镜头'],
  'dolly-in': ['Dolly in', '向前推进'],
  'dolly-out': ['Dolly out', '向后拉远'],
  'pan-left': ['Pan left', '向左摇镜'],
  'pan-right': ['Pan right', '向右摇镜'],
  'tilt-up': ['Tilt up', '向上摇镜'],
  'tilt-down': ['Tilt down', '向下摇镜'],
  tracking: ['Tracking', '跟拍'],
  'side-tracking': ['Side tracking', '侧面跟拍'],
  handheld: ['Handheld', '手持镜头'],
  'rack-focus': ['Rack focus', '焦点转移'],
  'drone-orbit': ['Drone orbit', '无人机环绕'],
  'arc-left': ['Arc left', '向左弧线运动'],
  'arc-right': ['Arc right', '向右弧线运动'],
  'crane-up': ['Crane up', '摇臂升起'],
  'crane-down': ['Crane down', '摇臂下降'],
  'pedestal-up': ['Pedestal up', '垂直升起'],
  'pedestal-down': ['Pedestal down', '垂直下降'],
  'truck-left': ['Truck left', '向左平移'],
  'truck-right': ['Truck right', '向右平移'],
  'slider-left': ['Slider left', '滑轨向左'],
  'slider-right': ['Slider right', '滑轨向右'],
  'slow-zoom-in': ['Slow zoom in', '缓慢变焦推近'],
  'slow-zoom-out': ['Slow zoom out', '缓慢变焦拉远'],
  'dolly-zoom': ['Dolly zoom', '滑动变焦'],
  'whip-pan': ['Whip pan', '快速甩镜'],
  'crush-zoom': ['Crush zoom', '快速变焦推近'],
  'aerial-pullback': ['Aerial pullback', '航拍后拉'],
  helicopter: ['Helicopter shot', '直升机镜头'],
  pov: ['POV', '第一人称视角'],
  snorricam: ['Snorricam', '主体固定机位'],
  'robot-arm': ['Robot arm', '机械臂'],
  'bullet-time': ['Bullet time', '子弹时间']
} as const
export type CreativeCopyKey = keyof typeof COPY
export function tcCreative(
  key: CreativeCopyKey,
  locale: Locale = 'en'
): string {
  return COPY[key][locale === 'zh-CN' ? 1 : 0]
}
