/**
 * The translation API every page and component calls.
 *
 * It reads pre-resolved dictionaries — one flat `key -> string` file per locale,
 * generated by `pnpm i18n:build-resolved` — rather than the layered source in
 * `source.ts`. Two things follow from that, and both are the point:
 *
 * 1. A visitor downloads only their own language. The layered source holds every
 *    locale in one module, so shipping it meant an English reader fetched 80 KB
 *    gzipped of Chinese, and filling Japanese would have added ~85 KB more for
 *    everyone, on every page.
 * 2. There is no fallback chain in the browser. A resolved dictionary already
 *    answers every key, so no second locale has to be present to back it up.
 *
 * The import path is unchanged, so no component, page or data file needed
 * editing when this moved.
 *
 * `import.meta.glob` is lazy on purpose: eager loading would inline all three
 * dictionaries into one chunk and undo the split.
 */
import { DEFAULT_LOCALE, LOCALE_CODES } from '../config/locales'
import type { Locale } from '../config/locales'
import type { TranslationLayer } from './pipeline/types'
import type { LocalizedText, TranslationKey } from './source'

const dictionaryLoaders = import.meta.glob<TranslationLayer>(
  './resolved/*.json',
  { import: 'default' }
)

function isLocale(value: string): value is Locale {
  return (LOCALE_CODES as readonly string[]).includes(value)
}

/**
 * The locale this JavaScript is running for.
 *
 * In a browser that is the page's own `<html lang>`, which `BaseLayout` writes
 * from the same `Locale` union, so exactly one dictionary is ever fetched.
 *
 * There is no browser case where a component asks for a different locale than
 * its page: all 61 calls that name a locale literally are in `.astro` files,
 * which run here on the server. `t()` still takes a locale so those keep
 * working, and so a mismatch would surface as a missing key rather than as
 * silently wrong text.
 */
function documentLocale(): Locale {
  const lang = document.documentElement.lang
  return isLocale(lang) ? lang : DEFAULT_LOCALE
}

async function loadDictionary(locale: Locale): Promise<TranslationLayer> {
  const load = dictionaryLoaders[`./resolved/${locale}.json`]
  if (!load) {
    throw new Error(
      `No resolved dictionary for locale "${locale}". Run ` +
        `\`pnpm i18n:build-resolved\` — src/i18n/resolved/${locale}.json is missing.`
    )
  }
  return load()
}

/**
 * Only the production browser bundle restricts itself to one locale.
 *
 * Everywhere else needs all of them in one process: `astro build` renders every
 * language server-side, and component tests mount the same component at several
 * locales in a single file. Both would break on a single dictionary, and
 * neither ships to anyone.
 *
 * `import.meta.env` is safe here in a way it is not in `source.ts`: nothing
 * loads this module under `tsx`, and `resolved.test.ts` fails if that changes.
 */
const PRODUCTION_BROWSER =
  import.meta.env.PROD &&
  !import.meta.env.SSR &&
  typeof document !== 'undefined'

async function loadDictionaries(): Promise<Map<Locale, TranslationLayer>> {
  const wanted = PRODUCTION_BROWSER ? [documentLocale()] : LOCALE_CODES

  const loaded = await Promise.all(
    wanted.map(
      async (locale): Promise<[Locale, TranslationLayer]> => [
        locale,
        await loadDictionary(locale)
      ]
    )
  )

  return new Map(loaded)
}

const dictionaries = await loadDictionaries()

/**
 * Any loaded dictionary, for questions that are about keys rather than text.
 *
 * It cannot be "the English one": in a browser on a Japanese page, English is
 * deliberately not loaded. Every dictionary carries the same keys in the same
 * order — `resolved.test.ts` asserts both — so any of them answers.
 */
function keySpace(): TranslationLayer {
  const first = dictionaries.values().next()
  if (first.done) throw new Error('No resolved dictionary was loaded.')
  return first.value
}

function dictionaryFor(locale: Locale): TranslationLayer {
  const dictionary = dictionaries.get(locale)
  if (!dictionary) {
    // Loud rather than silent. Falling back to the page's own locale would
    // render text the server did not, and hydration would paper over it.
    throw new Error(
      `t() asked for locale "${locale}" on a "${documentLocale()}" page. A ` +
        `component may only render its own page's locale in the browser.`
    )
  }
  return dictionary
}

export function t(
  key: TranslationKey,
  locale: Locale = DEFAULT_LOCALE
): string {
  return dictionaryFor(locale)[key]
}

/**
 * Every key, in the order `source.ts` declares them.
 *
 * The order is load-bearing: `LegalContentSection.vue` walks this list to decide
 * the order of the sections it renders. `buildResolvedDictionary` writes the
 * dictionaries in source order and a test asserts it, so reading the keys back
 * off one preserves it.
 */
export const translationKeys = Object.keys(keySpace()) as TranslationKey[]

export function hasKey(key: string): boolean {
  return key in keySpace()
}

export type { Locale, LocalizedText, TranslationKey }
