import {
  comfyPageFixture as test,
  comfyExpect as expect
} from '../../fixtures/ComfyPage'

test.describe('QueueClearHistoryDialog', { tag: '@ui' }, () => {
  test.beforeEach(async ({ comfyPage }) => {
    await comfyPage.setup()

    // Expand the queue overlay so the JobHistoryActionsMenu is visible
    await comfyPage.queuePanel.overlayToggle.click()
  })

  test('Dialog opens from queue panel history actions menu', async ({
    comfyPage
  }) => {
    await comfyPage.queuePanel.openClearHistoryDialog()

    await expect(comfyPage.queuePanel.clearHistoryDialog.root).toBeVisible()
  })

  test('Dialog shows confirmation message with title, description, and assets note', async ({
    comfyPage
  }) => {
    await comfyPage.queuePanel.openClearHistoryDialog()

    const dialog = comfyPage.queuePanel.clearHistoryDialog
    await expect(dialog.root).toBeVisible()

    // Verify title
    await expect(
      dialog.root.getByText('Clear your job queue history?')
    ).toBeVisible()

    // Verify description
    await expect(
      dialog.root.getByText(
        'All the finished or failed jobs below will be removed from this Job queue panel.'
      )
    ).toBeVisible()

    // Verify assets note (locale uses Unicode RIGHT SINGLE QUOTATION MARK \u2019)
    await expect(
      dialog.root.getByText(
        'Assets generated by these jobs won\u2019t be deleted and can always be viewed from the assets panel.'
      )
    ).toBeVisible()
  })

  test('Cancel button closes dialog without clearing history', async ({
    comfyPage
  }) => {
    await comfyPage.queuePanel.openClearHistoryDialog()

    const dialog = comfyPage.queuePanel.clearHistoryDialog
    await expect(dialog.root).toBeVisible()

    // Intercept the clear API call — it should NOT be called
    let clearCalled = false
    await comfyPage.page.route('**/api/history', (route) => {
      if (route.request().method() === 'POST') {
        clearCalled = true
      }
      return route.continue()
    })

    await dialog.cancelButton.click()

    await expect(dialog.root).not.toBeVisible()
    expect(clearCalled).toBe(false)

    await comfyPage.page.unroute('**/api/history')
  })

  test('Close (X) button closes dialog without clearing history', async ({
    comfyPage
  }) => {
    await comfyPage.queuePanel.openClearHistoryDialog()

    const dialog = comfyPage.queuePanel.clearHistoryDialog
    await expect(dialog.root).toBeVisible()

    // Intercept the clear API call — it should NOT be called
    let clearCalled = false
    await comfyPage.page.route('**/api/history', (route) => {
      if (route.request().method() === 'POST') {
        clearCalled = true
      }
      return route.continue()
    })

    await dialog.closeButton.click()

    await expect(dialog.root).not.toBeVisible()
    expect(clearCalled).toBe(false)

    await comfyPage.page.unroute('**/api/history')
  })

  test('Confirm clears queue history and closes dialog', async ({
    comfyPage
  }) => {
    await comfyPage.queuePanel.openClearHistoryDialog()

    const dialog = comfyPage.queuePanel.clearHistoryDialog
    await expect(dialog.root).toBeVisible()

    // Intercept the clear API call to verify it is made
    const clearPromise = comfyPage.page.waitForRequest(
      (req) => req.url().includes('/api/history') && req.method() === 'POST'
    )

    await dialog.clearButton.click()

    // Verify the API call was made
    const request = await clearPromise
    expect(request.postDataJSON()).toEqual({ clear: true })

    await expect(dialog.root).not.toBeVisible()
  })

  test('Dialog state resets after close and reopen', async ({ comfyPage }) => {
    // Open and cancel
    await comfyPage.queuePanel.openClearHistoryDialog()
    const dialog = comfyPage.queuePanel.clearHistoryDialog
    await expect(dialog.root).toBeVisible()
    await dialog.cancelButton.click()
    await expect(dialog.root).not.toBeVisible()

    // Reopen — dialog should be fresh (Clear button enabled, not stuck)
    await comfyPage.queuePanel.openClearHistoryDialog()
    await expect(dialog.root).toBeVisible()

    await expect(dialog.clearButton).toBeVisible()
    await expect(dialog.clearButton).toBeEnabled()
  })
})