import type { UseCase, WorkshopModel } from '../../config/models-catalogue'
import { useCaseFor } from '../../config/models-catalogue'
import { routerModelSlugAliases } from '../../config/workshop-browse-content'
import templateModelJoin from '../../data/templateModelJoin.json'
import type { HubTemplate } from './types'

// Generated by `pnpm hub:generate-join` for the templates that name their
// model only in the file name, and only where the two agree on the medium.
const JOINED_SLUG = templateModelJoin as Record<string, string>

const ROUTER_SLUG_BY_LEGACY_FAMILY: Readonly<Record<string, string>> = {
  beeble: 'beeble--switchx-image-edit',
  'bria-ai': 'bria--fibo-image-edit',
  'gemini-image': 'vertexai--gemini-2.5-flash-image',
  'grok-imagine': 'xai--grok-imagine-video',
  happyhorse1: 'wan--happyhorse-text-to-video',
  'kling-ai': 'kling--v3',
  'ltx-2': 'ltx--text-to-video-v2',
  'luma-dream-machine': 'luma--ray-2-text-to-video',
  'magnific-ai': 'freepik--magnific-upscaler-creative',
  'meshy-7': 'meshy--text-to-model',
  'meshy-ai': 'meshy--text-to-model',
  minimax: 'minimax--hailuo-03',
  'nano-banana': 'vertexai--gemini-nano-banana-2',
  'openai-dall-e': 'openai--dall-e-3',
  'rodin-3d': 'rodin--gen2',
  'seedance-2': 'byteplus--seedance-2-5-text-to-video',
  'seedance-bytedance': 'byteplus--seedance-1-0-lite-text-to-video',
  sync: 'synclabs--lip-sync',
  'topaz-labs': 'topaz--image-enhance',
  'tripo-3d': 'tripo--text-to-model',
  vidu: 'vidu--text-to-video-q3-pro'
}

const normalize = (value: string) =>
  value.toLowerCase().replace(/[^a-z0-9]/g, '')

// The catalogue names its models as free text ("Wan2.7", "FLUX 3 Video"), so
// only an exact match after normalising is safe: a substring match sends a
// FLUX video workflow to an image playground.
export function modelNamedBy(
  template: HubTemplate,
  models: readonly WorkshopModel[]
): WorkshopModel | undefined {
  if (!template.tags.includes('API')) return undefined
  const names = template.models.map(normalize)
  return models.find((model) => names.includes(normalize(model.name)))
}

export function partnerModelFor(
  template: HubTemplate,
  models: readonly WorkshopModel[]
): WorkshopModel | undefined {
  const legacy = JOINED_SLUG[template.name]
  const sourceSlug = legacy ? ROUTER_SLUG_BY_LEGACY_FAMILY[legacy] : undefined
  const joined = sourceSlug
    ? (routerModelSlugAliases.get(sourceSlug) ?? sourceSlug)
    : undefined
  return (
    modelNamedBy(template, models) ??
    (template.tags.includes('API')
      ? models.find((model) => model.slug === joined)
      : undefined)
  )
}

// What the workflow does, in the vocabulary the models catalogue already uses.
// The index's own mediaType describes the thumbnail, not the output, so the
// task tags decide; the broader tags only break a tie.
const TASK_TAGS: Readonly<Record<string, UseCase>> = {
  'Image to 3D': '3d',
  'Text to Model': '3d',
  'Image to Model': '3d',
  'Text to Speech': 'audio',
  TTS: 'audio',
  'Speech to Text': 'audio',
  'Voice Cloning': 'audio',
  'Text to Music': 'audio',
  'Text to Audio': 'audio',
  'Audio Editing': 'audio',
  'Text Generation': 'text',
  'Video Edit': 'edit-videos',
  'Video to Video': 'edit-videos',
  'Video Extend': 'edit-videos',
  'Video Upscale': 'edit-videos',
  'Frame Interpolation': 'edit-videos',
  'Image to Video': 'animate-images',
  FLF2V: 'animate-images',
  'Lip Sync': 'animate-images',
  'Audio to Video': 'animate-images',
  'Character Replacement': 'animate-images',
  'Text to Video': 'generate-videos',
  'Reference to Video': 'generate-videos',
  'Image Edit': 'edit-images',
  Inpainting: 'edit-images',
  Outpainting: 'edit-images',
  'Image Upscale': 'edit-images',
  Relight: 'edit-images',
  'Remove Background': 'edit-images',
  'Style Transfer': 'edit-images',
  'Layer Decompose': 'edit-images',
  'Element Segmentation': 'edit-images',
  'Virtual Try-On': 'edit-images',
  'Text to Image': 'generate-images'
}

// Motion control animates a subject, which the medium alone cannot say. What
// is left names a conditioning method — ControlNet, a pose map, a style
// reference — so it conditions a generation of whatever the workflow outputs.
const TASK_FALLBACK_TAGS: Readonly<Record<string, UseCase>> = {
  'Motion Control': 'animate-images'
}

const GENERATED_MEDIUM: Readonly<Record<string, UseCase>> = {
  image: 'generate-images',
  video: 'generate-videos',
  audio: 'audio',
  '3d': '3d'
}

function fromTags(
  tags: readonly string[],
  table: Readonly<Record<string, UseCase>>
): UseCase | undefined {
  for (const tag of Object.keys(table)) {
    if (tags.includes(tag)) return table[tag]
  }
  return undefined
}

export function useCaseForTemplate(
  template: HubTemplate,
  models: readonly WorkshopModel[]
): UseCase | undefined {
  const partner = partnerModelFor(template, models)
  return (
    fromTags(template.tags, TASK_TAGS) ??
    (partner ? useCaseFor(partner) : undefined) ??
    fromTags(template.tags, TASK_FALLBACK_TAGS) ??
    GENERATED_MEDIUM[template.mediaType]
  )
}
