import { z } from 'zod'

/**
 * Schema for a subgraph identifier (RFC 4122 UUID).
 *
 * Subgraph IDs are generated by `createUuidv4()` and persisted in workflow
 * JSON as `z.string().uuid()` (see workflowSchema.ts). They are also embedded
 * in the URL hash for in-app navigation; hash values are untrusted input and
 * must be validated before use as a lookup key.
 */
export const zSubgraphId = z.string().uuid()

type SubgraphId = z.infer<typeof zSubgraphId>

export function isValidSubgraphId(value: unknown): value is SubgraphId {
  return zSubgraphId.safeParse(value).success
}
