import { z } from 'astro/zod'

import { USE_CASES } from '@/config/models-catalogue'
import generated from './open-weight-models.generated.json' with { type: 'json' }

const openWeightModelSchema = z.object({
  slug: z.string(),
  name: z.string(),
  provider: z.string().optional(),
  modality: z.enum(['image', 'video', 'audio', '3d']),
  useCase: z.enum(USE_CASES),
  tasks: z.array(z.enum(['edit', 'upscale'])).readonly(),
  thumbnailUrl: z.string()
})

/**
 * A published model page for weights people download and run in ComfyUI,
 * described by the template its page takes its artwork from.
 * Generated by `scripts/generate-open-weight-models.ts`.
 */
export type OpenWeightModel = Readonly<z.output<typeof openWeightModelSchema>>
export type OpenWeightModality = OpenWeightModel['modality']
export type OpenWeightTask = OpenWeightModel['tasks'][number]

export const OPEN_WEIGHT_MODELS: readonly OpenWeightModel[] = z
  .array(openWeightModelSchema)
  .parse(generated)
