import { WORKSHOP_INCLUDED } from 'astro:env/client'
import { z } from 'astro/zod'

import { modelFileHref } from '@/lib/workshop/model-file-href'
import type { UseCase } from '@/config/models-catalogue'
import { USE_CASES } from '@/config/models-catalogue'
import type { ModelTab } from './model-tabs'
import { openWeightInTab } from './model-tabs'
import generated from './open-weight-models.generated.json' with { type: 'json' }

const openWeightModelSchema = z.object({
  slug: z.string(),
  name: z.string(),
  provider: z.string().optional(),
  modality: z.enum(['image', 'video', 'audio', '3d']),
  useCase: z.enum(USE_CASES),
  tasks: z.array(z.enum(['edit', 'upscale'])).readonly(),
  thumbnailUrl: z.string()
})

/**
 * A published model page for weights people download and run in ComfyUI,
 * described by the template its page takes its artwork from.
 * Generated by `scripts/generate-open-weight-models.ts`.
 */
export type OpenWeightModel = Readonly<z.output<typeof openWeightModelSchema>>
export type OpenWeightModality = OpenWeightModel['modality']
export type OpenWeightTask = OpenWeightModel['tasks'][number]

export const OPEN_WEIGHT_MODELS: readonly OpenWeightModel[] = z
  .array(openWeightModelSchema)
  .parse(generated)

export function openWeightHref(model: Pick<OpenWeightModel, 'slug'>): string {
  return modelFileHref(model.slug, WORKSHOP_INCLUDED)
}

export function filterOpenWeightModels(
  list: readonly OpenWeightModel[],
  {
    query = '',
    useCases = [],
    tab = 'all',
    byName = false
  }: {
    query?: string
    useCases?: readonly UseCase[]
    tab?: ModelTab
    byName?: boolean
  }
): OpenWeightModel[] {
  const needle = query.trim().toLowerCase()
  const matches = list.filter(
    (model) =>
      openWeightInTab(model, tab) &&
      (useCases.length === 0 || useCases.includes(model.useCase)) &&
      (needle === '' ||
        [model.name, model.provider ?? '', model.useCase.replaceAll('-', ' ')]
          .join(' ')
          .toLowerCase()
          .includes(needle))
  )
  return byName
    ? matches.toSorted((a, b) => a.name.localeCompare(b.name))
    : matches
}
