/**
 * Maps HuggingFace repo ids to the compatible base model(s) for any asset
 * sourced from that repo. Used as a fallback when the asset itself doesn't
 * carry a [[base_model]] field in its metadata.
 *
 * Generated one-shot from temp/scripts/scrape-base-models.py + emit-base-model-overrides.mjs
 * by scraping HuggingFace cardData / tags / READMEs for every unique repo_id
 * in the cloud asset list. Hand-edit entries that look wrong — the regenerator
 * is destructive.
 *
 * Repos without a confident match are intentionally omitted; the UI falls
 * back to an "Unknown base model" bucket for those.
 */
const BASE_MODEL_OVERRIDES: Readonly<Record<string, readonly string[]>> =
  Object.freeze({
    '100percentrobot/LTX-2.3-Audio-Reactive-LORA': ['LTX 2.3'],
    '1038lab/sam3': ['SAM 3'],
    'AInVFX/SeedVR2_comfyUI': ['SeedVR2'],
    'alibaba-pai/Qwen-Image-2512-Fun-Controlnet-Union': ['Qwen Image'],
    'alibaba-pai/Z-Image-Turbo-Fun-Controlnet-Union': ['Z-Image'],
    'alibaba-pai/Z-Image-Turbo-Fun-Controlnet-Union-2.1': ['Z-Image'],
    'Alissonerdx/BFS-Best-Face-Swap-Video': ['LTX 2.3'],
    'Alissonerdx/LTX-LoRAs': ['LTX 2.3'],
    'alvdansen/illustration-1.0-qwen-image': ['Qwen Image'],
    'AviadDahan/ID-LoRA-CelebVHQ': ['LTX Video'],
    'AviadDahan/ID-LoRA-TalkVid': ['LTX Video'],
    'bionicman69/StarTrek_TNG_Style_LTX23': ['LTX 2.3'],
    'black-forest-labs/FLUX.1-Canny-dev': ['Flux.1 dev'],
    'black-forest-labs/FLUX.1-Depth-dev-lora': ['Flux.1 dev'],
    'black-forest-labs/FLUX.1-dev': ['Flux.1 dev'],
    'black-forest-labs/FLUX.1-Fill-dev': ['Flux.1 dev'],
    'black-forest-labs/FLUX.1-Kontext-dev': ['Flux.1 Kontext'],
    'black-forest-labs/FLUX.1-Redux-dev': ['Flux.1 Redux'],
    'black-forest-labs/FLUX.1-schnell': ['Flux.1 Schnell'],
    'black-forest-labs/FLUX.2-klein-4b-fp8': ['Flux.2 Klein'],
    'black-forest-labs/FLUX.2-klein-9B': ['Flux.2 Klein'],
    'black-forest-labs/FLUX.2-klein-base-4b-fp8': ['Flux.2 Klein'],
    'black-forest-labs/FLUX.2-klein-base-9b-fp8': ['Flux.2 Klein'],
    'black-forest-labs/FLUX.2-small-decoder': ['Flux.2 dev'],
    'ByteDance/LatentSync-1.6': ['LatentSync'],
    'ByteDance/SDXL-Lightning': ['SDXL'],
    'ByteZSzn/Flux.2-Turbo-ComfyUI': ['Flux.2 dev'],
    'clayshoaf/Make-Wojak-2511': ['Qwen Image Edit'],
    'Comfy-Org/ace_step_1.5_ComfyUI_files': ['ACE-Step'],
    'Comfy-Org/ACE-Step_ComfyUI_repackaged': ['ACE-Step'],
    'Comfy-Org/BiRefNet': ['BiRefNet'],
    'Comfy-Org/Chroma1-HD_repackaged': ['Chroma1 HD'],
    'Comfy-Org/Chroma1-Radiance_Repackaged': ['Chroma1 Radiance'],
    'Comfy-Org/Cosmos_Predict2_repackaged': ['Cosmos'],
    'Comfy-Org/ERNIE-Image': ['ERNIE'],
    'Comfy-Org/FLUX.1-Krea-dev_ComfyUI': ['Flux.1 Krea'],
    'Comfy-Org/flux1-dev': ['Flux.1 dev'],
    'Comfy-Org/flux1-kontext-dev_ComfyUI': ['Flux.1 Kontext'],
    'Comfy-Org/flux1-schnell': ['Flux.1 Schnell'],
    'Comfy-Org/flux2-dev': ['Flux.2 dev'],
    'Comfy-Org/flux2-klein-4B': ['Flux.2 Klein'],
    'Comfy-Org/flux2-klein-9B': ['Flux.2 Klein'],
    'Comfy-Org/gemma-4': ['Gemma'],
    'Comfy-Org/HiDream-I1_ComfyUI': ['HiDream I1'],
    'Comfy-Org/HiDream-O1-Image': ['HiDream O1'],
    'Comfy-Org/HuMo_ComfyUI': ['HuMo'],
    'Comfy-Org/hunyuan3D_2.0_repackaged': ['Hunyuan 3D'],
    'Comfy-Org/hunyuan3D_2.1_repackaged': ['Hunyuan 3D'],
    'Comfy-Org/HunyuanVideo_1.5_repackaged': ['HunyuanVideo 1.5'],
    'Comfy-Org/HunyuanVideo_repackaged': ['HunyuanVideo'],
    'Comfy-Org/LongCat-Image': ['LongCat'],
    'Comfy-Org/lotus': ['Lotus'],
    'Comfy-Org/ltx-2': ['LTX 2'],
    'Comfy-Org/ltx-2.3': ['LTX 2.3'],
    'Comfy-Org/mochi_preview_repackaged': ['Mochi'],
    'Comfy-Org/MoGe': ['MoGe'],
    'Comfy-Org/NewBie-image-Exp0.1_repackaged': ['NewBie'],
    'Comfy-Org/Omnigen2_ComfyUI_repackaged': ['Omnigen'],
    'Comfy-Org/OneReward_repackaged': ['OneReward'],
    'Comfy-Org/Ovis-Image': ['Ovis'],
    'Comfy-Org/Qwen-Image_ComfyUI': ['Qwen Image'],
    'Comfy-Org/Qwen-Image-DiffSynth-ControlNets': ['Qwen Image'],
    'Comfy-Org/Qwen-Image-Edit_ComfyUI': ['Qwen Image Edit'],
    'Comfy-Org/Qwen-Image-InstantX-ControlNets': ['Qwen Image'],
    'Comfy-Org/Qwen-Image-Layered_ComfyUI': ['Qwen Image'],
    'Comfy-Org/Real-ESRGAN_repackaged': ['Real-ESRGAN'],
    'Comfy-Org/sam3.1': ['SAM 3'],
    'Comfy-Org/stable-audio-3': ['Stable Audio'],
    'Comfy-Org/stable-audio-open-1.0_repackaged': ['Stable Audio'],
    'Comfy-Org/stable-diffusion-3.5-fp8': ['SD 3.5'],
    'Comfy-Org/stable-diffusion-v1-5-archive': ['SD 1.5'],
    'Comfy-Org/USO_1.0_Repackaged': ['USO'],
    'Comfy-Org/vae-text-encorder-for-flux-klein-9b': ['Flux.1 dev'],
    'Comfy-Org/Wan_2.1_ComfyUI_repackaged': ['Wan 2.1'],
    'Comfy-Org/Wan_2.2_ComfyUI_Repackaged': ['Wan 2.2'],
    'Comfy-Org/z_image': ['Z-Image'],
    'Comfy-Org/z_image_turbo': ['Z-Image'],
    'comfyanonymous/cosmos_1.0_text_encoder_and_VAE_ComfyUI': ['Cosmos'],
    'comfyanonymous/flux_text_encoders': ['Flux.1 dev'],
    'Cseti/LTX2.3-22B_IC-LoRA-Cameraman_v1': ['LTX 2.3'],
    'depth-anything/DA3-BASE': ['Depth Anything'],
    'depth-anything/DA3-LARGE-1.1': ['Depth Anything'],
    'depth-anything/DA3-SMALL': ['Depth Anything'],
    'depth-anything/DA3METRIC-LARGE': ['Depth Anything'],
    'depth-anything/DA3MONO-LARGE': ['Depth Anything'],
    'depth-anything/Depth-Anything-V2-Large': ['Depth Anything V2'],
    'DiffSynth-Studio/Qwen-Image-Layered-Control': ['Qwen Image'],
    'DoctorDiffusion/LTX-2.3-IC-LoRA-Colorizer': ['LTX 2.3'],
    'duongve/NetaYume-Lumina-Image-2.0': ['Lumina'],
    'dx8152/Flux2-Klein-9B-Consistency': ['Flux.2 Klein'],
    'dx8152/Flux2-Klein-9B-Enhanced-Details': ['Flux.2 Klein'],
    'dx8152/Qwen-Edit-2509-Light-Migration': ['Qwen Image Edit'],
    'dx8152/Qwen-Edit-2509-Multiple-angles': ['Qwen Image Edit'],
    'dx8152/Qwen-Image-Edit-2509-Fusion': ['Qwen Image Edit'],
    'dx8152/Qwen-Image-Edit-2509-Light_restoration': ['Qwen Image Edit'],
    'dx8152/Qwen-Image-Edit-2509-Relight': ['Qwen Image Edit'],
    'dx8152/Qwen-Image-Edit-2509-White_to_Scene': ['Qwen Image Edit'],
    'enigmatic/gummycandy_qwen': ['Qwen'],
    'EQUES/qwen-image-edit-2511-lineart-interpolation': ['Qwen Image Edit'],
    'fal/flux-2-klein-4B-background-remove-lora': ['Flux.2 Klein'],
    'fal/flux-2-klein-4B-object-remove-lora': ['Flux.2 Klein'],
    'fal/flux-2-klein-4B-outpaint-lora': ['Flux.2 Klein'],
    'fal/flux-2-klein-4b-spritesheet-lora': ['Flux.2 Klein'],
    'fal/flux-2-klein-4B-zoom-lora': ['Flux.2 Klein'],
    'fal/Qwen-Image-Edit-2511-Multiple-Angles-LoRA': ['Qwen Image Edit'],
    'fal/virtual-tryoff-lora': ['Flux.2 Klein'],
    'gokaygokay/Florence-2-Flux': ['Florence-2'],
    'gokaygokay/Florence-2-Flux-Large': ['Florence-2'],
    'gokaygokay/Florence-2-SD3-Captioner': ['SD 3'],
    'google/siglip-so400m-patch14-384': ['SigLIP'],
    'guoyww/animatediff': ['AnimateDiff'],
    'hr16/DWPose-TorchScript-BatchSize5': ['DWPose'],
    'hr16/UnJIT-DWPose': ['DWPose'],
    'HuggingFaceM4/Florence-2-DocVQA': ['Florence-2'],
    'HuggingFaceTB/SmolLM2-1.7B-Instruct': ['SmolLM2'],
    'HuggingFaceTB/SmolLM2-135M-Instruct': ['SmolLM2'],
    'HuggingFaceTB/SmolLM2-360M-Instruct': ['SmolLM2'],
    'HuggingFaceTB/SmolVLM-Instruct': ['SmolLM2', 'SigLIP'],
    'hustvl/vitmatte-base-composition-1k': ['ViTMatte'],
    'hustvl/vitmatte-small-composition-1k': ['ViTMatte'],
    'infinith/UltraShape': ['Hunyuan 3D'],
    'jetjodh/sam-3d-body-dinov3': ['SAM 3D'],
    'jetjodh/sam-3d-objects': ['SAM 3D'],
    'John6666/joy-caption-alpha-two-cli-mod': ['JoyCaption'],
    'jonathandinu/face-parsing': ['Face Parsing'],
    'joyfox/LTX2.3-ICEdit-Insight': ['LTX 2.3'],
    'JunhaoZhuang/FlashVSR': ['FlashVSR'],
    'JunhaoZhuang/FlashVSR-v1.1': ['FlashVSR'],
    'kabachuha/ltx2-cakeify': ['LTX 2'],
    'kabachuha/ltx2-eat': ['LTX 2'],
    'kabachuha/ltx2-hydraulic-press': ['LTX 2'],
    'kabachuha/ltx2-inflate-it': ['LTX 2'],
    'kandinskylab/Kandinsky-5.0-I2V-Lite-5s': ['Kandinsky'],
    'kandinskylab/Kandinsky-5.0-T2I-Lite': ['Kandinsky'],
    'kandinskylab/Kandinsky-5.0-T2V-Lite-sft-5s': ['Kandinsky'],
    'Kijai/ChatGLM3-safetensors': ['ChatGLM3'],
    'Kijai/DepthAnythingV2-safetensors': ['Depth Anything V2'],
    'Kijai/DynamiCrafter_pruned': ['DynamiCrafter'],
    'Kijai/HunyuanVideo_comfy': ['HunyuanVideo'],
    'Kijai/LivePortrait_safetensors': ['LivePortrait'],
    'Kijai/llava-llama-3-8b-text-encoder-tokenizer': ['LLaVA'],
    'Kijai/lotus-comfyui': ['Lotus'],
    'Kijai/LTX2.3_comfy': ['LTX 2.3'],
    'Kijai/LTXV2_comfy': ['LTX 2'],
    'Kijai/MimicMotion_pruned': ['MimicMotion'],
    'Kijai/sam2-safetensors': ['SAM 2'],
    'Kijai/WanVideo_comfy': ['Wan 2.1'],
    'Kijai/WanVideo_comfy_fp8_scaled': ['Wan 2.1'],
    'Kim2091/UltraSharp': ['UltraSharp'],
    'Kwai-Kolors/Kolors': ['Kolors'],
    'Kwai-Kolors/Kolors-IP-Adapter-FaceID-Plus': ['Kolors'],
    'Kwai-Kolors/Kolors-IP-Adapter-Plus': ['Kolors'],
    'LayerDiffusion/layerdiffusion-v1': ['LayerDiffusion'],
    'Lightricks/LTX-2': ['LTX 2'],
    'Lightricks/LTX-2-19b-IC-LoRA-Canny-Control': ['LTX 2'],
    'Lightricks/LTX-2-19b-IC-LoRA-Depth-Control': ['LTX 2'],
    'Lightricks/LTX-2-19b-IC-LoRA-Detailer': ['LTX 2'],
    'Lightricks/LTX-2-19b-IC-LoRA-Pose-Control': ['LTX 2'],
    'Lightricks/LTX-2-19b-LoRA-Camera-Control-Dolly-In': ['LTX 2'],
    'Lightricks/LTX-2-19b-LoRA-Camera-Control-Dolly-Left': ['LTX 2'],
    'Lightricks/LTX-2-19b-LoRA-Camera-Control-Dolly-Out': ['LTX 2'],
    'Lightricks/LTX-2-19b-LoRA-Camera-Control-Dolly-Right': ['LTX 2'],
    'Lightricks/LTX-2-19b-LoRA-Camera-Control-Jib-Down': ['LTX 2'],
    'Lightricks/LTX-2-19b-LoRA-Camera-Control-Jib-Up': ['LTX 2'],
    'Lightricks/LTX-2-19b-LoRA-Camera-Control-Static': ['LTX 2'],
    'Lightricks/LTX-2.3': ['LTX 2.3'],
    'Lightricks/LTX-2.3-22b-IC-LoRA-HDR': ['LTX 2.3'],
    'Lightricks/LTX-2.3-22b-IC-LoRA-LipDub': ['LTX 2.3'],
    'Lightricks/LTX-2.3-22b-IC-LoRA-Motion-Track-Control': ['LTX 2.3'],
    'Lightricks/LTX-2.3-fp8': ['LTX 2.3'],
    'Lightricks/LTX-Video': ['LTX Video'],
    'lightx2v/Qwen-Image-2512-Lightning': ['Qwen Image'],
    'lightx2v/Qwen-Image-Edit-2511-Lightning': ['Qwen Image Edit'],
    'lightx2v/Qwen-Image-Lightning': ['Qwen Image'],
    'lightx2v/Wan2.2-Distill-Loras': ['Wan 2.2'],
    'lilylilith/AnyPose': ['Qwen Image Edit'],
    'lilylilith/QIE-2511-MP-AnyLight': ['Qwen Image Edit'],
    'lkeab/hq-sam': ['SAM'],
    'lodestones/Chroma': ['Chroma'],
    'lodestones/Chroma1-HD': ['Chroma1 HD'],
    'lovis93/crt-animation-terminal-ltx-2.3-lora': ['LTX Video'],
    'lovis93/next-scene-qwen-image-lora-2509': ['Qwen Image Edit'],
    'lrzjason/Anything2Real_2601': ['Qwen Image Edit'],
    'lrzjason/ObjectRemovalFluxFill': ['Flux.1 dev'],
    'lrzjason/QwenEdit-Anything2Real_Alpha': ['Qwen Image Edit'],
    'lym00/Wan2.2_T2V_A14B_VACE-test': ['Wan 2.2'],
    'MachineDelusions/LTX-2_Image2Video_Adapter_LoRa': ['LTX 2'],
    'marduk191/rife': ['RIFE'],
    'mattmdjaga/segformer_b2_clothes': ['SegFormer'],
    'MiaoshouAI/Florence-2-base-PromptGen': ['Florence-2'],
    'MiaoshouAI/Florence-2-base-PromptGen-v1.5': ['Florence-2'],
    'MiaoshouAI/Florence-2-base-PromptGen-v2.0': ['Florence-2'],
    'MiaoshouAI/Florence-2-large-PromptGen-v1.5': ['Florence-2'],
    'MiaoshouAI/Florence-2-large-PromptGen-v2.0': ['Florence-2'],
    'microsoft/Florence-2-base': ['Florence-2'],
    'microsoft/Florence-2-base-ft': ['Florence-2'],
    'microsoft/Florence-2-large': ['Florence-2'],
    'microsoft/Florence-2-large-ft': ['Florence-2'],
    'Nap/depth_anything_v2_vitg': ['Depth Anything V2'],
    'Nebsh/LTX2_Animatediff_Lora': ['LTX 2'],
    'Nebsh/LTX2_AtomicExplosion': ['LTX 2'],
    'Nebsh/LTX2_Lora_Outfitcheck': ['LTX 2'],
    'Nebsh/LTX2_Lora_TimelapseHuman': ['LTX 2'],
    'Nebsh/LTX2_Outfitswitch': ['LTX 2'],
    'numz/SeedVR2_comfyUI': ['SeedVR2'],
    'OmerHagage/ltx2-greenscreen-avatar-ic-lora-vertical-v1': ['LTX 2.3'],
    'openai/clip-vit-large-patch14': ['CLIP-ViT'],
    'ostris/flux2_berthe_morisot': ['Flux.2 dev'],
    'oumoumad/LTX-2.3-22b-IC-LoRA-Deinterlace': ['LTX 2.3'],
    'oumoumad/LTX-2.3-22b-IC-LoRA-MotionDeblur': ['LTX 2.3'],
    'oumoumad/LTX-2.3-22b-IC-LoRA-Outpaint': ['LTX 2.3'],
    'oumoumad/LTX-2.3-22b-IC-LoRA-ReFocus': ['LTX 2.3'],
    'oumoumad/LTX-2.3-22b-IC-LoRA-Uncompress': ['LTX 2.3'],
    'oumoumad/LTX-2.3-22b-IC-LoRA-Ungrade': ['LTX 2.3'],
    'oumoumad/ltx-2.3-dearchive-lora': ['LTX 2.3'],
    'oumoumad/LumiPic': ['Qwen Image Edit', 'Flux.2 Klein'],
    'ovi054/QIE-2511-Color-Grade-Transfer-LoRA': ['Qwen Image Edit'],
    'Owen777/UltraFlux-v1': ['Flux.1 dev'],
    'peteromallet/Qwen-Image-Edit-InSubject': ['Qwen Image Edit'],
    'Phr00t/WAN2.2-14B-Rapid-AllInOne': ['Wan 2.2'],
    'PixArt-alpha/PixArt-Sigma-XL-2-1024-MS': ['PixArt'],
    'prithivMLmods/QIE-2511-Extract-Outfit': ['Qwen Image Edit'],
    'prithivMLmods/QIE-2511-Object-Remover-v2': ['Qwen Image Edit'],
    'prithivMLmods/QIE-2511-Studio-DeLight': ['Qwen Image Edit'],
    'prithivMLmods/QIE-2511-Zoom-Master': ['Qwen Image Edit'],
    'prithivMLmods/Qwen-Image-Edit-2511-Midnight-Noir-Eyes-Spotlight': [
      'Qwen Image Edit'
    ],
    'prithivMLmods/Qwen-Image-Edit-2511-Noir-Comic-Book-Panel': [
      'Qwen Image Edit'
    ],
    'prithivMLmods/Qwen-Image-Edit-2511-Pixar-Inspired-3D': ['Qwen Image Edit'],
    'prithivMLmods/Qwen-Image-Edit-2511-Ultra-Realistic-Portrait': [
      'Qwen Image Edit'
    ],
    'ProGamerGov/qwen-360-diffusion': ['Qwen Image'],
    'Qwen/Qwen2.5-VL-3B-Instruct': ['Qwen'],
    'Qwen/Qwen2.5-VL-7B-Instruct': ['Qwen'],
    'Qwen/Qwen3-0.6B': ['Qwen'],
    'Qwen/Qwen3-4B-Instruct-2507': ['Qwen'],
    'Qwen/Qwen3-TTS-12Hz-0.6B-Base': ['Qwen'],
    'Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice': ['Qwen'],
    'Qwen/Qwen3-TTS-12Hz-1.7B-Base': ['Qwen'],
    'Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice': ['Qwen'],
    'Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign': ['Qwen'],
    'Qwen/Qwen3-TTS-Tokenizer-12Hz': ['Qwen'],
    'Qwen/Qwen3-VL-2B-Instruct': ['Qwen'],
    'Qwen/Qwen3-VL-2B-Thinking': ['Qwen'],
    'Qwen/Qwen3-VL-32B-Instruct': ['Qwen'],
    'Qwen/Qwen3-VL-32B-Thinking': ['Qwen'],
    'Qwen/Qwen3-VL-4B-Instruct': ['Qwen'],
    'Qwen/Qwen3-VL-4B-Thinking': ['Qwen'],
    'Qwen/Qwen3-VL-8B-Instruct': ['Qwen'],
    'Qwen/Qwen3-VL-8B-Thinking': ['Qwen'],
    'ResembleAI/chatterbox': ['Chatterbox'],
    'ResembleAI/chatterbox-turbo': ['Chatterbox Turbo'],
    'roborovski/superprompt-v1': ['SuperPrompt'],
    'Ruicheng/moge-vitl': ['MoGe'],
    'RunDiffusion/Juggernaut-XL-v9': ['SDXL'],
    'sayeed99/segformer_b3_clothes': ['SegFormer'],
    'sayeed99/segformer-b3-fashion': ['SegFormer'],
    'Shakker-Labs/AWPortrait-QW': ['Qwen Image'],
    'Shakker-Labs/AWPortrait-Z': ['Z-Image'],
    'ShilongLiu/GroundingDINO': ['GroundingDINO'],
    'stabilityai/sdxl-turbo': ['SDXL'],
    'stabilityai/stable-audio-open-1.0': ['Stable Audio'],
    'stabilityai/stable-diffusion-3.5-controlnets': ['SD 3.5'],
    'stabilityai/stable-diffusion-xl-base-1.0': ['SDXL'],
    'stabilityai/stable-diffusion-xl-refiner-1.0': ['SDXL'],
    'StableDiffusionVN/Flux': ['Flux.1 dev'],
    'systms/SYSTMS-ACTION-LoRA-Qwen-Image-Edit-2511': ['Qwen Image Edit'],
    'systms/SYSTMS-FLW-IC-LORA-LTX-2.3': ['LTX Video'],
    'systms/SYSTMS-INFL8-LoRA-Qwen-Image-Edit-2511': ['Qwen Image Edit'],
    'systms/SYSTMS-TRNS-LoRA-Wan22': ['Wan 2.2'],
    'TalmajM/LongCat-Image-Edit_ComfyUI_repackaged': ['LongCat'],
    'tarn59/apply_texture_qwen_image_edit_2509': ['Qwen Image Edit'],
    'tarn59/pixel_art_style_lora_z_image_turbo': ['Z-Image'],
    'tencent/Hunyuan3D-2': ['Hunyuan 3D'],
    'tencent/Hunyuan3D-2mv': ['Hunyuan 3D'],
    'TencentARC/t2i-adapter-lineart-sdxl-1.0': ['SDXL'],
    'TheBurgstall/ltx-2.3-googlyeyes-lora': ['LTX 2.3'],
    'TheDenk/wan2.1-t2v-1.3b-controlnet-canny-v1': ['Wan 2.1'],
    'TheDenk/wan2.1-t2v-1.3b-controlnet-depth-v1': ['Wan 2.1'],
    'TheDenk/wan2.1-t2v-1.3b-controlnet-hed-v1': ['Wan 2.1'],
    'TheDenk/wan2.1-t2v-14b-controlnet-canny-v1': ['Wan 2.1'],
    'TheDenk/wan2.1-t2v-14b-controlnet-depth-v1': ['Wan 2.1'],
    'TheDenk/wan2.1-t2v-14b-controlnet-hed-v1': ['Wan 2.1'],
    'thwri/CogFlorence-2-Large-Freeze': ['Florence-2'],
    'thwri/CogFlorence-2.1-Large': ['Florence-2'],
    'unsloth/Llama-3.2-3B-Instruct': ['Llama 3.2'],
    'vafipas663/Qwen-Edit-2509-Upscale-LoRA': ['Qwen Image Edit'],
    'valiantcat/LTX-2.3-Transition-LORA': ['LTX 2.3'],
    'valiantcat/LTX2-I2V-Smooth-LORA': ['LTX 2'],
    'valiantcat/Qwen-Image-Edit-2509-Passionate-kiss': ['Qwen Image Edit'],
    'valiantcat/Qwen-Image-Edit-2509-photous': ['Qwen Image Edit'],
    'valiantcat/Qwen-Image-Edit-2511-Upscale2K': ['Qwen Image Edit'],
    'vrgamedevgirl84/LTX_2.3_90s_Animation_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Cinematic_Sci-fi-Cyberpunk_Style_LoRa': [
      'LTX Video'
    ],
    'vrgamedevgirl84/LTX_2.3_Clay_Mation_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Crisp_Enhance_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Fantasy_Anime_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Fantasy_Painterly_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Fantasy_Puppet_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Fantasy_Realism_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Paper_Cut_Out_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Pixar_Toon_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Post_Apocalyptic_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Soft_Enhance_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX_2.3_Wild_West_Style_LoRa': ['LTX Video'],
    'vrgamedevgirl84/LTX2.3_Cozy_Felt_Style_LoRa': ['LTX Video'],
    'Wan-AI/Wan2.2-Animate-14B': ['Wan 2.2'],
    'Wuli-art/Qwen-Image-2512-Turbo-LoRA-2-Steps': ['Qwen Image'],
    'xtuner/llava-llama-3-8b-v1_1-transformers': ['LLaVA'],
    'YaoJiefu/multiple-characters': ['Qwen Image Edit'],
    'YxZhang/evf-sam': ['SAM'],
    'YxZhang/evf-sam2': ['SAM 2'],
    'yzd-v/DWPose': ['DWPose'],
    'ZhengPeng7/BiRefNet': ['BiRefNet'],
    'Zlikwid/LTX_2.3_Upscale_IC_Lora': ['LTX 2.3'],
    'zooeyy/Qwen-Edit-2511_LightingRemap_Alpha0.2': ['Qwen Image Edit']
  })

export function getBaseModelOverrides(repoId: string): readonly string[] {
  return BASE_MODEL_OVERRIDES[repoId] ?? []
}
