export const RESERVED_BY_BROWSER = new Set([
  'Ctrl + t',
  'Ctrl + w',
  'Ctrl + n',
  'Ctrl + Shift + n',
  'Ctrl + Tab',
  'Ctrl + Shift + Tab',
  'Ctrl + Shift + Delete',
  'Ctrl + h',
  'Ctrl + j',
  'Ctrl + d',
  'Ctrl + Shift + b',
  'Ctrl + Shift + o',
  'Ctrl + Shift + i',
  'Ctrl + Shift + j',
  'F5',
  'Ctrl + F5',
  'Ctrl + r',
  'Ctrl + Shift + r',
  'F7',
  'F11',
  'F12',
  'Alt + F4'
])

export const RESERVED_BY_TEXT_INPUT = new Set([
  'Ctrl + a',
  'Ctrl + c',
  'Ctrl + v',
  'Ctrl + x',
  'Ctrl + z',
  'Ctrl + y',
  'Ctrl + p',
  'Enter',
  'Shift + Enter',
  'Ctrl + Backspace',
  'Ctrl + Delete',
  'Home',
  'Ctrl + Home',
  'Ctrl + Shift + Home',
  'End',
  'Ctrl + End',
  'Ctrl + Shift + End',
  'PageUp',
  'PageDown',
  'Shift + PageUp',
  'Shift + PageDown',
  'ArrowLeft',
  'Ctrl + ArrowLeft',
  'Shift + ArrowLeft',
  'Ctrl + Shift + ArrowLeft',
  'ArrowRight',
  'Ctrl + ArrowRight',
  'Shift + ArrowRight',
  'Ctrl + Shift + ArrowRight',
  'ArrowUp',
  'Shift + ArrowUp',
  'ArrowDown',
  'Shift + ArrowDown'
])
