/**
 * Pending-op ledger (s3-opt-1 / CRDT-RM-3): the pure state machine behind the
 * follower's optimistic overlay. It registers locally minted semantic ops by
 * their immutable `op_id` and tracks each one through send and outcome, so a
 * later presentation layer (s3-opt-5) can render pending shadows and the
 * send-path integration (s3-opt-6) can drive retry/revert policy.
 *
 * Contract boundaries this module deliberately encodes:
 *
 * - `op_id` is minted ONCE by the caller and never regenerated here. Retrying
 *   a send reuses the same id (`markInFlight` accepts a re-send of an entry
 *   that already flew), so the host's duplicate detection stays sound.
 * - A `doc_ops_result` with `ok:false` means "a failure exists", NOT "the
 *   batch rolled back": the host applies the valid prefix, records the
 *   failure, and still broadcasts. `reconcileOpsResult` therefore transitions
 *   each batch member per-outcome — applied / skipped / failed / unprocessed —
 *   and removes NOTHING. There is intentionally no rollback-the-batch API.
 * - Per KEEP-ALIVE #9, an applied entry is preserved until its matching
 *   authoritative EFFECT (`doc_update`, correlated by op id once DQ-9/enact-2
 *   lands), not until the ack. `clearOnEffect` is the only outcome-driven
 *   removal path.
 * - `skipped[]` means the op id already existed host-side before this call; a
 *   fully duplicate batch produces no new broadcast, so a skipped entry may
 *   never see an effect frame. The ledger keeps it visible in the `skipped`
 *   state and leaves the authoritative catch-up policy to s3-opt-2, which
 *   removes it explicitly via `take`.
 * - The ledger never touches Yjs or the canvas: it stores an opaque `shadow`
 *   payload for the presentation layer and nothing else. No timers, no
 *   clocks, no IO — every transition is an explicit call.
 */

/** Lifecycle of one pending op. All transitions are explicit caller calls. */
export type PendingOpState =
  /** Enqueued locally; not yet handed to the transport. */
  | 'queued'
  /** Sent (or re-sent) on the wire; awaiting `doc_ops_result`. */
  | 'inflight'
  /** Host applied it (prefix of a batch); awaiting its `doc_update` effect. */
  | 'applied'
  /** Host reported the op id as already present; no new effect will come. */
  | 'skipped'
  /** Host rejected this exact op; shadow revert/retry policy is s3-opt-2/6. */
  | 'failed'
  /** Batch member after the failed op; the host never processed it. */
  | 'unprocessed'

export interface PendingOpEntry<TShadow = unknown> {
  /** Immutable caller-minted operation id. Never regenerated by the ledger. */
  readonly opId: string
  readonly state: PendingOpState
  /** Opaque presentation payload (overlay shadow). The ledger never reads it. */
  readonly shadow: TShadow
  /** Verbatim host failure detail; only present in the `failed` state. */
  readonly failure?: unknown
}

/** Per-outcome input mirroring one `doc_ops_result` for one sent batch. */
export interface OpsResultOutcome {
  /**
   * The op ids of the batch AS SENT, in order. Needed to classify members the
   * host never reached (everything after the failed op) as `unprocessed`.
   */
  batch: readonly string[]
  /** Op ids the host applied (the committed prefix — never rolled back). */
  applied: readonly string[]
  /** Op ids already present host-side before this call. */
  skipped: readonly string[]
  /** The single rejected op id, when `ok:false`. */
  failedOpId?: string | null
  /** Verbatim failure detail to preserve on the failed entry. */
  failure?: unknown
}

/** What `reconcileOpsResult` did, per op id, for observability and tests. */
export interface ReconcileSummary {
  applied: string[]
  skipped: string[]
  failed: string[]
  unprocessed: string[]
  /** Result mentioned an id the ledger does not hold (lost or foreign op). */
  unknown: string[]
}

export interface PendingOpLedger<TShadow = unknown> {
  /**
   * Register a minted op exactly once. Returns false (and changes nothing)
   * when the id is already present in ANY state — enqueue is idempotent-safe,
   * never an overwrite.
   */
  enqueue(opId: string, shadow: TShadow): boolean
  /**
   * Mark ids as sent. Valid from `queued` (first send) and from `inflight`,
   * `failed`, or `unprocessed` (a retry with the SAME id, per s3-opt-6
   * policy). Returns the ids that did not transition (unknown, or in a state
   * that must not fly again: `applied`/`skipped`).
   */
  markInFlight(opIds: readonly string[]): string[]
  /**
   * Apply one `doc_ops_result` per-outcome. Applied ids → `applied`, skipped
   * ids → `skipped`, the failed id → `failed` (with detail), and remaining
   * batch members → `unprocessed`. Removes nothing; never encodes
   * whole-batch rollback.
   */
  reconcileOpsResult(outcome: OpsResultOutcome): ReconcileSummary
  /**
   * Authoritative effect arrived for these op ids: remove and return the
   * matching entries regardless of state (the effect supersedes any ack
   * bookkeeping). This is the KA-9 clear-on-effect path.
   */
  clearOnEffect(opIds: readonly string[]): PendingOpEntry<TShadow>[]
  /**
   * Explicit reconciliation removal (e.g. revert of a failed shadow, or a
   * skipped entry after authoritative catch-up). Returns the removed entry,
   * or undefined when the id is not held.
   */
  take(opId: string): PendingOpEntry<TShadow> | undefined
  /** Snapshot of current entries, optionally filtered by state. */
  entries(state?: PendingOpState): PendingOpEntry<TShadow>[]
  get(opId: string): PendingOpEntry<TShadow> | undefined
  size(): number
}

interface MutableEntry<TShadow> {
  opId: string
  state: PendingOpState
  shadow: TShadow
  failure?: unknown
}

const RETRYABLE: ReadonlySet<PendingOpState> = new Set([
  'queued',
  'inflight',
  'failed',
  'unprocessed'
])

export function createPendingOpLedger<
  TShadow = unknown
>(): PendingOpLedger<TShadow> {
  /** Insertion-ordered by first enqueue; ids are never re-minted or reused. */
  const ledger = new Map<string, MutableEntry<TShadow>>()

  const snapshot = (e: MutableEntry<TShadow>): PendingOpEntry<TShadow> =>
    e.failure === undefined
      ? { opId: e.opId, state: e.state, shadow: e.shadow }
      : { opId: e.opId, state: e.state, shadow: e.shadow, failure: e.failure }

  return {
    enqueue(opId, shadow) {
      if (ledger.has(opId)) return false
      ledger.set(opId, { opId, state: 'queued', shadow })
      return true
    },

    markInFlight(opIds) {
      const rejected: string[] = []
      for (const opId of opIds) {
        const entry = ledger.get(opId)
        if (!entry || !RETRYABLE.has(entry.state)) {
          rejected.push(opId)
          continue
        }
        entry.state = 'inflight'
        delete entry.failure
      }
      return rejected
    },

    reconcileOpsResult(outcome) {
      const summary: ReconcileSummary = {
        applied: [],
        skipped: [],
        failed: [],
        unprocessed: [],
        unknown: []
      }
      const resolved = new Set<string>()

      const transition = (
        opId: string,
        state: PendingOpState,
        bucket: string[],
        failure?: unknown
      ) => {
        resolved.add(opId)
        const entry = ledger.get(opId)
        if (!entry) {
          summary.unknown.push(opId)
          return
        }
        entry.state = state
        if (failure === undefined) delete entry.failure
        else entry.failure = failure
        bucket.push(opId)
      }

      for (const opId of outcome.applied)
        transition(opId, 'applied', summary.applied)
      for (const opId of outcome.skipped)
        transition(opId, 'skipped', summary.skipped)
      if (outcome.failedOpId != null)
        transition(
          outcome.failedOpId,
          'failed',
          summary.failed,
          outcome.failure
        )
      for (const opId of outcome.batch) {
        if (resolved.has(opId)) continue
        transition(opId, 'unprocessed', summary.unprocessed)
      }
      return summary
    },

    clearOnEffect(opIds) {
      const removed: PendingOpEntry<TShadow>[] = []
      for (const opId of opIds) {
        const entry = ledger.get(opId)
        if (!entry) continue
        ledger.delete(opId)
        removed.push(snapshot(entry))
      }
      return removed
    },

    take(opId) {
      const entry = ledger.get(opId)
      if (!entry) return undefined
      ledger.delete(opId)
      return snapshot(entry)
    },

    entries(state) {
      const out: PendingOpEntry<TShadow>[] = []
      for (const entry of ledger.values()) {
        if (state !== undefined && entry.state !== state) continue
        out.push(snapshot(entry))
      }
      return out
    },

    get(opId) {
      const entry = ledger.get(opId)
      return entry ? snapshot(entry) : undefined
    },

    size() {
      return ledger.size
    }
  }
}
