name: Start ComfyUI Server
description: 'Start ComfyUI server in a container environment (assumes ComfyUI is pre-installed)'

inputs:
  front_end_root:
    description: 'Path to frontend dist directory'
    required: false
    default: '${{ github.workspace }}/dist'
  timeout:
    description: 'Timeout in seconds for server startup'
    required: false
    default: '600'

runs:
  using: 'composite'
  steps:
    - name: Copy devtools and start server
      shell: bash
      run: |
        cp -r ./tools/devtools/* /ComfyUI/custom_nodes/ComfyUI_devtools/
        cd /ComfyUI && python3 main.py --cpu --multi-user --front-end-root ${{ inputs.front_end_root }} &
        wait-for-it --service 127.0.0.1:8188 -t ${{ inputs.timeout }}
