import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

import type { DeprecationEntry } from '../src/platform/dev/deprecations'
import { DEPRECATIONS } from '../src/platform/dev/deprecations'

const OUTPUT_PATH = './docs/deprecations.mdx'

const FRONTMATTER = `---
title: "Deprecations"
description: "Deprecated frontend APIs and their replacements."
---`

const INTRO = `Whilst we try to keep the frontend API stable and backwards compatible, there are times where functionality must change - to fix bugs, improve performance, or make room for new features.

When that happens we deprecate the old API rather than removing it outright: it keeps working until the removal date, but logs a warning pointing you at the replacement. This page lists the currently deprecated APIs so you can migrate your custom nodes and extensions ahead of their removal.

## Deprecation Warnings panel

To see which deprecated APIs are actually being used in your current session, enable the **"Enable dev mode options"** setting (Settings → search "dev mode"). A **Deprecation Warnings** panel then appears in the main sidebar, listing each warning reported this session - with the suggested replacement and how many times it occurred.

Alternatively, every deprecation is logged to the browser DevTools console as it occurs, prefixed with a \`[DEPRECATED]\` tag.`

interface Column {
  header: string
  cell: (entry: DeprecationEntry) => string | undefined
}

const REQUIRED_COLUMNS: Column[] = [
  { header: 'Deprecated', cell: (entry) => entry.message },
  { header: 'Replacement', cell: (entry) => entry.suggestion }
]

const OPTIONAL_COLUMNS: Column[] = [
  { header: 'Since', cell: (entry) => entry.since },
  { header: 'Removed in', cell: (entry) => entry.removeBy },
  {
    header: 'Docs',
    cell: (entry) => (entry.docsUrl ? `[Guide](${entry.docsUrl})` : undefined)
  }
]

function escapeCell(value: string | undefined): string {
  if (!value) return '-'
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

function activeColumns(entries: DeprecationEntry[]): Column[] {
  return [
    ...REQUIRED_COLUMNS,
    ...OPTIONAL_COLUMNS.filter((column) =>
      entries.some((entry) => column.cell(entry))
    )
  ]
}

function groupBySource(
  deprecations: Record<string, DeprecationEntry>
): Map<string, DeprecationEntry[]> {
  const groups = new Map<string, DeprecationEntry[]>()
  for (const entry of Object.values(deprecations)) {
    const group = groups.get(entry.source) ?? []
    group.push(entry)
    groups.set(entry.source, group)
  }
  return groups
}

function renderRow(cells: string[]): string {
  return `| ${cells.join(' | ')} |`
}

function renderSection(
  source: string,
  entries: DeprecationEntry[],
  columns: Column[]
): string {
  const rows = entries.map((entry) =>
    renderRow(columns.map((column) => escapeCell(column.cell(entry))))
  )
  return [
    `## ${source}`,
    '',
    renderRow(columns.map((column) => column.header)),
    renderRow(columns.map(() => '---')),
    ...rows
  ].join('\n')
}

export function renderDeprecationsMdx(
  deprecations: Record<string, DeprecationEntry>
): string {
  const columns = activeColumns(Object.values(deprecations))
  const sections = [...groupBySource(deprecations).entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([source, entries]) => renderSection(source, entries, columns))

  return [
    FRONTMATTER,
    '',
    '{/* Generated by scripts/generate-deprecations-doc.ts. Do not edit by hand. */}',
    '',
    INTRO,
    '',
    sections.join('\n\n'),
    ''
  ].join('\n')
}

function main(): void {
  const mdx = renderDeprecationsMdx(DEPRECATIONS)
  fs.writeFileSync(path.resolve(OUTPUT_PATH), mdx)
}

const invokedDirectly =
  process.argv[1] &&
  fileURLToPath(import.meta.url) === path.resolve(process.argv[1])
if (invokedDirectly) main()
