#!/usr/bin/env bash
set -euo pipefail

output=scripts/primevue-import-allowlist.ts
temp=$(mktemp scripts/primevue-import-allowlist.XXXXXX.ts)
primevue_import_pattern="(?:\\bfrom\\s*|\\bimport\\s*(?:\\(\\s*)?)[\"'](?:primevue|@primevue)(?:/[^\"']*)?[\"']"
trap 'rm -f "$temp"' EXIT

{
  echo '// Generated by scripts/generate-primevue-import-allowlist.sh. Do not edit.'
  echo 'export const primeVueImportAllowlist = ['
  { rg -l -U --pcre2 \
    -g '*.{ts,tsx,vue}' \
    -g '!src/scripts/*' \
    -g '!src/extensions/core/*' \
    "$primevue_import_pattern" src/ || [[ $? == 1 ]]; } |
    LC_ALL=C sort |
    sed "s|^|  '|; s|$|',|"
  echo '] as const'
} > "$temp"

pnpm exec oxfmt --write "$temp"
mv "$temp" "$output"
trap - EXIT
