import {
  comfyExpect as expect,
  comfyPageFixture as test
} from '@e2e/fixtures/ComfyPage'
import {
  expectedCanonicalPersistence,
  exportedProjection,
  legacyWorkflowFixture,
  persistedProjection,
  persistedWorkflowPaths,
  projectWorkflow
} from '@e2e/fixtures/utils/legacyWorkflowRoundTrip'

for (const vueNodesEnabled of [false, true]) {
  test.describe(
    `legacy workflow save and full reload with VueNodes=${vueNodesEnabled}`,
    {
      tag: vueNodesEnabled
        ? ['@canvas', '@widget', '@vue-nodes']
        : ['@canvas', '@widget']
    },
    () => {
      const savedName = `legacy-v1.52.5-resaved-${
        vueNodesEnabled ? 'vue' : 'litegraph'
      }`
      const savedFilename = `${savedName}.json`
      const savedPath = `workflows/${savedFilename}`

      test.afterEach(async ({ comfyPage }) => {
        const status = await comfyPage.page.evaluate(async (workflowPath) => {
          const response = await window.app!.api.deleteUserData(workflowPath)
          return response.status
        }, savedPath)
        expect([204, 404]).toContain(status)
      })

      test('preserves exact nodes, links, groups, reroutes, and widget values', async ({
        comfyPage
      }) => {
        test.slow()
        test.info().annotations.push({
          type: 'fixture-provenance',
          description:
            'Generated by the frontend v1.52.5 tag (abf63b48b3) from repository fixture 7972550f6b, then saved by its graph serializer'
        })

        const expected = projectWorkflow(legacyWorkflowFixture)
        const expectedPersisted = expectedCanonicalPersistence(expected)
        expect(expected.nodes.length).toBeGreaterThan(0)
        expect(expected.links?.length).toBeGreaterThan(0)
        expect(expected.groups?.length).toBeGreaterThan(0)
        expect(expected.reroutes?.length).toBeGreaterThan(0)
        expect(
          expected.nodes.filter(({ widgetsValues }) => widgetsValues?.length)
            .length
        ).toBeGreaterThan(0)

        await comfyPage.workflow.loadWorkflow('legacy-v1.52.5-entity-roundtrip')
        expect(await exportedProjection(comfyPage)).toEqual(expected)

        await comfyPage.menu.topbar.saveWorkflowAs(savedName)

        await expect
          .poll(() => comfyPage.workflow.getActiveWorkflowPath())
          .toBe(savedPath)
        await expect
          .poll(() => persistedWorkflowPaths(comfyPage))
          .toContain(savedFilename)
        expect(await persistedProjection(comfyPage, savedPath)).toEqual(
          expectedPersisted
        )

        await comfyPage.workflow.reloadAndWaitForApp()

        await expect
          .poll(() => comfyPage.workflow.getActiveWorkflowPath())
          .toBe(savedPath)
        await expect
          .poll(() => persistedWorkflowPaths(comfyPage))
          .toContain(savedFilename)
        expect(await persistedProjection(comfyPage, savedPath)).toEqual(
          expectedPersisted
        )
        await expect.poll(() => exportedProjection(comfyPage)).toEqual(expected)
      })
    }
  )
}
