/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CanvasBottomBar: typeof import('./components/v2/canvas/CanvasBottomBar.vue')['default']
    CanvasLeftSidebar: typeof import('./components/v2/canvas/CanvasLeftSidebar.vue')['default']
    CanvasTabBar: typeof import('./components/v2/canvas/CanvasTabBar.vue')['default']
    FlowNode: typeof import('./components/v2/nodes/FlowNode.vue')['default']
    FlowNodeMinimized: typeof import('./components/v2/nodes/FlowNodeMinimized.vue')['default']
    NodeHeader: typeof import('./components/v2/nodes/NodeHeader.vue')['default']
    NodeSlots: typeof import('./components/v2/nodes/NodeSlots.vue')['default']
    NodeWidgets: typeof import('./components/v2/nodes/NodeWidgets.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotDot: typeof import('./components/v2/nodes/SlotDot.vue')['default']
    WidgetColor: typeof import('./components/v2/nodes/widgets/WidgetColor.vue')['default']
    WidgetNumber: typeof import('./components/v2/nodes/widgets/WidgetNumber.vue')['default']
    WidgetSelect: typeof import('./components/v2/nodes/widgets/WidgetSelect.vue')['default']
    WidgetSlider: typeof import('./components/v2/nodes/widgets/WidgetSlider.vue')['default']
    WidgetText: typeof import('./components/v2/nodes/widgets/WidgetText.vue')['default']
    WidgetToggle: typeof import('./components/v2/nodes/widgets/WidgetToggle.vue')['default']
    WorkspaceLayout: typeof import('./components/v2/layout/WorkspaceLayout.vue')['default']
    WorkspaceSidebar: typeof import('./components/v2/layout/WorkspaceSidebar.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
