import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import { websiteRoot } from '@website/paths'
import { modelPageUrls } from '@/config/model-urls'
import { models } from '@/config/models'
import type { SupportedModelUrl } from '@/config/supported-model-urls'
import { supportedModelUrls } from '@/config/supported-model-urls'
import { workshopModels } from '@/config/workshop-browse-content'
import { modelUrlSlug } from './generate-model-url-map'
import { isDirectExecution } from './script-entry-point'

interface SupportedModel {
  readonly slug: string
  readonly canonicalSlug?: string
  readonly displayName: string
}

interface HubPage {
  readonly newSlug: string
  readonly name: string
}

/** Earlier wins when one model has several task pages. */
const TASKS_BY_PRIORITY = [
  'text-to-image',
  'text-to-vector',
  'text-to-video',
  'reference-to-video',
  'text-to-speech',
  'text-to-dialogue',
  'image-to-video',
  'first-last-frame',
  'video-continuation',
  'image-edit',
  'video-edit',
  'video-to-video',
  'audio-to-video'
] as const

const taskOf = (slug: string) =>
  TASKS_BY_PRIORITY.find((task) => slug.endsWith(`-${task}`))

const sameVersion = (slug: string) => slug.replace(/(\d)-0(?=-|$)/g, '$1')

const modelKey = (name: string) => sameVersion(modelUrlSlug(name))

function hubModelKey({ name }: HubPage): string {
  const slug = modelUrlSlug(name)
  const task = taskOf(slug)
  return sameVersion(task ? slug.slice(0, -task.length - 1) : slug)
}

const taskRank = (page: HubPage) => {
  const task = taskOf(modelUrlSlug(page.name))
  return task ? TASKS_BY_PRIORITY.indexOf(task) : -1
}

/**
 * The Hub page for the same model, or undefined when there is none. A Hub
 * page matches only when its name minus the task is the model's name, so a
 * provider page (ElevenLabs) or another version (Kling 2.6 vs Kling 2.6 Pro)
 * never matches.
 */
function supportedModelHubSlug(
  name: string,
  hubPages: readonly HubPage[],
  providers: ReadonlySet<string>
): string | undefined {
  const key = modelKey(name)
  if (providers.has(key)) return undefined
  return hubPages
    .filter((page) => hubModelKey(page) === key)
    .sort(
      (a, b) =>
        taskRank(a) - taskRank(b) || a.newSlug.localeCompare(b.newSlug, 'en')
    )
    .at(0)?.newSlug
}

/** `frozen` rows keep their target; only slugs new to the table are matched. */
export function compileSupportedModelUrls(
  supportedModels: readonly SupportedModel[],
  hubPages: readonly HubPage[],
  providerNames: readonly string[],
  frozen: readonly SupportedModelUrl[] = []
): SupportedModelUrl[] {
  const providers = new Set(providerNames.map(modelKey))
  const bySlug = new Map(supportedModels.map((model) => [model.slug, model]))
  const rows = new Map(frozen.map((row) => [row[0], row]))
  for (const model of supportedModels) {
    if (rows.has(model.slug)) continue
    const canonical = bySlug.get(model.canonicalSlug ?? model.slug) ?? model
    const hubSlug = supportedModelHubSlug(
      canonical.displayName,
      hubPages,
      providers
    )
    rows.set(model.slug, hubSlug ? [model.slug, hubSlug] : [model.slug])
  }
  return [...rows.values()].sort((a, b) => a[0].localeCompare(b[0], 'en'))
}

function renderSupportedModelUrlsModule(
  rows: readonly SupportedModelUrl[]
): string {
  const line = (row: SupportedModelUrl) =>
    `  [${row.map((value) => `'${value}'`).join(', ')}]`
  return `// Generated by scripts/generate-supported-model-urls.ts. Rows are frozen.
// Every published /p/supported-models/<slug> page, with the /hub/models/<slug>
// page for the same model. A row without one redirects to /hub/models/.
export type SupportedModelUrl = readonly [slug: string, hubSlug?: string]

export const supportedModelUrls: readonly SupportedModelUrl[] = [
${rows.map(line).join(',\n')}
]
`
}

if (isDirectExecution(process.argv[1], import.meta.filename)) {
  const rows = compileSupportedModelUrls(
    models,
    modelPageUrls,
    workshopModels.flatMap(({ provider }) => (provider ? [provider] : [])),
    supportedModelUrls
  )
  await writeFile(
    join(websiteRoot, 'src/config/supported-model-urls.ts'),
    renderSupportedModelUrlsModule(rows)
  )
  console.warn(
    `${rows.length} pages, ${rows.filter((row) => row[1]).length} with a Hub page`
  )
}
