import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import type {
  RouterWorkshopModel,
  UseCase
} from '../src/config/models-catalogue'
import {
  routerModelSlugAliases,
  workshopModels
} from '../src/config/workshop-browse-content'
import { isDirectExecution } from './script-entry-point'

type MapModel = Pick<
  RouterWorkshopModel,
  'slug' | 'name' | 'provider' | 'useCases' | 'routerId'
>
interface ModelUrlMap {
  pages: { oldSlug: string; newSlug: string }[]
  aliases: { alias: string; newSlug: string }[]
}

export const MODEL_URL_SLUG = /^[a-z0-9]+(-[a-z0-9]+)*$/

const TASK_WORDS_BY_USE_CASE: Readonly<Record<UseCase, readonly string[]>> = {
  'generate-images': ['text-to-image', 'text-to-vector'],
  'edit-images': ['image-edit'],
  'generate-videos': ['text-to-video', 'reference-to-video'],
  'animate-images': [
    'image-to-video',
    'reference-to-video',
    'first-last-frame',
    'video-continuation'
  ],
  'edit-videos': ['video-edit', 'video-to-video', 'audio-to-video'],
  audio: ['text-to-speech', 'text-to-dialogue'],
  '3d': [],
  text: []
}
const TASK_WORDS = [...new Set(Object.values(TASK_WORDS_BY_USE_CASE).flat())]

const compareText = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0)

const hasWords = (slug: string, words: string) =>
  `-${slug}-`.includes(`-${words}-`)

export function modelUrlSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export function compileModelUrlMap(
  models: readonly Pick<MapModel, 'slug' | 'name'>[],
  aliases: ReadonlyMap<string, string>
): ModelUrlMap {
  const newSlugByOld = new Map(
    models.map((model) => [model.slug, modelUrlSlug(model.name)])
  )
  const owners = new Map<string, string>()
  for (const [oldSlug, newSlug] of newSlugByOld) {
    if (!MODEL_URL_SLUG.test(newSlug))
      throw new Error(`Invalid model URL slug for ${oldSlug}: ${newSlug}`)
    const owner = owners.get(newSlug)
    if (owner) throw new Error(`${oldSlug} and ${owner} both map to ${newSlug}`)
    owners.set(newSlug, oldSlug)
  }
  return {
    pages: [...newSlugByOld]
      .map(([oldSlug, newSlug]) => ({ oldSlug, newSlug }))
      .sort((a, b) => compareText(a.oldSlug, b.oldSlug)),
    aliases: [...aliases]
      .map(([alias, target]) => {
        const newSlug = newSlugByOld.get(target)
        if (!newSlug)
          throw new Error(`Alias ${alias} targets unknown ${target}`)
        return { alias, newSlug }
      })
      .sort((a, b) => compareText(a.alias, b.alias))
  }
}

function modelUrlFlags(model: MapModel, newSlug: string): string[] {
  const useCases = model.useCases ?? []
  const named = TASK_WORDS.filter((words) => hasWords(newSlug, words))
  const expected = useCases.flatMap(
    (useCase) => TASK_WORDS_BY_USE_CASE[useCase]
  )
  return [
    ...(named.length
      ? []
      : ['no task words in the name; the product name stands in for the task']),
    ...named
      .filter((words) => !expected.includes(words))
      .map(
        (words) => `name says "${words}", task data says ${useCases.join(', ')}`
      ),
    ...(/\d/.test(model.routerId.split('/')[1] ?? '') && !/\d/.test(newSlug)
      ? [`no version in the name, Router id is ${model.routerId}`]
      : [])
  ]
}

const entryLines = (fields: Record<string, string>) =>
  [
    '  {',
    Object.entries(fields)
      .map(([k, v]) => `    ${k}: '${v}'`)
      .join(',\n'),
    '  }'
  ].join('\n')

export function renderModelUrlsModule(map: ModelUrlMap): string {
  return `// Generated by scripts/generate-model-url-map.ts. Do not edit by hand.
export const modelPageUrls: readonly { oldSlug: string; newSlug: string }[] = [
${map.pages.map(entryLines).join(',\n')}
]

export const modelAliasUrls: readonly { alias: string; newSlug: string }[] = [
${map.aliases.map(entryLines).join(',\n')}
]
`
}

export function renderModelUrlTable(
  models: readonly MapModel[],
  map: ModelUrlMap
): string {
  const newSlugByOld = new Map(
    map.pages.map((page) => [page.oldSlug, page.newSlug])
  )
  const rows = models
    .map((model) => ({ model, newSlug: newSlugByOld.get(model.slug) ?? '' }))
    .sort(
      (a, b) =>
        compareText(a.model.provider ?? '', b.model.provider ?? '') ||
        compareText(a.model.slug, b.model.slug)
    )
  const flagged = rows.flatMap(({ model, newSlug }) => {
    const flags = modelUrlFlags(model, newSlug)
    return flags.length
      ? [`| \`${newSlug}\` | ${model.name} | ${flags.join('; ')} |`]
      : []
  })
  return [
    '# Model page URL map',
    '',
    'Generated by `scripts/generate-model-url-map.ts`. Old URL `/models/<old slug or alias>/`, final URL `/hub/models/<new slug>/`.',
    '',
    `## Check these first (${flagged.length})`,
    '',
    '| New slug | Display name | Why |',
    '| --- | --- | --- |',
    ...flagged,
    '',
    `## Model pages (${rows.length})`,
    '',
    '| Provider | Display name | Old slug | New slug |',
    '| --- | --- | --- | --- |',
    ...rows.map(
      ({ model, newSlug }) =>
        `| ${model.provider ?? ''} | ${model.name} | \`${model.slug}\` | \`${newSlug}\` |`
    ),
    '',
    `## Aliases (${map.aliases.length})`,
    '',
    '| Alias | New slug |',
    '| --- | --- |',
    ...map.aliases.map(
      ({ alias, newSlug }) => `| \`${alias}\` | \`${newSlug}\` |`
    ),
    ''
  ].join('\n')
}

const appDir = join(dirname(fileURLToPath(import.meta.url)), '..')
export const MODEL_URLS_MODULE = join(appDir, 'src/config/model-urls.ts')
export const MODEL_URL_TABLE = join(appDir, 'MODEL_URL_MAP.md')

if (isDirectExecution(process.argv[1], import.meta.filename)) {
  const map = compileModelUrlMap(workshopModels, routerModelSlugAliases)
  await writeFile(MODEL_URLS_MODULE, renderModelUrlsModule(map))
  await writeFile(MODEL_URL_TABLE, renderModelUrlTable(workshopModels, map))
  console.warn(`${map.pages.length} pages, ${map.aliases.length} aliases`)
}
