import { readFileSync } from 'node:fs'

import type { ComfyWorkflowJSON } from '@/platform/workflow/validation/schemas/workflowSchema'
import type { ComfyPage } from '@e2e/fixtures/ComfyPage'
import {
  comfyExpect as expect,
  comfyPageFixture as test
} from '@e2e/fixtures/ComfyPage'

type WorkflowProjection = ReturnType<typeof projectWorkflow>

const fixture = JSON.parse(
  readFileSync(
    new URL('../assets/legacy-v1.52.5-entity-roundtrip.json', import.meta.url),
    'utf-8'
  )
) as ComfyWorkflowJSON

function projectWorkflow(workflow: ComfyWorkflowJSON) {
  return {
    nodes: workflow.nodes.map((node) => ({
      id: node.id,
      type: node.type,
      pos: node.pos,
      size: node.size,
      order: node.order,
      mode: node.mode,
      flags: node.flags,
      widgetsValues: node.widgets_values,
      inputs: node.inputs?.map(({ name, type, link }) => ({
        name,
        type,
        link
      })),
      outputs: node.outputs?.map(({ name, type, links }) => ({
        name,
        type,
        links
      }))
    })),
    links: workflow.links,
    groups: workflow.groups,
    reroutes: workflow.extra?.reroutes,
    linkExtensions: workflow.extra?.linkExtensions
  }
}

async function exportedProjection(
  comfyPage: ComfyPage
): Promise<WorkflowProjection> {
  return projectWorkflow(await comfyPage.workflow.getExportedWorkflow())
}

for (const vueNodesEnabled of [false, true]) {
  test.describe(
    `legacy workflow save and full reload with VueNodes=${vueNodesEnabled}`,
    {
      tag: vueNodesEnabled
        ? ['@canvas', '@widget', '@vue-nodes']
        : ['@canvas', '@widget']
    },
    () => {
      test.afterEach(async ({ comfyPage }) => {
        await comfyPage.workflow.setupWorkflowsDirectory({})
      })

      test('preserves exact nodes, links, groups, reroutes, and widget values', async ({
        comfyPage
      }) => {
        test.slow()
        test.info().annotations.push({
          type: 'fixture-provenance',
          description:
            'Generated by the frontend v1.52.5 tag (abf63b48b3) from repository fixture 7972550f6b, then saved by its graph serializer'
        })

        const expected = projectWorkflow(fixture)
        expect(expected.nodes.length).toBeGreaterThan(0)
        expect(expected.links?.length).toBeGreaterThan(0)
        expect(expected.groups?.length).toBeGreaterThan(0)
        expect(expected.reroutes?.length).toBeGreaterThan(0)
        expect(
          expected.nodes.filter(({ widgetsValues }) => widgetsValues?.length)
            .length
        ).toBeGreaterThan(0)

        await comfyPage.workflow.loadWorkflow('legacy-v1.52.5-entity-roundtrip')
        expect(await exportedProjection(comfyPage)).toEqual(expected)

        await comfyPage.menu.topbar.saveWorkflow('legacy-v1.52.5-resaved')
        await comfyPage.workflow.reloadAndWaitForApp()

        await expect.poll(() => exportedProjection(comfyPage)).toEqual(expected)
      })
    }
  )
}
