/**
 * Curated tag options for ComfyHub workflow publishing.
 * Sourced from https://github.com/Comfy-Org/workflow_templates/blob/main/templates/index.json
 *
 * To regenerate: npx tsx temp/scripts/extract-comfyhub-tags.ts
 */
export const COMFY_HUB_TAG_OPTIONS = [
  '3D',
  '3D Model',
  'Anime',
  'API',
  'Audio',
  'Audio Editing',
  'Audio to Audio',
  'Audio to Video',
  'Brand',
  'Brand Design',
  'Canny',
  'Character',
  'Character Reference',
  'ControlNet',
  'Depth Map',
  'Fashion',
  'FLF2V',
  'Frame Interpolation',
  'icon',
  'Image',
  'Image Edit',
  'Image Enhancement',
  'Image to 3D',
  'Image to Image',
  'Image to Model',
  'Image to Video',
  'Image Upscale',
  'Inpainting',
  'Layer Decompose',
  'Layout Design',
  'LLM',
  'Mockup',
  'Motion Control',
  'Multiple Angles',
  'Music',
  'Normal Map',
  'OpenPose',
  'Outpainting',
  'Portrait',
  'Pose transfer',
  'Preprocessor',
  'Product',
  'Relight',
  'Remove Background',
  'Replacement',
  'Style Reference',
  'Style Transfer',
  'Text to Audio',
  'Text to Image',
  'Text to Model',
  'Text to Speech',
  'Text to Video',
  'Text-to-Image',
  'Turbo',
  'Vector',
  'Video',
  'Video Edit',
  'Video Extension',
  'Video to Video',
  'Video Upscale',
  'Voice Cloning'
] as const
