name: PR Storybook Deploy (Forks)

on:
  workflow_run:
    workflows: ['Chromatic']
    types: [requested, completed]

env:
  DATE_FORMAT: '+%m/%d/%Y, %I:%M:%S %p'

jobs:
  deploy-and-comment-forked-pr:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'Comfy-Org/ComfyUI_frontend' && 
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.head_repository.full_name != github.event.workflow_run.repository.full_name &&
      (github.event_name == 'workflow_dispatch' || startsWith(github.event.workflow_run.head_branch, 'version-bump-'))
    permissions:
      pull-requests: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PR Number
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            
            const pr = prs.find(p => p.head.sha === context.payload.workflow_run.head_sha);
            
            if (!pr) {
              console.log('No PR found for SHA:', context.payload.workflow_run.head_sha);
              return null;
            }
            
            console.log(`Found PR #${pr.number} from fork: ${context.payload.workflow_run.head_repository.full_name}`);
            return pr.number;

      - name: Handle Storybook Start
        if: steps.pr.outputs.result != 'null' && github.event.action == 'requested'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          chmod +x scripts/cicd/pr-storybook-deploy-and-comment.sh
          ./scripts/cicd/pr-storybook-deploy-and-comment.sh \
            "${{ steps.pr.outputs.result }}" \
            "${{ github.event.workflow_run.head_branch }}" \
            "starting" \
            "$(date -u '${{ env.DATE_FORMAT }}')"

      - name: Download and Deploy Storybook
        if: steps.pr.outputs.result != 'null' && github.event.action == 'completed'
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: storybook-static
          path: storybook-static
          
      - name: Get workflow conclusion
        if: steps.pr.outputs.result != 'null' && github.event.action == 'completed'
        id: workflow-status
        uses: actions/github-script@v7
        with:
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            
            return {
              conclusion: run.data.conclusion,
              url: run.data.html_url
            };
          
      - name: Handle Storybook Completion
        if: steps.pr.outputs.result != 'null' && github.event.action == 'completed'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          GITHUB_TOKEN: ${{ github.token }}
          WORKFLOW_CONCLUSION: ${{ fromJSON(steps.workflow-status.outputs.result).conclusion }}
          WORKFLOW_URL: ${{ fromJSON(steps.workflow-status.outputs.result).url }}
        run: |
          chmod +x scripts/cicd/pr-storybook-deploy-and-comment.sh
          ./scripts/cicd/pr-storybook-deploy-and-comment.sh \
            "${{ steps.pr.outputs.result }}" \
            "${{ github.event.workflow_run.head_branch }}" \
            "completed"