name: size data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  collect:
    if: github.repository == 'Comfy-Org/ComfyUI_frontend'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Collect size data
        run: node scripts/size-collect.js

      - name: Save PR number & base branch
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo ${{ github.event.number }} > ./temp/size/number.txt
          echo ${{ github.base_ref }} > ./temp/size/base.txt

      - name: Upload size data
        uses: actions/upload-artifact@v4
        with:
          name: size-data
          path: temp/size
