name: Update ComfyUI-Manager API Types

on:
  # Manual trigger
  workflow_dispatch:

jobs:
  update-manager-types:
    runs-on: ubuntu-latest
    steps:
      - uses: Comfy-Org/ComfyUI_frontend_setup_action@v2.3

      - name: Checkout ComfyUI-Manager repository
        uses: actions/checkout@v4
        with:
          repository: Comfy-Org/ComfyUI-Manager
          path: ComfyUI-Manager

      - name: Get Manager commit information
        id: manager-info
        run: |
          cd ComfyUI-Manager
          MANAGER_COMMIT=$(git rev-parse --short HEAD)
          echo "commit=${MANAGER_COMMIT}" >> $GITHUB_OUTPUT
          cd ..

      - name: Generate Manager API types
        run: |
          echo "Generating TypeScript types from ComfyUI-Manager@${{ steps.manager-info.outputs.commit }}..."
          npx openapi-typescript "$(pwd)/ComfyUI-Manager/openapi.yaml" --output ./ComfyUI_frontend/src/types/generatedManagerTypes.ts

      - name: Validate generated types
        run: |
          if [ ! -f ./ComfyUI_frontend/src/types/generatedManagerTypes.ts ]; then
            echo "Error: Types file was not generated."
            exit 1
          fi

          # Check if file is not empty
          if [ ! -s ./ComfyUI_frontend/src/types/generatedManagerTypes.ts ]; then
            echo "Error: Generated types file is empty."
            exit 1
          fi

      - name: Debugging info
        run: |
          echo "Branch: ${{ github.head_ref }}"
          git status
        working-directory: ComfyUI_frontend

      - name: Commit updated types
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch origin ${{ github.head_ref }}
          git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }}
          git add src/types/generatedManagerTypes.ts
          git commit -m "[chore] Update ComfyUI-Manager API types from ComfyUI-Manager@${{ steps.manager-info.outputs.commit }}" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
        working-directory: ComfyUI_frontend
