name: Update API Types

on:
  # Manual trigger
  workflow_dispatch:

  # Triggered from comfy-api repo
  repository_dispatch:
    types: [comfy-api-updated]

jobs:
  update-api-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ComfyUI_frontend
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Checkout comfy-api repository
        uses: actions/checkout@v4
        with:
          repository: Comfy-Org/comfy-api
          path: comfy-api
          token: ${{ secrets.COMFY_API_PAT }}

      - name: Get API commit information
        id: api-info
        run: |
          cd comfy-api
          API_COMMIT=$(git rev-parse --short HEAD)
          echo "commit=${API_COMMIT}" >> $GITHUB_OUTPUT

      - name: Generate API types
        run: |
          echo "Generating TypeScript types from comfy-api@${{ steps.api-info.outputs.commit }}..."
          npx openapi-typescript comfy-api/openapi.yml --output src/types/comfyRegistryTypes.ts

      - name: Validate generated types
        run: |
          if [ ! -f src/types/comfyRegistryTypes.ts ]; then
            echo "Error: Types file was not generated."
            exit 1
          fi

          # Check if file is not empty
          if [ ! -s src/types/comfyRegistryTypes.ts ]; then
            echo "Error: Generated types file is empty."
            exit 1
          fi

      - name: Check for changes
        id: check-changes
        run: |
          if [[ -z $(git status --porcelain src/types/comfyRegistryTypes.ts) ]]; then
            echo "No changes to Comfy Registry API types detected."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Changes detected in Comfy Registry API types."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create PR for API type changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # Create branch with timestamp
          DATE=$(date '+%Y-%m-%d')
          TIMESTAMP=$(date '+%s')
          BRANCH="update-registry-types-${DATE}-${TIMESTAMP}"
          git checkout -b $BRANCH

          # Commit changes
          git add src/types/comfyRegistryTypes.ts
          git commit -m "[chore] Update Comfy Registry API types from comfy-api@${{ steps.api-info.outputs.commit }}"
          git push origin $BRANCH

          # Create PR
          gh pr create \
            --title "Update Comfy Registry API types from comfy-api@${{ steps.api-info.outputs.commit }}" \
            --body "Automated update of Comfy Registry API types from the latest comfy-api OpenAPI specification." \
            --label "dependencies,auto-generated" \
            --base main \
            --head $BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
